### ISSUE TITLE
Subprocess mode using captured Subprocess output fails

### ISSUE THREAD

**Issue by TobalJackson** [xonsh/xonsh#1022]
Hello, I'm running the latest commit of xonsh and experience the following issue:

Whenever I run a command in subprocess mode which is using as an argument(s) the output of another subprocess command, the resulting string is incorrectly treated as a single argument.  A simple example is to run:

<pre>
file $(ls)
</pre>

The expected output is for file to see X number of arguments and run on each of them. Instead this is the result:

![](https://i.imgur.com/NSTwvkb.png)

When I use xonsh from `pip3 install xonsh` the command runs successfully as expected:
![](https://i.imgur.com/ccGgUHT.png)

**Comment by Siecje** [comment]
This is a regression from version ```0.3.0``` and only happens if installed from current git master which is currently https://github.com/scopatz/xonsh/commit/67ac9cd5e1819afde45ea561853fc571826828aa.

**Comment by melund** [comment]
I am not sure. I thought this was intended. I thought you needed to do `file @([x.strip() for x in $(ls).split()])` to accomplish that. Not that nice though which is also the reason for the new subproc shorthand operator `@$()`. 

So you could write `file @$(ls)`

**Comment by TobalJackson** [comment]
Hmm, well all I know is, typing `file @$(ls)` instead of `file $(ls)` is more complicated, and breaks compatibility with the BASH-like way of doing something as simple as process substitution.  As of now,  I've gone from -dev to the pip3 version of xonsh just to maintain this capability/feature which I think is much more straightforward.

I could be wrong however.

**Comment by adqm** [comment]
The problem, I think, is that `$()` only worked like bash-style command substitution in some cases anyway (running `$(which ls)`, for example, wouldn't work), and its behavior was inconsistent between Python mode (where it always returned a full string of the output) and subprocess mode (where its output was split around newlines, and each piece was added to the list of subproc arguments).

It's possible there are better choices than the one we made, but on the current master, `$()` always returns a single string containing the whole output of a command, and `@$()` forces subproc mode, splits its output, and adds the pieces to the subproc args.

To me personally, that internal consistency wins over Bash-compatibility.

**Comment by scopatz** [comment]
> To me personally, that internal consistency wins over Bash-compatibility.

+100, I also this it would help to explain a bit about how Bash's `$()` operator and Bash's interpreter.

In Bash, the `$()` operator returns a string of stdout of the command.  Say we have a dir with an `a`, `b`, and `c` file.  If we run `ls -l` in this dir, and force the output of `$()` to be captured as a string using quotes, we see that the newlines are captured and printed:

```bash
scopatz@artemis:~/temp$ echo "$(ls -1)"
a
b
c
```

However, if we don't use quotes to capture the `$()` output, than the Bash *interpreter* will automatically split the output based on whitespace, and pass each element in as its own argument. It is the interpreter that creates an split array of strings, not the `$()` operator.  We can see this in the following:

```bash
scopatz@artemis:~/temp$ echo $(ls -1)
a b c
```

The newlines are now gone and the filenames all appear on the same line. Additionally, note that because this is the interpreter doing this, we can change its behaviour at run time. Setting the `$IFS` variable to any other character will split based on that character, instead of whitespace. So say we wanted to split on colons, then we would no longer split on whitespace and our newlines would be preserved:

```bash
scopatz@artemis:~/temp$ export IFS=':'
scopatz@artemis:~/temp$ echo $(ls -1)
a
b
c
```

So, in fact, the `$()` operators are pretty much exactly the same between xonsh and Bash. The difference is that the semantics of xonsh do not split all arguments for you. 

My opinion is that while this rule may be more strict, it is also more precise. It allows xonsh code developers to know exactly what they are getting from their command arguments without much worry.  In Bash, one ought to be concerned about the value of IFS almost all the time, though in practice no one does and it is (by convention) dangerous to change with out changing it back. This is a fact made worse by Bash's lack of error handling, limited context management, and that almost no one uses Bash's local-only variables.

I think using `@$()` is a nice compromise, all things considered.

**Comment by melund** [comment]
Yes. This what I meant by intended behavior I just don't have a good grasp of how things work in bash.

 Also, I think I remember @scopatz suggested that the syntax could be expanded with function argument: `@func$(command)` to do custom filtering of the output.  Nice since it resembles the decorator idea. 

I was also thinking that we could make simple version with string to specify which characters to split at. E.g  `@':'$(command)` would split output at `:`

**Comment by scopatz** [comment]
> I was also thinking that we could make simple version with string to specify which characters to split at. E.g @':'$(command) would split output at :

I have been thinking about something like this too :)
