### ISSUE TITLE
XONSH_SHOW_TRACEBACK to a log file.

### ISSUE THREAD

**Issue by Carreau** [xonsh/xonsh#1025]
Would it be possible to set XONSH_SHOW_TRACEBACK to a filepath, and if so have the traceback dump to this file ?

**Comment by melund** [comment]
Yes. I think that would be possible, and not that hard to do. We would just have to add a little code here: https://github.com/scopatz/xonsh/blob/e5217a8816ca3b48c3f30e885a5d09dee612742d/xonsh/tools.py#L360

Maybe also add XONSH_SHOW_TRACEBACK to the DEFAULT_ENSURES with some functionality to validate its type.  https://github.com/scopatz/xonsh/blob/5d32a74a54e87e778b2f5b3aea19c353caa9f379/xonsh/environ.py#L64 

A PR would very welcome :)

**Comment by VHarisop** [comment]
Hey there, is anyone working on this one?

From what I understand from the above discussion, @Carreau proposed that instead of just `True/False`, a string containing a filepath would also be acceptable and force traceback info to be dumped there.

If that is indeed the case, this would be somewhat confusing with respect to both the programmer and the end-user as well (consider the following .xonshrc file):

```
$ cat .xonshrc
XONSH_SHOW_TRACEBACK = 'True'
```

This can be interpreted in at least two ways:
- create a log file called `True` and output traceback info there (i.e. treated like a string / filepath) or
- output traceback info to stderr (i.e. treated like a boolean, after converting it to `str` and matching it against `'True'` and `'False'`)

I propose that, instead, an extra parameter called something like `XONSH_TRACEBACK_FILE` be introduced, and traceback info to be output there only if `XONSH_SHOW_TRACEBACK` is set to `True`.

I could a submit a PR in the following days, if you agree on the above :)

**Comment by Carreau** [comment]
Yeah, I was unsure about the exact semantics, but a general debug log file, not only for traceback would make sens. 

`XONSH_SHOW_TRACEBACK=True|False` could also be dropped in favor of 

`XONSH_TRACEBACK_FILE` and with specific value like `<stdout>|<stderr>|<devnull>`. 

In general (I know I'm becoming old and grumpy) I'm starting to prefer not to duplicate settings.

**Comment by scopatz** [comment]
Hi @VHarisop - no one is working on this right now to the best of my knowledge and a PR would be most welcome!  I also prefer not duplicating envvars, but I also prefer the `$XONSH_SHOW_TRACEBACK` name.  My vision for how this would work is:

```console
$XONSH_SHOW_TRACEBACK = False  # as bool, doesn't display
$XONSH_SHOW_TRACEBACK = True  # as bool, displays to stderr
$XONSH_SHOW_TRACEBACK = '/path/to/file'  # will display both on stderr and write to the file
```

Note that going to /dev/null is not the same as setting this to False.

**Comment by Carreau** [comment]
We can easily detect and alias /dev/null to False, even if this is [frowned upon](https://lists.gnu.org/archive/html/bug-tar/2010-03/msg00054.html)

**Comment by scopatz** [comment]
Not a bad idea :)

**Comment by VHarisop** [comment]
What do you think should be the default behavior if the user has specified an invalid filepath (e.g. nonexisting directory or file/directory without write permissions)?

I was thinking that defaulting to `stderr` would be a sensible choice, but I wouldn't call it obvious.

**Comment by laerus** [comment]
Solved!
