### ISSUE TITLE
Consider adding zsh-like directory completion

### ISSUE THREAD

**Issue by stefanv** [xonsh/xonsh#1046]
In zshell, I can type e.g. `cd ~/D/S`, which upon TAB will expand to `cd ~/Dropbox/Shared`.

Any hints on how I can add this to Xonsh?

**Comment by adqm** [comment]
Wow, didn't know that about zsh; that's pretty neat!  Would definitely be good to have in xonsh.

I think it is likely that there will be a change to how tab completion is handled in the near future, via #1027.  If that comes through, this change would probably involve modifying `xonsh.completers.path.complete_path`, to make it include those new elements in the set of elements it returns (rather than adding a new completer to the list).

If that doesn't come through, the right place to change is the analogous [`xonsh.completer.path_complete`](https://github.com/scopatz/xonsh/blob/master/xonsh/completer.py#L408-L423) in the current master.

It is possible that the function that does that expansion is something that could be used elsewhere, so it might make some sense to include it in `xonsh.tools` and to import it for the completer.

**Comment by scopatz** [comment]
Sounds like a nice idea! Probably best to wait until the new completion stuff is in before tackling this, though.

**Comment by gforsyth** [comment]
This has been available for quite some time now, just missed closing this out.
