### ISSUE TITLE
emacs mode for editing .xsh files

### ISSUE THREAD

**Issue by asmeurer** [xonsh/xonsh#1074]
xonsh needs an emacs mode.

**Comment by scopatz** [comment]
Pull requests welcome. I believe that that if one uses the readline shell, then then there is a readline mode available.  For prompt-toolkit, while we could implement a readline mode, this is more appropriately  a prompt-toolkit feature.  Maybe @jonathanslenders has some thoughts?

**Comment by adqm** [comment]
Well, ptk has almost all of the emacs keybindings already (movement, marks, kill and yank).  Readline has some of these by default (movement and yank), and one can bind `set-mark` and `kill-region` to keybindings.

@asmeurer, if I'm not mistaken, you're not asking about keybindings within xonsh, but rather a "mode" within emacs for working with xonsh?

**Comment by asmeurer** [comment]
Yeah, this isn't about using xonsh. It's about editing xonsh files in emacs. It works pretty well if you set the mode to python-mode (and disable flycheck), but it would be nice, for instance, to have smarter syntax highlighting.

**Comment by scopatz** [comment]
Is this something that xonsh would package and install?  Or would this have to come stock with emacs?  In any event, this is something that an emacs user should implement.  We'd be happy to have this as a contribution.

**Comment by asmeurer** [comment]
I'm not super familiar, but I think the correct thing is to upload it to MELPA.

**Comment by asmeurer** [comment]
FWIW I'm currently using

```elisp
(define-derived-mode xonsh-mode python-mode "Xonsh Mode"
  "A mode for .xsh files.")

(add-to-list 'auto-mode-alist '("\\.xsh\\'" . xonsh-mode))
```

which basically makes a new mode based on python-mode. This takes care of things that work for Python like basic syntax highlighting. It also apparently prevents flycheck from using the Python linters.

**Comment by salotz** [comment]
MELPA is the way to go. There should be a mode for using it in emacs too though :P

**Comment by asmeurer** [comment]
I changed the title because people assumed it meant emacs shortcuts inside xonsh itself. I agree xonsh-mode should probably also include ways to call xonsh from emacs, or even use it as the shell in emacs (though I personally don't care about either of those things).

**Comment by eggcaker** [comment]
+1

**Comment by scopatz** [comment]
This is an emacs feature request. If this exists, we are happy to include links in our docs!

**Comment by salotz** [comment]
Note this exists: https://github.com/seanfarley/xonsh-mode I would be willing to (when I have the urge to) get the authors consent and do the uploading to melpa (from my fork https://github.com/salotz/xonsh-mode).

**Comment by salotz** [comment]
As a note for distributing emacs mode with the xonsh. It shouldn't be installed by any xonsh thing, but including the single xonsh-mode.el file in the source tree with a direct link in the docs is a common practice and easy to maintain. These editing modes are lightweight and don't change much unless the syntax or recognized file extensions change. Some emacs users work only this was, some like to use the package manager and a repo like melpa. I favor the latter when I can but copy-pasting elisp files is also pretty easy. I would just let the community support the melpa package.

**Comment by scopatz** [comment]
Thanks for pointing this out @salotz! CC @seanfarley

**Comment by seanfarley** [comment]
(Sorry for the late reply; I've been out of town for the past week)

I'm not sure what y'all want me to do here so I'll just outline what I was thinking when I wrote `xonsh-mode` and what I had in mind for the future:

* As a personal habit, mainly because my emacs-lisp isn't that great, I usually write a package and use it in my day-to-day workflow for a couple of weeks before attempting to distribute it
*  I was planning on making a melpa package for it (I'm fine to do that this week, if yall want) but kinda forgot about it because I've been using quelpa
* Now that I think about it, we could just add this emacs mode to the xonsh repo and have melpa use that (just like [erlang does](https://github.com/melpa/melpa/blob/898cc59239f9aef6012baabf29fa35a9c7fd8d70/recipes/erlang)
* Alternatively, we could just move the repo to `xonsh/xonsh-mode` or something if the community wants it be a bit more official

I have no real preference and I'll try to look at @salotz's commits in his fork this week.

**Comment by salotz** [comment]
I changed no code, just some installation instructions that emacs veterans already know.

**Comment by seanfarley** [comment]
Ok, this is [now in melpa](https://github.com/melpa/melpa/pull/6587)! I'll update the instructions in the repo as well :-)
