### ISSUE TITLE
Xonsh.org should redirect to xon.sh

### ISSUE THREAD

**Issue by jxcl** [xonsh/xonsh#1077]
The domain name xonsh.org is still active and serving an outdated version of the documentation. To avoid user confusion it should automatically redirect to xon.sh.

**Comment by scopatz** [comment]
Hi @jxcl - yep, I agree!  We don't know who owns this yet though...

**Comment by jxcl** [comment]
If xonsh.org is not under the project's control, can I suggest using a different documentation theme for xon.sh to make it more obvious that it is a different site?

**Comment by scopatz** [comment]
Well, someone took our docs and our project name, so the right thing to do would be for them to come forward and/or redirect to xon.sh

**Comment by melund** [comment]
Hopefully, it was acquired by someone with good intentions. In Denmark, there is a big problem with domains beeing hijacked and used for scams as soon as they run out. Does anyone know if there are other ways to get the domain back or shut it down?

**Comment by adqm** [comment]
> there is a big problem with domains beeing hijacked 

Unfortunately, I would guess at this. xonsh.org may not be the best bet for someone who wants to scam people, but I could imagine someone buying up the domain on the cheap to try to sell it back to the original owner at a higher price, or something like that...

**Comment by CJ-Wright** [comment]
Hey, at least it doesn't redirect to zshell.

**Comment by scopatz** [comment]
I can think of worse shells :)

**Comment by jleclanche** [comment]
Was it hijacked? Looking at the whois shows that it's currently owned by a domain squatting registry. It's confusing if it *was* hijacked, because [its been submitted to HN several times](https://news.ycombinator.com/from?site=xonsh.org), [unlike xon.sh](https://news.ycombinator.com/from?site=xon.sh).

If you're certain it's in bad faith, you can file a complaint at cloudflare since the dns is currently handled by them. It probably won't get you the domain name itself, but they may be able to help. https://www.cloudflare.com/abuse/form

**Comment by lightdot** [comment]
I just posted a wrong link somewhere because of this bogus .org site.

The .org domain has CoudFlare's DNS, the IPs actually used to host (or proxy to) content also belong to CloudFlare.

Contacting Cloudflare would be a proper thing to do, perhaps followed by contacting the domain registrar ( pheenix.com ). Registrant is, sadly, "privacy protected", so the domain whois doesn't help.

Registrant can squat on a domain if he thinks it will get him anything, just don't let them impersonate the project. Copyright rights should help here, if it comes to that.

**Comment by scopatz** [comment]
OK, I have submitted an abuse form and I am working on getting a trademark as well.

**Comment by scopatz** [comment]
Time to contact quickpacket, I guess?

**Comment by santagada** [comment]
http://xonsh.org/ is still up and pointing to 0.2.4 docs, can't we do anything about it?

**Comment by scopatz** [comment]
I wish I knew who owned it.  I have started contacting the hosting services to complain about copyright, but it hasn't been very responsive.

**Comment by CJ-Wright** [comment]
Any progress on this? Sometimes `xon.sh` shows up before the proper url in google.

**Comment by scopatz** [comment]
I wish there was...

**Comment by offero** [comment]
I, too, was browsing xonsh.org for a while before stumbling on xon.sh. I think it's important to find a way to clarify that xonsh.org is not the right place and xon.sh is the right place someone prominent.

**Comment by melund** [comment]
@offero. Yes. Any good ideas would be appreciated.

**Comment by JulesGM** [comment]
Can you complain to ICANN? or whatever registrar. If they lost the domain that would be an ok resolution of this issue

**Comment by astronouth7303** [comment]
I'm going to send a series of emails to the various packagers that ship xonsh in the various distros.

**Comment by scopatz** [comment]
Thanks @astronouth7303!  I could try complaining to ICANN, I haven't done that...

**Comment by astronouth7303** [comment]
So far, the people that have responded have no idea.

**Comment by JulesGM** [comment]
I was thinking, it's normal for Cloudfare to not want to reveal who there client is. 
However, maybe a letter could be written to the client, and they could **forward it** to them, without telling who they are.

There is a non negligible possibility that the client just either doesn't realize they're hosting this, or doesn't realize they're hurting, and that therefore they would be receptive to such a letter.

**Comment by scopatz** [comment]
I have reacquired xonsh.org and redirected it to xon.sh, finally.

**Comment by JulesGM** [comment]
congrats!

**Comment by scopatz** [comment]
Thanks!

**Comment by gforsyth** [comment]
YAAAAAYYYYYY!

I started using Octobox and then forgot I was using it and I missed this.  Fantastic news!
