### ISSUE TITLE
How to enable a pyvenv/venv in xonsh ?

### ISSUE THREAD

**Issue by GMLudo** [xonsh/xonsh#108]
Hi,

As you understand, I'm trying to replace bash by xonsh.
I've an issue when I try to enable a pyvenv in xonsh:

    $ . pyvenv/bin/activate
    Traceback (most recent call last):
    File "/usr/local/lib/python3.4/dist-packages/xonsh/shell.py", line 109, in default
        self.execer.exec(code, mode='single', glbs=None, locs=self.ctx)
    File "/usr/local/lib/python3.4/dist-packages/xonsh/execer.py", line 110, in exec
        return exec(code, glbs, locs)
    File "<xonsh-code>", line 1, in <module>
    File "/usr/local/lib/python3.4/dist-packages/xonsh/built_ins.py", line 383, in subproc_uncaptured
        return run_subproc(cmds, captured=False)
    File "/usr/local/lib/python3.4/dist-packages/xonsh/built_ins.py", line 355, in run_subproc
        stdin=stdin, stdout=stdout)
    File "/usr/lib/python3.4/subprocess.py", line 848, in __init__
        restore_signals, start_new_session)
    File "/usr/lib/python3.4/subprocess.py", line 1446, in _execute_child
        raise child_exception_type(errno_num, err_msg)
    PermissionError: [Errno 13] Permission denied

I understand the stacktrace, but, how I could enable a pyvenv in xonsh ?

BTW, thanks a lot for xonsh, I like it a lot.
At least for me, it was the missing piece I'm waiting to replace bash by a more Pythonic console, and keep in the same time some facilities of bash.

**Comment by scopatz** [comment]
Hi @GMLudo, you are trying to source the activate file. To source bash files, we have the `source-bash` alias.  You should be able to do the following:

```console
$ source-bash pyvenv/bin/activate
```

The permission error here is kinda funny because it is basically saying that the current directory (`.`) is not executable.

> BTW, thanks a lot for xonsh, I like it a lot. At least for me, it was the missing piece I'm waiting to replace bash by a more Pythonic console, and keep in the same time some facilities of bash.

Thanks!  We're glad you like it!  If there are bugs or things that you want to see improved, please don't hesitate to report them.  Pull requests are even better!

**Comment by GMLudo** [comment]
Thanks for `source-bash`, it works pretty well. The yocto detail I'm still missing is that `activate` script change the bash prompt to show the context change, it isn't the case with xonsh.

> Thanks! We're glad you like it! If there are bugs or things that you want to see improved, please don't hesitate to report them. Pull requests are even better!

For now, I'm trying to be iso-functionnal with I had with bash.
After, my long term plan, is to add some features you have with `oh my zsh` like to know the branch you  have when you are in a Git folder. Or at least, hope that somebody else in xonsh community adds that ;-)

**Comment by aig787** [comment]
I'm interested in getting the prompt to change as well. @scopatz is there a better approach than just parsing the bash prompt? Ultimately I'd like to have virtualenv-wrapper like functionality built in so we wouldn't need to worry about it.

**Comment by wrywerytwreywery** [comment]
I am not sure about the virtualenv stuff, but customizing the prompt in a general sense is possible (see [this section](http://xonsh.org/tutorial#customizing-the-prompt) of the xonsh tutorial).

I haven't tested, but if virtualenv is setting `$PS1` to try to make that change, it seems like you could set your xonsh prompt always to read that value from the environment:
`$PROMPT = lambda: $PS1`

...though though that would require doing some transformation on the bash prompt as well to translate it to xonsh's format (could be just replacing the bash prompt's escaped characters with relevant `{variable}` strings, and adding those variables to `FORMATTER_DICT`).  It could be the case that we want to have something equivalent to `bash_aliases`, but for prompts, to facilitate this kind of change...

**Comment by scopatz** [comment]
For conda, you can probably do something like:

```console
$FORMATTER_DICT['conda'] = lambda: $CONDA_DEFAULT_ENV
```

And then you modify the PROMPT to use this variable. I would imagine it is similar for virtual env.  This should probably be added to the default formatter.  PRs welcome!

**Comment by logavanc** [comment]
I wasn't sure where to try and provide my input on this... but I thought this thread seemed appropriate.

Since this is a Python-ish shell, couldn't there just be a builtin command to activate the virtualenv?  For example, you could have a builtin `activate` command which accepts a path to a virtual environment.  So if you were in the virtual environment directory, you would just write:

```activate .```

Then you could easily do all the path manipulation stuff to show the current virtual environment.

**Comment by scopatz** [comment]
Hi @logavanc - yes there could be!  It is just a matter of writing an alias function. A pull request for this would be very welcome. I am not a virtualenv user myself, so it would better to rely on someone who is :)

**Comment by frol** [comment]
It seems that `source-bash` works only partially.

```
frol@redatopa ~ $ which python
/usr/bin/python

frol@redatopa /tmp $ virtualenv env
Using base prefix '/usr'
New python executable in env/bin/python3
Also creating executable in env/bin/python
Installing setuptools, pip, wheel...done.

frol@redatopa /tmp $ source-bash env/bin/activate
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/xonsh/proc.py", line 338, in wrapped_simple_command
    r = f(args, i)
  File "/usr/lib/python3.5/site-packages/xonsh/aliases.py", line 109, in source_bash
    return source_foreign(args, stdin=stdin)
  File "/usr/lib/python3.5/site-packages/xonsh/aliases.py", line 94, in source_foreign
    if k in env and v == denv[k]:
KeyError: 'PS1'

frol@redatopa /tmp $ which python
/tmp/env/bin/python
```

So the correct PATH is set though an error has been raised. However, how do I deactvate then?

```
frol@redatopa /tmp $ deacivate
xonsh: subprocess mode: command not found: deacivate

frol@redatopa /tmp $ source deacivate
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/xonsh/proc.py", line 338, in wrapped_simple_command
    r = f(args, i)
  File "/usr/lib/python3.5/site-packages/xonsh/aliases.py", line 116, in source_alias
    fname = locate_binary(fname, cwd=None)[:-1]
TypeError: 'NoneType' object is not subscriptable

frol@redatopa /tmp $ source-bash deacivate

frol@redatopa /tmp $ which python
/tmp/env/bin/python
```

Even though `source-bash deactivate` didn't fail, it didn't make any PATH-cleaning either.

**Comment by scopatz** [comment]
Thanks for reporting @frol, there definitely was a bug triggered by the sourcing.  #617 should fix this.  

As per deactivate, if you are using the stock virtualenv, you should be able to run just `deactivate` since this is a [shell function](https://hg.python.org/cpython/file/3.5/Lib/venv/scripts/posix/activate#l4). The reason that you are not is because of the previous KeyError.  When you run `source-bash deactivate` you are probably picking up some other deactivate. Do a `which deactivate` to find out what is going on there. 

Let us know what happens with the fix. 

Alternatively, you may consider using virtualenvwrapper (shell based) or [virtualxonsh](https://github.com/riccardomurri/virtualxonsh) (xonsh based) as an alternative.

**Comment by frol** [comment]
@scopatz Works fine now! Super! (it seems I made a typo which is why deactivate didn't work for me the first time, sorry)

**Comment by scopatz** [comment]
Awesome @frol!

**Comment by brunobeltran** [comment]
BTW, this issue has been totally resolved from what I can tell, @scopatz. So it can probably be closed.

**Comment by scopatz** [comment]
@brunobeltran - great!  Please feel free to reopen.
