### ISSUE TITLE
Backslash doesn't escape spaces in subprocess mode

### ISSUE THREAD

**Issue by asmeurer** [xonsh/xonsh#1084]
This is problematic for paths with spaces in them. Say I have a directory "this dir". If I run

```
ls this\ dir
```

it tells me that `this\` and `dir` do not exist. 

You can get the right thing if you quote the path. But the problem here is that quoting paths is annoying. For instance, say you have `this dir/something` and tab complete `this dir`. The tab completer in prompt_toolkit will complete `'this dir'` (the readline completer isn't as smart). But then you have to delete the `'` and type the next thing. If you are recursing, you have to keep doing this. @scopatz has told me that quotes in the middle of tokens will becoming syntax error, so `'test dir/'something` isn't an option. 

Actually, it looks like the prompt toolkit completer is smart enough to complete `'test dir/'som` to `'test dir/something'`. Even so, I think for a shell, it is highly expected for \ to escape spaces. Even Python's shlex works this way.

**Comment by melund** [comment]
We have a problem called windows :( But maybe there is a way around it.

**Comment by adqm** [comment]
I'm actually in the camp that thinks this is the right thing to do; i.e., using Python strings is the most straightforward way to do escaping to me (even though it takes a while to develop new muscle memory).

One issue with backslashes is that backslash is used as a separator for Windows.  But beyond that, I think there is a big benefit to having only one means of escaping, which behaves largely the same way in Python mode as in subproc mode, rather than having to learn different escaping rules for each.  Plus, I think the fact that the tab completer generally works makes wrapping things in quotes way less painful than it would otherwise be.

> But then you have to delete the ' and type the next thing.  If you are recursing, you have to keep doing this.

No you don't.  Just start typing the next thing and tab-complete again (it should quote properly).

> the readline completer isn't as smart

I only use readline, and the quoting on completions is working for me just fine (all of your examples complete just fine for me).  I'm not sure what the issue is.

> Even so, I think for a shell, it is highly expected for \ to escape spaces. Even Python's shlex works this way. 

`shlex` works that way because it is a lexer for `sh`-based languages.

IMHO, this is one place where the goal of internal consistency should trump the goal of being compatible with other Unix shells.

So I actually think the quoting/escaping semantics are quite sensible now.  I could be wrong, and if enough people feel this way and there is a reasonable way to solve the issue, then we should do it.

**Comment by scopatz** [comment]
I pretty much agree with everything that @adqm said.  I'd add that one of my metrics for syntax is whether it makes the language easier or more difficult to learn.  We have generally resisted adding things that allow you to do `x OR y`.  The major exception to this is the `&&` and `||` in subprocess mode.  In that case, there is a bijective mapping between those `and` + `or`.  Here, there would two distinct ways to represent part of token.  

If enough people complain and there is a particular implementation that gets PR'd, I think we should consider it. But the benefits would need to outweigh the drawbacks.  For me, this fits into the same category as py2k. Worth thinking about, but something that none of the current core devs are actually interested in :)

**Comment by asmeurer** [comment]
The issue with the readline completer is that it doesn't complete in the beginning quote.  Making readline add and remove quotes correctly everywhere sounds messy, but if you can make it work, I'm for it. Knowing that tab completion actually does do the right thing here makes me feel less strong about it, although I do think this is something that will trip a lot of people up who are coming from other shells.

One thing that I think that would be useful (and this is related to another issue which I haven't opened yet) is to have a xonsh "split" buitin, which does a proper tokenized split, since `str.split` and `shlex.split` are both wrong for xonsh.

**Comment by asmeurer** [comment]
Worth noting that [some parts](http://xon.sh/tutorial.html#aliases) of xonsh are already using `shlex.split`, which allows `\` to escape spaces:

```
xonshat-docs%🐚 aliases['testing'] = 'ls the\ test'
xonshat-docs%🐚 testing
ls: the test: No such file or directory
```

**Comment by scopatz** [comment]
And you are right about the xonsh split builtin.  We have talked about something like this.

**Comment by adqm** [comment]
> The issue with the readline completer is that it doesn't complete in the beginning quote.

I'm sorry; I'm still not understanding.  Do you have an example?

On my machine, if I have a directory called `this dir` (with the space), and I do :`$ thi<tab>`, it completes to `'this dir'` with quotes.  If I have multiple completions, only those that need them are wrapped with quotes.

**Comment by asmeurer** [comment]
Maybe there was a problem because I had other things starting with the same prefix. That's a general problem with readline, exacerbated here because you have to go back and add the quote.

**Comment by santagada** [comment]
My case for adding this is that on osx when you drop a folder in a terminal somehow it pastes a line with "\ " for spaces. Also related is the fact that we don't do tab completion inside strings so wrapping a very log path that has a space is very painful.

Can prompt-toolkit detect a paste happening? Maybe we can fix 2 and then detect 1 and correct the string in that case.

**Comment by gforsyth** [comment]
Hey @santagada -- the osx pasting thing is annoying.  

As for tab completion, it should work with spaces, the quotes will just keep autowrapping.
