### ISSUE TITLE
Command line flag to not pull in bash configuration

### ISSUE THREAD

**Issue by asmeurer** [xonsh/xonsh#1089]
Discussed this with @scopatz earlier. xonsh needs a command line flag to not pull in the bash configuration.

**Comment by scopatz** [comment]
I think that this is good opportunity to bring up the possibility of removing bash as a default shell on startup. We'd have to add some stuff to `xonsh.platform` to make sure that the shell was usable in most places.  I am definitely in favor of this because it would certainly decrease startup times.

**Comment by scopatz** [comment]
I also think that this would mitigate the need for a command line flag.

**Comment by asmeurer** [comment]
Yes! I really want that.

**Comment by adqm** [comment]
Agree 100%!

**Comment by scopatz** [comment]
This has been implemented for quite some time.
