### ISSUE TITLE
add git hash to version number

### ISSUE THREAD

**Issue by gforsyth** [xonsh/xonsh#1140]
As mentioned by @Carreau in #1060

> That because __version__ is init should be 0.3.2.dev, and if possible 3.2.devX with X an increasing number (from git --describe ?)

This seems like a good idea to me -- especially as it will provide very granular information when users post `xonfig` output.

Thoughts?

**Comment by Carreau** [comment]
Likely, You also want to make sure that versin number comply to [pep440](https://www.python.org/dev/peps/pep-0440/). This  pypi package [might be of help](https://pypi.python.org/pypi/pep440) [1], or a wrong version number will be missinterprested by pip. 
Like `X.y.zRC` and `beta` **should not have dots**, while `.dev` should. Or you will have surprises, typically `tar.gz` effectively being recognized as different versions than wheels, or stable versions instead of nightly.


[1]: I need to update it

**Comment by scopatz** [comment]
Thanks for pointing out your pep440 package. This looks small enough to vend ourselves, if that is OK with you!

**Comment by Carreau** [comment]
Yeah, the regex was tricky enough to get right that I thought a package
might be a good place to store it.

**Comment by gforsyth** [comment]
@scopatz @melund @adqm @Carreau : my current idea on how to add dirty version numbers. if you have concerns/improvements I am all ears.

1. github Webhook on PR merge pings server (i can use my work machine. I was trying to think of a way to do this with CI but I can't come up with anything, suggestions?)
2. server pulls in all changes, reads out short hash from merge commit and appends it to version number in __init__.py (use @Carreau's pep440 to confirm it's valid)
3. adds and commits updated __init__.py
4. amend commit author to be something like 'xonsh version bot'
5.     push to master

Since releases aren't PRs, it wouldn't trigger this and we can always build the base-version off of the most recent / highest numbered tag

Crazy?

**Comment by scopatz** [comment]
@gforsyth - why couldn't this just be figured out in the setup.py if the repo is available?  Is the concern that this would be then be present for the CI and anaconda.org?

**Comment by Carreau** [comment]
I think that you likely can assume that when using `.dev` people have git installed, and you should be able to shell out to git, and if not just use `.dev0` I think it's fine. Plus that allows to have hash in version number for dirty tree, or things not pushed on GitHub, which might happen.

It's possible to have travis push back on main branch but it's tricky (`https://github.com/python/peps/pull/25`) you would need to do that only if current commit is a merge commit from a PR to avoid recusrions.

And honestly IIRC `.devX` is useful only if you make a build as otherwise `pip install` will always assume that `.dev` is the latest.

**Comment by gforsyth** [comment]
I'm happy to keep it simpler.  Dirty version numbers for the xonsh dev conda builds were requested in #1248 which is why I was proposing what I was.  That said, I think even having a `dev0` as @Carreau proposes would work.  I can always do that now and then add in extra stuff later if it's really needed.

**Comment by adqm** [comment]
Personally, I think it's really helpful to have the Git hash in the version number (or at least in `xonfig`), to help us track down bugs.  I like this better than just having the `.devX` version number, but the two aren't mutually exclusive.  Maybe we could do the `.devX` in the version number, but separately store the Git hash so that `xonfig` can grab it?

But the method you propose wouldn't quite work for that, @gforsyth, since it would miss the version number associated with "version bump," etc.

I'm not sure how the Conda stuff works, but it seems like a hook in `setup.py` would work for `pip`, since we could have it add that variable (`__git_hash__` or something) to the source, I think, including in the tarball that gets uploaded to pypi.  Same could go for installing straight from source.  If Conda eats a tarball or clones from the git repo directly, then presumably we could do something similar there?

That way, when we build the tarball for releases, they get the git hash; and when people build with `setup.py install`, same deal.

Unless I'm misunderstanding something?  I've been absent recently and missed (apparently) quite a lot.

**Comment by gforsyth** [comment]
First crack in #1344
