### ISSUE TITLE
classic shell like stream handling + sub shells

### ISSUE THREAD

**Issue by mburo** [xonsh/xonsh#1141]
In a recent thread there was a question how to mimic bash code like this:

`(echo "abc"; sleep 1; echo "def") | grep abc`

@adqm answered:

"Unfortunately, we don't support the "subshell" idea yet, and so it is hard to group those commands together. It is also not yet possible to use IO redirection to one of those Python objects (only to files). But something along these lines would be really nice in the future. We can think on this for a bit; there has to be a nice way."

I tried it the Python way:

```
def xxx(args='', stdin, stdout, stderr):
  print('abc', file=stdout, flush=True)
  sleep 1
  print('def', file=stdout, flush=True)
```

but

`xxx | grep abc`

just hangs and

`xxx > aaa`

works.

However, with

```
def xxx(args='', stdin, stdout, stderr):
  print('abc', file=stdout, flush=True)
  time.sleep(1)
  print('def', file=stdout, flush=True)
```

`xxx | grep abc` works. So sprinkling in shell commands interferes,
which perhaps is to be expected, unless we somehow inform them about context stdin,stdout,stderr.

It would be nice to do this implicitly like in classic shells. I.e., xonsh could adjust file descriptors 0,1,2 as needed for redirections and pipes. Then we won't need to pass on stdin,stdout,stderr.

**Comment by adqm** [comment]
I definitely agree that this is something we should have.

**Comment by scopatz** [comment]
This seems to be the kind of thing that is being discussed [on the mailing list here](https://groups.google.com/d/msgid/xonsh/CAAKrkh8MqqGix0Z7zFiBN1tj7VaOMLbURgLpWhOPjYHw%3Do7Fag%40mail.gmail.com?utm_medium=email&utm_source=footer). I guess I would want to see a proposed syntax before doing anything.

**Comment by LarryRiedel** [comment]
The kind of thing being discussed on the mailing list [there](https://groups.google.com/forum/#!msg/xonsh/1rnysYG1Uqk/CG0S0n-tBQAJ) is adding support for alternative delimiters around Python compound statement suites, in other words an alternative to using `NEWLINE INDENT` and `DEDENT` around statement lists, as in `p_suite()` in parsers/base.py.

To me using `!{` instead of `NEWLINE INDENT` with either `}` or `!}` instead of `DEDENT` seems to match things like `!()` and `![]` which xonsh already uses, but I don't know what all tokens are already used.

**Comment by scopatz** [comment]
@LarryRiedel this idea is now being discussed in #1223

**Comment by astronouth7303** [comment]
Sounds similar to #1307.

**Comment by scopatz** [comment]
See potential implementation for the original issue in #2260
