### ISSUE TITLE
Starting the X server from .xonshrc

### ISSUE THREAD

**Issue by b52** [xonsh/xonsh#1156]
So, I switched to xonsh as my default shell. No I tried to install a way to `startx` without a login manager. Previously, I simply used `~/.zprofile` to do this, but it seems there is no such thing in xonsh. But I found the environment variable `$XONSH_LOGIN`, which should come close. So, I installed a similar script at the end of my `~/.xonshrc` to do the same:

``` python
if $XONSH_LOGIN and 'DISPLAY' not in __xonsh_env__ and $XDG_VTNR == '1':
    startx -- -nolisten tcp vt1
```

However, `$XONSH_LOGIN` is `False` during the invocation of the script. If I print it in the spawned login shell it's `True` however.

**Edit:** Furthermore, if I start terms in X and look at $XONSH_LOGIN it's still `True`, which shouldn't be the case in my opinion. I assume that the login shell is the first one spawned by me, e.g., the one I use to `startx`.

**Edit2:** Good [explanation](http://unix.stackexchange.com/questions/38175/difference-between-login-shell-and-non-login-shell) of the distinction between login and non-login shell.

**Comment by adqm** [comment]
Thanks for reporting, @b52.  You are right that it looks like right now xonsh is treating `$XONSH_LOGIN` and `$XONSH_INTERACTIVE` as the same thing, which is not the right thing to do.  That logic could use some work.

**Comment by adqm** [comment]
In the meantime, one way you could hack this would be to set a dummy variable in the environment that you could later check in the other shells (since all the shells after you have started x should inherit from the first shell you use to log in).  It's not pretty, but it should get the job done (tested a little bit on my machine):

```
if 'STARTED_X' in __xonsh_env__:
    # already started x; do nothing
    pass
elif any(i in __xonsh_env__ for i in {'SSH_TTY', 'SSH_CLIENT', 'SSH_CONNECTION'}):
    # ssh'ed in; don't start x
    pass
else:
    $STARTED_X = True
    startx -- -nolisten tcp vt1
```

Hope this helps!

**Comment by astronouth7303** [comment]
Hm. Testing out some stuff mentioned in the StackExchange link above, and I don't get the leading `-` in `sys.argv` (or in procfs `cmdline`). However, I do see it when running zsh. So I'm wondering if CPython cleans this up, or if it's something weird about executing scripts vs binaries.

**Comment by astronouth7303** [comment]
Ohhhh, from the [sys module reference](https://docs.python.org/3/library/sys.html):

> `argv[0]` is the script name (it is operating system dependent whether this is a full pathname or not).

Because of how hashbangs work, what gets invoked as `xonsh` (on my system) is `/bin/python -u /bin/xonsh`. When doing this as a login shell, no `-` is prepended. (Aside: The parsing of spaces in varies hashbangs somewhat. In my tests, running scripts from xonsh would cause spaces to be parsed. In all other contexts, the hashbang would only be split on the first script. Filed as #1512.)

So in order to get the leading `-`, xonsh needs a C wrapper. (The project may want to consider this anyway, given #1471 and #1472.)

**Comment by scopatz** [comment]
Can you launch with `xon.sh`, rather than `xonsh`?  `xon.sh` is supposed to be the fully sh-lang compatible launcher for these kinds of situations.

**Comment by PaulReiber** [comment]
>* xon.sh is supposed to be the fully sh-lang compatible launcher*
I think maybe we should call this out better in the documentation


Kind regards,


*Paul Reiber*http://about.me/reiber

**Comment by scopatz** [comment]
Yeah, for sure.

**Comment by scopatz** [comment]
Is this still an issue?  Or can we switch this to a docs issue at this point to address @PaulReiber's point?

**Comment by scopatz** [comment]
Switching this to a docs issue.

**Comment by gforsyth** [comment]
Closing this in favor of manual meta-issue #2315
