### ISSUE TITLE
Full text of how to download missing program gets cut off

### ISSUE THREAD

**Issue by kirbyfan64** [xonsh/xonsh#1180]
By default on Ubuntu distros (I'm using Elementary OS), when you enter a missing program, the system will hint on how to download it:

```
ryan@DevPC-LX:~$ realpath
The program 'realpath' is currently not installed. You can install it by typing:
sudo apt-get install realpath
ryan@DevPC-LX:~$ 
```

However, this doesn't seem to work fully in Xonsh:

```
ryan@DevPC-LX ~ $ realpath
xonsh: subprocess mode: command not found: realpath
The program 'realpath' is currently not installed. You can install it by typing:
ryan@DevPC-LX ~ $ 
```

**Comment by scopatz** [comment]
Thanks for reporting @kirbyfan64!

**Comment by PaulReiber** [comment]
The command-not-found package is what implements command-not-found processing for bash and zsh for ubuntu.  More info on it here: https://wiki.ubuntu.com/CommandNotFoundMagic

Code tarball, if you're interested: https://launchpad.net/command-not-found/+download

Snippet:
`import sys, os, os.path, gdbm, posix, grp, string, subprocess
from util import gettext_wrapper as _
[...]
                    print >>sys.stderr, _("The program '%s' is currently not installed. ") % command,
                    print >>sys.stderr, _("You can install it by typing:")
                    print >>sys.stderr, cmd
`
The only difference I note is the final line is not getting sent thru gettext_wrapper.

Anthony, I wrote up a test that wrote 3 lines to stderr using print >>sys.stderr, "quoted strings 1 thru 3" and, as I expected, xonsh outputs all 3 lines just fine.

Any ideas?

**Comment by scopatz** [comment]
I am not sure I understand the fix here. Can you please put in a PR?

**Comment by PaulReiber** [comment]
I don't have a fix at this point - I was just sharing the investigation and observations I've done so far.  

This particular bug's an odd one, as such very compelling for me, to better understand things ( how could that possibly happen? why?)

What I've learned is, the difference is that the final line with the command isn't sent through the internationalization function _  but that other than that the recommended commandline is just printed to stderr, as were the lines above it.  The stream gets flushed when the program exits and its stderr stream closes, so that line should come thru... so where did it go?

Are there any other cases of oddness with processing of stderr of a subcommand?

**Comment by scopatz** [comment]
> Are there any other cases of oddness with processing of stderr of a subcommand?

Not that I know of, but I think this might be handled in a special way.  The problem is probably that we are not running the command directly, but through shell mode in a script we construct programatically. See https://github.com/xonsh/xonsh/blob/master/xonsh/tools.py#L539

We should probably just run the command directly and ignore any failures.  That `exit 0` part isn't needed.

**Comment by adqm** [comment]
Isn't [this](https://github.com/xonsh/xonsh/blob/master/xonsh/tools.py#L542) the problem?  The last line is being removed explicitly.

Maybe older versions used to leave an empty blank line, or something?  If so, we could `rstrip` before doing the `splitlines`, and then just keep all the lines.

**Comment by scopatz** [comment]
Ahh yeah! That is probably it!

**Comment by kirbyfan64** [comment]
Man, those one-liner bugs can be the worst to figure out...

**Comment by scopatz** [comment]
A PR with a fix would be most welcome!

**Comment by PaulReiber** [comment]
Adam wrote:

> Isn't this
<https://github.com/xonsh/xonsh/blob/master/xonsh/tools.py#L542> the
problem? The last line is being removed explicitly.
Nice find!

Kind regards,


*Paul Reiber*http://about.me/reiber

**Comment by SanketDG** [comment]
Hi,

I tried to fix this by changing line [543](https://github.com/xonsh/xonsh/blob/master/xonsh/tools.py#L543) to:

```python
    s = '\n'.join(s.rstrip().splitlines()).strip()
```

But that doesn't change anything on the output. Note that I did `pip install -e .`, so I should see realtime changes, is there anything else I have to do?

**Comment by laerus** [comment]
hey @SanketDG, you should restart xonsh after changing the source to see the live changes. The only other thing that comes in mind right now is that if you had previously installed xonsh not in develop mode (`-e` option) you must reinstall or remove the install and install in develop mode.

**Comment by SanketDG** [comment]
Cool thanks. I have opened a PR. :point_up:
