### ISSUE TITLE
Custom color themes?

### ISSUE THREAD

**Issue by ns-phennessy** [xonsh/xonsh#1207]
I know we can apply an existing color theme by doing something like: `$XONSH_COLOR_STYLE = 'monokai'`

Is there any support for defining my own color theme? 

Thanks!

**Comment by scopatz** [comment]
Thanks for bringing this up @ns-phennessy! Currently there is no way to do this, but there should be.  If anyone wants to work on this, please let us know!

**Comment by ns-phennessy** [comment]
@scopatz I'd be more than happy to dig into it a bit. 

Could we do something like have a dict called themes and you can just append to it where (xonshrc / config). Not sure what you thoughts would be on that.

**Comment by scopatz** [comment]
> @scopatz I'd be more than happy to dig into it a bit.

Great! 

> Could we do something like have a dict called themes and you can just append to it where (xonshrc / config). Not sure what you thoughts would be on that.

I think it will be a little more involved than that.  There are such mappings already (called STYLES). However, these differ in meaning (if not in structure) based on what backend is being used.  Readline uses ANSI escape sequences ([see here](https://github.com/xonsh/xonsh/blob/master/xonsh/ansi_colors.py)) and prompt-toolkit uses pygments ([see here](https://github.com/xonsh/xonsh/blob/master/xonsh/pyghooks.py)).  Having a single interface would be able to translate the custom theme into the form used by either / both backends.  

Additionally, the pygments backend should optionally be able to take pygment token colorizations for syntax highlighting. 

Does this make sense? I don't think that this would be too hard because the building blocks are there, but it doesn't exist yet.  Maybe a `xonsh.tools.register_color_style(cmap, pyg=None)` would be a good entry point.

**Comment by hawkeyej** [comment]
I would really love to use xonsh more, but the bold blue on black is basically unreadable.

**Comment by laerus** [comment]
you're right @hawkeyej. Try setting `XONSH_COLOR_STYLE='native'` and see if that helps

**Comment by hawkeyej** [comment]
@laerus Thanks, that is much better...

**Comment by gforsyth** [comment]
Now that pygments is updated, setting `$XONSH_COLOR_STYLE='default'` will use the terminal's color scheme

**Comment by t184256** [comment]
I don't quite think that solves the issue. E.g., what if I want to make strings bold red without switching whatever terminal color they happen to be now red for the whole terminal? Custom theme is custom styling for everything without touching the terminal settings.

**Comment by scopatz** [comment]
Yeah I agree with @t184256 - we still do need the ability to allow custom color themes.
