### ISSUE TITLE
incosistent error messages with subprocess syntax

### ISSUE THREAD

**Issue by laerus** [xonsh/xonsh#1247]
```
>  $(echo 'ok') tttt
xonsh: subprocess mode: command not found: ok
```

```
> !(echo 'ok') tttt
SyntaxError: <xonsh-code>
```

```
> $[echo 'ok'] tttt   # ????
AttributeError: 'NoneType' object has no attribute 'splitlines'
```

```
> ![echo 'ok'] asdasd
SyntaxError: <xonsh-code>
```

**Comment by adqm** [comment]
HI @laerus, thanks for bringing this up!  I think some of these differences are intentional, and at least one is not.

The first second and last examples (`!()` and `![]`) are indeed syntax errors, and they should be treated as such.  I think the third example (`$[]`) should probably also be treated this way.

The first, though, (`$()`) takes its result (string representing stdout) and injects it into the subprocess args.  That said, given our recent shift in perspective about `$()`, perhaps it would make sense for that to be a syntax error as well (and to force the use of `@()` for injecting anything Pythonic into the subprocess args)...

**Comment by scopatz** [comment]
I agree that perhaps the third `$[]` should be a syntax error, though I think that this could be tricky to implement, since exprs like `$[echo 'ok'] is None` should be valid.

That said, I believe that `$(echo 'ok') tttt` is totally legitimate and the error message is correct.  You may have a command that spits out the name of another command that you then wish to run. As a trivial example, consider `$(echo -n ls) myfile` to ls a file.  You shouldn't need to go into pymode to get a file name. Also, I think it is relatively easy to imagine a situation where going into python mode would be excessive since you need to run an external command to get the command name you want.

If we extend this to @$(), a natural use case is to by pass aliases with `@$(which -s cmd) args`

That is my two cents, at least!
