### ISSUE TITLE
Autoenv and xonsh

### ISSUE THREAD

**Issue by Granitas** [xonsh/xonsh#1256]
How could I get https://github.com/kennethreitz/autoenv working with xonsh. 

When I try to activate the autoenv script, I get
```
> source /usr/bin/activate.sh
File "<string>", line None
SyntaxError: <xonsh-code>:2:19: ('code: /',)
AUTOENV_AUTH_FILE=~/.autoenv_authorized
```
When using `source-bash` or `source-zsh` it sources it without errors however when using `cd directory` it doesn't do anything and stays in the directory.

How could I make this work?

**Comment by gforsyth** [comment]
Hey @Granitas - yeah, `autoenv` won't work in xonsh right now.  But I think nearly all of its functionality can be replicated with a post_cd hook, as described by @scopatz [here](https://github.com/xonsh/xonsh/issues/1243#issuecomment-226675493), if you want to try to take that on.  Otherwise we'll get to it soon enough, I imagine:

**Comment by Granitas** [comment]
I've made a clone of autoenv that works with Xonsh as a Xontrib using the post_cd hook described above:
https://github.com/Granitas/xonsh-autoxsh
It should end up in the Xonsh docs under xontribs soon enough :)

**Comment by astronouth7303** [comment]
I think this can be closed.
