### ISSUE TITLE
default value for $PATH seems strange in wizard

### ISSUE THREAD

**Issue by Qumeric** [xonsh/xonsh#1392]
It's  `<xonsh.__amalgam__.LazyObject object at 0x7f6705929eb8>`. Current value is okay though.

I run fresh xonsh 0.4.3 on Ubuntu 16.04.

**Comment by laerus** [comment]
Hello, thank you for reporting this! this happens because we need to call the `__getattribute__` method on a LazyObject somehow in order to replace itself with the actual object. Simply putting something like `PATH_DEFAULT[0]' in `environ.py` before `DEFAULT_VALUES` dictionary is being set, fixes this problem, but there must be a more elegant way to this.

**Comment by scopatz** [comment]
I think this is a matter of calling str or repr s directly
