### ISSUE TITLE
exceptions antipatern

### ISSUE THREAD

**Issue by PaulReiber** [xonsh/xonsh#1396]
I was doing some reading: https://realpython.com/blog/python/the-most-diabolical-python-antipattern/

Maxwell, the author, makes a very good case for not doing this.  I searched the xonsh source to see how it fared.

``` python
pbr@mongo:~/xonsh/xonsh$ pcregrep -M 'except Exception:.*\n.*pass.*\n' *.py
__amalgam__.py:        except Exception:
            pass
__amalgam__.py:    except Exception:  # pylint:disable=broad-except
        pass
__amalgam__.py:            except Exception:  # pylint:disable=broad-except
                pass
__amalgam__.py:        except Exception:
            pass
built_ins.py:        except Exception:
            pass
inspectors.py:    except Exception:  # pylint:disable=broad-except
        pass
inspectors.py:            except Exception:  # pylint:disable=broad-except
                pass
timings.py:        except Exception:
            pass
```

There are also 2 spots in pretty.py with intervening comment lines:

``` python
pretty.py:            except Exception:
pretty.py-                # Sometimes the keys don't sort.
pretty.py-                pass
```

I haven't undertaken to assess the impact of each specific case where we simply 'pass'.  

Could the author(s) of the original code in each case assess whether any changes are needed in light of reading Maxwell's article?  If no changes are needed, that's great to learn, too.

**Comment by melund** [comment]
@PaulReiber Thanks for bringing this up. I will not rule out that some of these should be fixed. You are welcome to investigate them further.

Firstly, I am not sure that what Maxwell writes is totally correct. For example `except:` and `except Exception` are not really equal. They  latter will not catch `StopIteration`, `GeneratorExit`, `KeyboardInterrupt` and `SystemExit`. `StandardError`, which is probably why 

Secondly, in many of these cases we can't do better than catching the broad `Exception`. For example if xonsh should not crash due to some user errors. You can also see that some of the lines has a `# pylint:disable=broad-except` to diable pylint warnings for the broad except.

**Comment by scopatz** [comment]
Closing due to age.  Would be happed to have issue/PR with more specific cases
