### ISSUE TITLE
Command not parsed correctly

### ISSUE THREAD

**Issue by wreed4** [xonsh/xonsh#1402]
Using version 0.4.3

A command of the format `nvim +"some command with spaces"` should execute the command in quotes upon startup of neovim (this is the same with vim).  It does not however.  In order to get the proper behavior, I have to do this: `@(shlex.split('nvim +"some command with spaces"'))`.  

Additionally, you can't escape spaces like `nvim +some\ command\ with\ spaces`.  I'm not sure if this is by design, but it is a useful feature.

**Comment by mitnk** [comment]
This may be a big topic to discuss as partly mentioned in #1397 :)

**Comment by laerus** [comment]
Hey @wreed4 can you write an example of what "some commands with spaces" is. You can also try putting the + inside the quotes:
`vim "+set noignorecase" "+set si"`

**Comment by scopatz** [comment]
Hello @wreed4, as @laerus pointed out implicitly.  This is because quotes that capture spaces in xonsh only apply to the outer most level, like it Python.  Quotes in Bash are always just removed from wherever they are. Xonsh takes the approach that Python always wins.  

This issue is being triggered because you don't provide outer quotes since the second argument starts with a `+` sign.

For example, `nvim +"some command with spaces"`  will be parsed as the following list of argument strings in Bash and other sh languages:

```python
["nvim", "+some command with spaces"]
```

Note that there are no quotes inside of the string because *Bash* removes them no matter where they are in the string.  However, in xonsh, this is parsed as four separate argument because no token both starts and ends with matching quote characters

```python
["nvim",  '+"some', "command", "with", 'spaces"']
```

So in xonsh, if you want to pass in this whole phrase a single argument, you write it as it is intended to be seen by the program, namely move the `+` inside of the quote:

```
nvim "+some command with spaces"
```

will be parsed as 

```python
["nvim", "+some command with spaces"]
```

sh-based languages do some crazy things with strings and arguments and xonsh attempts to make this more consistent and intuitive by relying on Python string semantics instead.  However, this is a relatively major distinction between sh-languages and xonsh.

Sorry if this was a gotcha for you.  More documentation to this effect would be very welcome!

**Comment by wreed4** [comment]
OH! yeah, that makes a lot of sense actually. It is hard coming from a sh-based language and typing as if you're still using it but remembering it's actually parsed entirely differently.  Thanks for the in-depth explanation.  

To anyone reading this in the future, I've confirmed that `nvim "+some command with spaces"` works as expected in xonsh v0.4.3.

**Comment by scopatz** [comment]
Glad it helped @wreed4  :).  I do think that this is something that needs a better explanation in the tutorial if someone wants to put that in ;)

**Comment by scopatz** [comment]
Closing based on #2560
