### ISSUE TITLE
Don't save [SPACE] command is history

### ISSUE THREAD

**Issue by Qumeric** [xonsh/xonsh#1404]
In bash shell you can suppress saving of a command to history by writing a single space before it. Seems like it doesn't work in xonsh.

If there is some other way to do it than probably documentation about history should be updated because I couldn't find it there.

**Comment by scopatz** [comment]
Hi @Qumeric, thanks for bringing this up, and I am sorry for taking so long to respond.

I don't think that we will support this particular syntax because it is sort of incongrouous with the rest of the parser and language.  

However, I would be in support of some command or syntax that implements this.  Suggestions and pull requests welcome!

**Comment by mitnk** [comment]
Just tried in bash, seems [space] prefixed commands will still be saved into ~/.bash_history file.

**Comment by mitnk** [comment]
I tried in bash 3.2. new version of bash may have that feature?

**Comment by Qumeric** [comment]
@mitnk GNU bash 4.3.46(1)-release at Ubuntu 16.04 does have it and it's enabled by default.

**Comment by scopatz** [comment]
This could be implemented in a xontrib with a pre command event handler.
