### ISSUE TITLE
Add argcomplete support?

### ISSUE THREAD

**Issue by melund** [xonsh/xonsh#1409]
Does anyone have experience with the argcomplete package by @kislyuk?  https://github.com/kislyuk/argcomplete

It adds argparse completion to bash for packages that support it. It seems that conda does for example.   It seems to be good candidate to add to the set of completers in xonsh. It is targeted bash but since it it is a Python package it must be possible to use it directly.

**Comment by scopatz** [comment]
Hi @melund! I think this would potentially be a great option to easily get completions.  

I have used this in the past, but my experience was that it was ridiculously slow.  Now that I think about it, it might be because of the pkg_resources/setuptools issue. We have mitigated this, and perhaps there is a clean API that we can hook into.  Definitely worth investigating.

**Comment by anki-code** [comment]
Hello guys! Any news here? Probably you can advice alternatives for `argcomplete`?

**Comment by anki-code** [comment]
@melund may be you found workaround for argcomplete in xonsh since 2016 year?

**Comment by melund** [comment]
No. I haven't looked at this since. I think pull request are really welcome here.

**Comment by anki-code** [comment]
@melund I've made [xontrib-argcomplete](https://github.com/anki-code/xontrib-argcomplete) as first try to solve this. Welcom to make a try:)
