### ISSUE TITLE
Idea: Event System?

### ISSUE THREAD

**Issue by astronouth7303** [xonsh/xonsh#1489]
Would it be a good idea to have some form of hooking or event system?

* xontribs like avox and autoxsh do not have to shadow `cd` in order to work
* Ability to run code before or after prompt execution

So far, I've identified three events: changing directory, pre-command, and post-command.

**Comment by PaulReiber** [comment]
Similar discussion was initiated by adqm on another issue, part-way through this comment:
https://github.com/xonsh/xonsh/issues/1204#issuecomment-228582495

The thread starts more or less at "**A different approach would be to add several hooks throughout xonsh**" 

I think the idea has merit.  An event system could be used to deliver some pretty useful and powerful end-user centric customizations.  

There are a handful of other relevant events beyond the ones listed so far that xonsh could make available for anyone interested.  Terminal resizes, stuff triggered by changes to the controlling terminal, for example. And a startup-time hook for "before everything else gets to load", another for "after everything else gets to load".  Since it just occurred to me, I'll add one more - pre_exit.

We'll want to consider both the interactive use cases and "xonsh shell scripts" as well.  There may be additional events or at least ones that get differentiated by whether the shell's interactive or not.

**Comment by scopatz** [comment]
Yeah, I think that there are enough use cases for this that it should be implemented and the code base should be reworked around this. @adqm has many great ideas :)

**Comment by scopatz** [comment]
Thanks for opening this @astronouth7303
