### ISSUE TITLE
wrong caret position when using two space unicode chars in $PROMPT

### ISSUE THREAD

**Issue by santagada** [xonsh/xonsh#1569]
My $PROMPT uses a unicode two space char and recently xonsh started wrongly counting the spaces in the prompt when I have them:

![screenshot 2016-08-16 13 34 47](https://cloud.githubusercontent.com/assets/225897/17697657/440944d0-63b6-11e6-8173-7e954087f26c.png)

this doesn't happen in zsh, so I'm guessing is a weird interation of prompt-toolkit/wcwidth

prompt toolkit 1.0.6
wcwidth 0.1.7

**Comment by astronouth7303** [comment]
Yup. Same thing happens with SPIRAL SHELL. Confirmed for iTerm2 and VTE.

Basically, wcwidth correctly identifies emoji as being 2 cells wide, but many (most? all?) terminal emulators do not.

I think it's because prompt-toolkit does lots of positioning when you're editing the line, but when it accepts input, it redraws the whole area and lets the terminal calulate width.

**Comment by santagada** [comment]
ok so the response from wcwidth is that they are not going to support it, as this is changed on wcwidth 0.1.7 I propose we set a hard dependency for wcwidth < 0.1.7 until this is fixed what do you guys think?

**Comment by astronouth7303** [comment]
For reference, this is a problem with Unicode in general, and different terminals will bug in different ways. https://eev.ee/blog/2015/09/12/dark-corners-of-unicode/#combining-characters-and-character-width has some background on this.

**Comment by scopatz** [comment]
Well, I think the dependency thing would be more for prompt-toolkit to decide.  We don't directly depend on wcwidth, just PTK.  We could put something in the docs, though about downgrading wcwidth until this is fixed upstream.
