### ISSUE TITLE
$PWD, and therefore, prompt string doesn't track change in real working directory.

### ISSUE THREAD

**Issue by bobhy** [xonsh/xonsh#1606]
If XONSH invokes a Python function which changes working directory, e.g, by ``os.chdir()``, $PWD and prompt string don't reflect it, leading to confusion all round.  Here's an example:

```xonsh
> xonsh
-------------------------- bobhy@BobHy-PC ~
$ $PWD
'C:\\Users\\bobhy'
-------------------------- bobhy@BobHy-PC ~
$ cmd /c 'cd'
C:\Users\bobhy
-------------------------- bobhy@BobHy-PC ~
$ import os
-------------------------- bobhy@BobHy-PC ~
$ os.getcwd()
'C:\\Users\\bobhy'
-------------------------- bobhy@BobHy-PC ~
$ os.chdir('Documents')  # <-- triggers the bug
-------------------------- bobhy@BobHy-PC ~          # <-- prompt string unaffected
$ $PWD
'C:\\Users\\bobhy'                                                     # <-- as is PWD
-------------------------- bobhy@BobHy-PC ~
$ os.getcwd()
'C:\\Users\\bobhy\\Documents'                                # <-- but working directory did change
-------------------------- bobhy@BobHy-PC ~
$ cmd /c 'cd'
C:\Users\bobhy\Documents
-------------------------- bobhy@BobHy-PC ~

**Comment by scopatz** [comment]
Thanks for reporting @bobhy. This is a subtle issue and I am not sure what can be done about it that doesn't involve excessive querying or monkey patching parts of the standard library.

Also, note that this is a problem *within* the standard library itself. For example, say I have a function which changes the directory from the C-level, `os.environ` and `os.getenv()`  will only see the original, old directory:

```python
>>> os.environ['PWD']
/a
>>> change_dir_from_c('/b')
>>> get_dir_from_c()
/b
>>> os.environ['PWD']
/a
>>> os.getenv['PWD']
/a
```

The safest thing to do from xonsh is to always use `__xonsh_env__` and `cd`.  Unfortunately, even setting `os.environ` to the xonsh env doesn't seem to work:

```console
scopatz@artemis ~ $ os.environ = __xonsh_env__
scopatz@artemis ~ $ os.chdir('/')
scopatz@artemis ~ $ $PWD
'/home/scopatz'
scopatz@artemis ~ $ os.environ['PWD']
'/home/scopatz'
scopatz@artemis ~ $ os.getcwd()
'/'
```

This is likely because `os.chdir()` and `os.getcwd()` have their own references to the original `os.environ` object, which we cannot override. 

Maybe we could do something simple that would work in most cases, like updating from `os.getcwd()` in the prompt.  However, that wouldn't be full proof enough to work in scripts.  That might be a nice small xontrib that xonsh could provide, if anyone is interested.

**Comment by bobhy** [comment]
Here comes a PR 18 with one way to fix it... (btw, what's the markdown markup to refer to the pull request?)

**Comment by gforsyth** [comment]
Hey @bobhy, you can refer to both issues and PRs with a pound sign and the corresponding number and github will take care of the rest. E.g. #18

**Comment by astronouth7303** [comment]
Just did some reading and source diving. `os.chdir()` largely defers to the underlying c calls. None of the reference pages for those C functions (Windows or POSIX) make any mention of `$PWD`. Bash has code to set and handle `$PWD`.

**Comment by gforsyth** [comment]
I believe this was handled in #1608

**Comment by nimatrueway** [comment]
I'm having this issue with `xonsh/0.13.0` on macOS+iTerm2 with zero-config.

![image](https://user-images.githubusercontent.com/2261274/178539269-01ce1abb-7049-4980-94cb-92f9d460c62a.png)

**Comment by gforsyth** [comment]
@nimatrueway -- if you set `$UPDATE_OS_ENVIRON=True` it should take care of that

**Comment by nimatrueway** [comment]
Oh nice, thanks @gforsyth.

```
nima.taheri@Nima-Taheri ~ $ pwd
/Users/nima.taheri
nima.taheri@Nima-Taheri ~ $ echo $PWD
/Users/nima.taheri
nima.taheri@Nima-Taheri ~ $ import os
nima.taheri@Nima-Taheri ~ $ os.getcwd()
'/Users/nima.taheri'
nima.taheri@Nima-Taheri ~ $ os.getenv("PWD")
'/Users/nima.taheri'


nima.taheri@Nima-Taheri ~ $ cd Projects


nima.taheri@Nima-Taheri ~ $ pwd
/Users/nima.taheri/Projects
nima.taheri@Nima-Taheri ~ $ echo $PWD
/Users/nima.taheri/Projects
nima.taheri@Nima-Taheri ~ $ os.getcwd()
'/Users/nima.taheri/Projects'
nima.taheri@Nima-Taheri ~ $ os.getenv("PWD")
'/Users/nima.taheri/Projects'
nima.taheri@Nima-Taheri ~ $ echo $PROMPT
{env_name}{BOLD_GREEN}{user}@{hostname}{BOLD_BLUE} {cwd}{branch_color}{curr_branch: {}}{RESET} {RED}{last_return_code_if_nonzero:[{BOLD_INTENSE_RED}{}{RED}] }{RESET}{BOLD_BLUE}{prompt_end}{RESET}
```

Do you happen to know why `{cwd}` in prompt is still pointing to the old directory?
