### ISSUE TITLE
Unable to scroll after mouse enabled process crashes

### ISSUE THREAD

**Issue by blahgeek** [xonsh/xonsh#1609]
1. Open a mouse enabled process (e.g., vim)
2. `killall -9 vim`
3. Try to scroll

**Comment by gforsyth** [comment]
I can confirm this on both prompt_toolkit and readline, although on prompt_toolkit my scroll wheel actually starts navigating through history instead.  Weird.

```console
> xonfig
+------------------+-----------------+
| xonsh            | 0.4.5.dev50     |
| Git SHA          | 7373893         |
| Python           | 3.5.2           |
| PLY              | 3.8             |
| have readline    | True            |
| prompt toolkit   | 1.0.7           |
| shell type       | prompt_toolkit  |
| pygments         | 2.1.3           |
| on posix         | True            |
| on linux         | True            |
| distro           | arch            |
| on darwin        | False           |
| on windows       | False           |
| on cygwin        | False           |
| is superuser     | False           |
| default encoding | utf-8           |
| xonsh encoding   | utf-8           |
| encoding errors  | surrogateescape |
+------------------+-----------------+
```

**Comment by PaulReiber** [comment]
I tested with a remote ssh session and I do _not_ see the mouse-scroll
problem in that case - mouse scroll kept working fine.

I did see another behavior, which I expected based on a PR a while ago with
some code that was trying to fix stdin's modes. While it looked like it
should work, it didn't, and we chalked it up to readline interfering with
things.

...IIRC the bug was reported as "invisible characters" or similar.
Basically, stdin wasn't in 'echo' mode.

This is yet another case showing that xonsh needs to 'stty sane' as it's
printing out the prompt.

---snip from my ssh session---

Killed
~     pbr@mongo ~ $ speed 38400 baud; rows 38; columns 121; line = 0;
~
intr = ^C; quit = ^\; erase = ^?; kill = ^U; eof = ^D; eol = <undef>;
eol2 = <undef>; swtch = <undef>; start = ^Q;
~                                                             stop =
^S; susp = ^Z; rprnt = ^R; werase = ^W; lnext = ^V; discard = ^O; min
= 1; time = 0;
~                               -parenb -parodd -cmspar cs8 -hupcl
-cstopb cread -clocal -crtscts
~
                          -ignbrk brkint -ignpar -parmrk -inpck
-istrip -inlcr -igncr -icrnl ixon -ixoff -iuclc -ixany imaxbel -iutf8
~
            opost -olcuc -ocrnl -onlcr -onocr -onlret -ofill -ofdel
nl0 cr0 tab0 bs0 vt0 ff0
~                                         -isig -icanon -iexten -echo
-echoe echok -echonl -noflsh -xcase -tostop -echoprt echoctl echoke
-flusho -extproc
~                                pbr@mongo ~ $      version 7.4.1689
~                                               by Bram Moolenaar et
al.
~                                Modified by
pkg-vim-maintainers@lists.alioth.debian.org
~                                      Vim is open source and freely
distributable
~
~                                               Sponsor Vim
development!
~                                    type  :help sponsor<Enter>    for
information
~
~                                    type  :q<Enter>               to
exit
~                                    type  :help<Enter>  or  <F1>  for
on-line help
~                                    type  :help version7<Enter>   for
version info
~


---snip---

At the xonsh prompt below 'killed' I typed in 'stty -a' and the program
ran, outputting  on top of what had been a vim startup screen.

A subsequent 'stty sane' got everything working perfectly again, as I
expected it would.

Gil, can you please try that as well (run 'stty sane') to see if it repairs
things for your case too?

Happy to put further shoulder to that PR if needed, if someone on the team
can talk to me about the shell's file descriptors and how they're being
managed.  I need to get to, and modify the mode on, the _real_ stdin.

Kind regards,


*Paul Reiber*http://about.me/reiber

**Comment by gforsyth** [comment]
Hey @PaulReiber , I will definitely take a look at that.  Could you open up a separate issue for that so we can track them independently?  Thanks!

**Comment by gforsyth** [comment]
Sorry -- brain detached from fingers.  Disregard previous comment.   I'll take a look and see what happens.

**Comment by gforsyth** [comment]
Hmm, interesting...

So `stty sane` doesn't make a difference with the prompt_toolkit backend -- everything still works as expected except for mouse scrolling which instead scrolls through command history.

The readline case is a little different.  The `killall -9 vim` renders the prompt unusable, with input hidden and output offset in wacky ways, but `stty sane` returns the prompt to a usable state.  And then, in the readline shell, the same weird mouse scrolling through command history behavior.

**Comment by PaulReiber** [comment]
I have not tried testing with prompt_toolkit.  How can I switch back and
forth between it and readline?

Our results will differ sometimes since I'm doing a 'remote ssh' usecase
almost all of the time when testing xonsh. (I test it on a machine I always
have remote access to, but occasionally have console access to)

Kind regards,


*Paul Reiber*http://about.me/reiber

**Comment by gforsyth** [comment]
If you have `prompt_toolkit` installed (also requires `pygments`) you can run 

```console
xonsh --shell-type prompt_toolkit
```

**Comment by PaulReiber** [comment]
pbr@mongo:~$ xonsh --shell-type prompt_toolkit
/usr/local/lib/python3.5/dist-packages/xonsh/__amalgam__.py:16320:
UserWarning: prompt_toolkit is not available, using readline instead.
  warnings.warn('prompt_toolkit is not available, using '
pbr@mongo ~ $

I'll work on this later today / this evening and follow up with test results

Thank you!


Kind regards,


*Paul Reiber*http://about.me/reiber

**Comment by astronouth7303** [comment]
What terminal emulators are you all using? I assume by "try to scroll" you mean "I use my mouse wheel to try to look at the scrollback of my GUI terminal emulator".

Is this a cross-emulator bug or specific to just one?

**Comment by gforsyth** [comment]
Hey @astronouth7303 -- good question!  
I can reproduce this in `roxterm` -- and in that case, I can't scroll either with mouse wheel, or PgUp, PgDn.  In fact, the scroll bar, while present, does not respond to anything.

In `urxvt` the `killall` command leaves the terminal in an unusable state until I pass a `stty sane`, but scrolling does continue to work regardless.

All of this is under prompt_toolkit

**Comment by PaulReiber** [comment]
For reference, most of my xonsh testing to date has been via ssh sessions
using the chrome extension "nassh" as the client.  On a chromebook.

https://chromium.googlesource.com/apps/libapps/+show/master/nassh

Kind regards,


*Paul Reiber*http://about.me/reiber

**Comment by scopatz** [comment]
Is anyone still seeing this issue? It seems to work for me

**Comment by scopatz** [comment]
Please feel free to reopen if needed!
