### ISSUE TITLE
Branch names no longer seem to show up until git is run

### ISSUE THREAD

**Issue by scopatz** [xonsh/xonsh#1948]
```console
scopatz@andromache ~ $ cd staged-recipes/
staged-recipes/recipes/  staged-recipes/scripts/  
scopatz@andromache ~ $ cd staged-recipes/recipes/
scopatz@andromache ~/staged-recipes/recipes $ 
scopatz@andromache ~/staged-recipes/recipes $ git branch
  master
  re2
* regolith
scopatz@andromache ~/staged-recipes/recipes regolith $
```

**Comment by Siecje** [comment]
This is caused by 

[cmds.lazy_locate_binary('git')](https://github.com/xonsh/xonsh/blob/a413061d772d9ecf6c5419e366e867d9d640aaa1/xonsh/prompt/vc_branch.py#L128) introduce by https://github.com/xonsh/xonsh/commit/0f10c774cd8a1cde5b1746343d3e87749057b7fa

I have removed the checks for ```__xonsh_commands_cache__``` in https://github.com/xonsh/xonsh/pull/1943

**Comment by laerus** [comment]
lazy locate was there before but it also run when the cache was empty meaning that it tried to search for hg in every directory even if hg was not installed. i'm working on a fix atm.

**Comment by scopatz** [comment]
Thanks for working on this!

**Comment by laerus** [comment]
the problem whith running the git/hg binaries when building the prompt is that we get all the overhead on xonsh startup and on each prompt update. This also means that if for some reason we cant get the commands cache file we have to also populate the cache in order to locate the binaries. 

note that `xonsh.prompt.gitstatus` does all that `xonsh.prompt.vc_branch` does for git and even more by calling git a couple of times.

**Comment by scopatz** [comment]
It seems to be working now, thanks @laerus @Siecje!
