### ISSUE TITLE
Does xonsh not support environment variables on the same line as the to be executed command?

### ISSUE THREAD

**Issue by jmmills** [xonsh/xonsh#1995]
This is sort of a standard thing in bash (and other unix shells iirc), what's the xonsh equivalent? 

```
/tmp $ echo $XONSH_VERSION
0.4.7
/private/tmp $ cat env_echo.sh
#!/bin/bash

echo $ONE
echo $TWO
/private/tmp $ ONE=a TWO=b ./env_echo.sh
xonsh: subprocess mode: command not found: ONE=a
/private/tmp $ bash
bash-4.4$ ONE=a TWO=b ./env_echo.sh
a
b
bash-4.4$
```

**Comment by astronouth7303** [comment]
No, it does not. Xonsh is not bash.

The closest equivalent is [swap()](http://xon.sh/tutorial.html#the-environment-itself).

**Comment by gforsyth** [comment]
Try prefixing the line with `env`, that should do the trick

**Comment by scopatz** [comment]
Yeah, I think the closest is `env`. I thought this was in the bash translation guide docs, but it isn't. 

I don't know how the other core devs feel, but this isn't something that I would be opposed to having in some form. I am just not super compelled to work on it myself since `env` does the job well and it pretty explicit about it.  Maybe if users start clamouring one way or the other we'll have to make a decision.
