### ISSUE TITLE
`gvim` command-line tool "blocking" with 0.5.1 on macOS

### ISSUE THREAD

**Issue by jonathanhogg** [xonsh/xonsh#2060]
When I use the `gvim` command-line tool to open a text file in MacVim for editing, the shell is remaining blocked, as if the tool was running in the foreground, until the window that has just been opened is closed. This is the behaviour I would expect using the `-f` flag, but it is occurring always. I'm not getting the same behaviour in other shells, so it's not something new introduced with a new version of MacVim. It kind of looks like xonsh is waiting for the forked background process.

I'm not certain which xonsh release this has started happening in as I've not been carefully tracking my upgrades, but I'm pretty sure that it wasn't the case in 0.4.

(homebrew-installed MacVim)

**Comment by gforsyth** [comment]
Hey @jonathanhogg -- thanks for reporting! This was almost certainly introduced by the new subprocess execution model in v0.5

We're working on better ways to predict which programs should or shouldn't block (beyond what we're doing now, which is writing them all down in a dictionary).

Can you try putting this in your `.xonshrc` and see if it fixes the issue for you? 

```console
from xonsh.proc import unthreadable, uncapturable

@uncapturable
@unthreadable
def _mygvim():
    gvim

aliases['vim'] = _mygvim
```

and then just call it using `vim` or whatever alias you choose (but not the same name or it will recurse)

**Comment by scopatz** [comment]
Hi @jonathanhogg, what precisely is the command that you are running?  Also could you try in your xonshrc

```python
from xonsh.commands_cache import predict_false

__xonsh_commands_cache__.threadable_predictors['gvim'] = predict_false
```

**Comment by scopatz** [comment]
ok we should maybe just wait for the commands cache fix then.

**Comment by scopatz** [comment]
Hi @jonathanhogg, is this fixed for you? Please feel free to close

**Comment by jonathanhogg** [comment]
Hi @scopatz,

The `__xonsh_commands_cache__` workaround makes the problem go away, but I don't know if you want to call that "fixed" 😉

Do you want me to wait for this "commands cache fix" (not sure what that is) and re-test or just close now?

**Comment by laerus** [comment]
Hey @jonathanhogg! well this is actually the solution we used so far for commands that use alternate mode aka nonthreadables. if you are on master or after #2062 try again without using the commands_cache 'hack', haven't test this myself but i feel that we finally solved this.

**Comment by jonathanhogg** [comment]
Hey @laerus, pulled my `xonsh` fork forwards to 6eeac872 and installed, but the problem remains.

Is there anything useful I can do to help debug? From brief playing around with `subprocess.Popen()`, it looks to me like the process is exiting immediately (a `.poll()` returns 0), but that it's stdout remains open until the window is closed (a `.stdout.read()` blocks until I close the MacVim edit window and then returns a zero-length bytes object). I assume that the stdout is being inherited by the forked background process and that is holding it open until it subsequently exits.

Why do you guys capture the output of the subprocess rather than just hook it to the shell stdout? Is this to integrate xonsh into other systems? I guess it is genrally impossible to know in advance that a process will do this, and thus avoid capturing it, so presumably one would need to return to the prompt immediately on process exit, but continue capturing output in the background, feeding it to the shell output.

**Comment by scopatz** [comment]
Hi @jonathanhogg, all, Thanks to @jb-leger in #2062, this the threadable predictor is considerably less hacky. But the right fix is still to declare in the commands cache that this call is not threadable. I have added #2121, though, just to be safe.

> Why do you guys capture the output of the subprocess rather than just hook it to the shell stdout? 

There are many reasons for this. Various people (myself included) want to be able to 

* store all output in history
* stream output through python loops, including multiple iterations
* hook up function aliases to file handles so they stream correctly.

Of course not all programs actually produce output that is worth capturing. The convention for flagging output as not worth storing / redirecting is called "alternate mode." Some programs like text editors and pages exclusively function in alternate.  Some programs, like shells (bash, python interpreter and other readline-based utilities, etc) never enter alternate mode but still aren't worth capturing / redirecting. So xonsh has to support all modes while still having the desired features above (which other shells don't have). If we didn't want those features we could have a simpler implementation.

**Comment by scopatz** [comment]
It turns out shells have some tricky edge cases ;)

**Comment by gforsyth** [comment]
> It turns out shells have some tricky edge cases ;)

New xonsh tagline

**Comment by scopatz** [comment]
So many feels, @gforsyth.... @jonathanhogg feel free to close this since the PR has been merged

**Comment by jonathanhogg** [comment]
@scopatz happy to close, but can I ask a couple more questions first?

I'm confused about the reference to "unthreadable" – isn't the problem here that the command is "uncapturable"? More specifically, the problem seems to be the attempt to continue capturing after the process has fork-and-exited; so wouldn't the most desirable fix be to either cease or background the capturing from an unclosed stdout if the process exits? Wouldn't that then solve the problem for all fork-and-log processes?

The following noddy program exhibits the same behaviour in xon.sh (hanging the shell instead of immediately returning to the prompt), but not in other shells:

```python
import os, time

if not os.fork():
    time.sleep(10)
    print("Hello World!")
```

**Comment by scopatz** [comment]
Hi @jonathanhogg - This is a confusing area, so don't worry. You are right in essence that unthreadable and uncapturable are distinct and that the important piece here is that the program is uncapturable. 

xonsh necessarily treats running external commands (`ls`, etc) different from running callable alias commands. For callable aliases, unthreadable and uncapturable are truly distinct, since xonsh has total control over what happens to the standard file descriptors (stdin, stdout, sterr). Also, it is possible for the alias author to declare how they want a command to be run. 

For external commands it is a bit trickier. We basically have no or limited idea of how a command should be run before it is run. Also different execution modes might have have different needs (think git, which sometimes opens a pager and sometimes doesn't). Thus by default we try to capture all commands, just in case the user might want to access the output or has explicitly said they want to capture the output. Unfortunately, Python's subprocess.Popen takes over the thread it was launched from. So to maintain interactivity and capturing, we have to run external commands on a separate thread. For external commands, uncapturable and unthreadable are currently highly coupled.

No one likes this and there are some options to remove this in the future. asyncio has a subprocess that could help us potentially, but would involve dropping Python v3.4 support. We might also fork/rewrite subprocess to do what we want. The main benefit of the current state-of-affairs is that is seems to work.

Pull requests welcome!

**Comment by jonathanhogg** [comment]
So I've just been having a look at the code and it looks like the problem is here (in `proc.py:CommandPipeline.iterraw()`):

```python
        while proc.poll() is None:
            # ...[elided]...
        # read from process now that it is over
        yield from safe_readlines(stdout)
        self.stream_stderr(safe_readlines(stderr))
        proc.wait()
        self._endtime()
        yield from safe_readlines(stdout)
        self.stream_stderr(safe_readlines(stderr))
```

The assumption here is that a process' stdout will always be closed when it exits and thus one can read it to exhaustion. I'm not sure why `safe_readlines()` is called both before and after `proc.wait()`.

Perhaps this could be changed to timeout immediately if no output is ready (as the process has ended, we should only be reading from buffered existing output in the normal case) and create a background task to continue draining the output if stdout/stderr has not closed?

I can't say that I'm familiar enough with the code base and design to be certain what would be an appropriate way to do this background draining, but I can have a go if you're interested…

**Comment by scopatz** [comment]
I am all for any attempt to improve this part of the code base!

>  I'm not sure why safe_readlines() is called both before and after proc.wait().

This is just to ensure that the buffers are fully read in and xonsh remains responsive.

> Perhaps this could be changed to timeout immediately if no output is ready

Maybe. I think that timeouts may not be entirely safe because they do not guarantee that the process has ended and won't kill it if it hasn't.  Timeouts basically only yield back control to the Python interpreter, which isn't exactly what we want here.

**Comment by jonathanhogg** [comment]
Ah, but we already know that the process has ended because `proc.poll()` has given up a return code.

I will attempt to look at ideas for improving in my copious free time (*droll laugh*).

**Comment by gforsyth** [comment]
I'm going to close this out @jonathanhogg as I believe it has been addressed, but please reopen if the issue persists.  Thanks!
