### ISSUE TITLE
Cannot set __xonsh_history__.buffersize in .xonshrc file

### ISSUE THREAD

**Issue by JohnLunzer** [xonsh/xonsh#2076]
As the title states, regardless of where I place the statement:
```python
__xonsh_history__.buffersize = 0
```
in my `.xonshrc` file it is returning as a NoneType. I am on the current master, c3ece74. I updated from 8f9e65f where this was not a problem. `__xonsh_history__.buffersize = 0` gives appearance of a "unified history" across consoles for up-arrow history. It only reads in the "unified history" at startup. 

buffersize is entirely undocumented.

After some searching I realize this "break" likely happened due to the inclusion of the sqlite history logic.

**Comment by JohnLunzer** [comment]
After a little further testing it looks like in `xonsh/ptk/history.py` that all history items are loaded regardless of history type.

I'm currently seeing the behavior as just stated but If somebody can confirm I will close this.

**Comment by scopatz** [comment]
We should have a more unified way of approaching this.  Buffersize isn't entirely undocumented, but it seems like it has only been implemented for the JSON backend. http://xon.sh/api/history/json.html?highlight=buffersize#xonsh.history.json.JsonHistory

The SQLite backend should probably also implement it, even if it ignores the value.

**Comment by mitnk** [comment]
Yes, the introduction of sqlite backend DID make `__xonsh_history__` not accessible in xonshrc. Because at that time, we need to read xonshrc first to know which backend to build. Anyway, to make `__xonsh_history__` available again is valid point to me.

> __xonsh_history__.buffersize = 0 gives appearance of a "unified history"
> across consoles for up-arrow history. It only reads in the "unified history" at startup.

I'm not quite catch with this, I do not understand what you want to achieve with it `= 0`. Could you provide more info?

Isn't `buffersize` only means how many items should keep in memory before flush to files?

> ... it has only been implemented for the JSON backend.
> http://xon.sh/api/history/json.html?highlight=buffersize#xonsh.history.json.JsonHistory

Isn't this only an internal implementing detail? Or it a public thing that xonsh user should know and can modify it? And if this is true, then mean user can put a `__xonsh_history__.filename = ~/hist.json` in xonshrc will make history backend always read/write history items in this single file all the time?

And what if user want implement a 3rd-part backend only need a ip and a port? (filename = "host:port"? :-)

**Comment by scopatz** [comment]
We probably need to have an event that is fired after history is initialized so that folks can manipulate history objects from the xonshrc.  We could also add additional envvars for history configuration, but an event is more general.

**Comment by JohnLunzer** [comment]
@mitnk Sorry for the long delay. This post from the xonsh google group explains the reason I previously used `xonsh_history.buffersize = 0`: https://groups.google.com/d/msg/xonsh/VVIPFQSXitI/bPxXnBNiCwAJ 

I believe with recent changes it is no longer relevant.

**Comment by mitnk** [comment]
I'll try adding history object back to xonshrc soon. For now you could try sqlite backend, which does not have buffered history items. It flush to db file for each command.

**Comment by JohnLunzer** [comment]
@mitnk, Honestly I would love to use the db backend, I think it's more robust not to mention more performant, unfortunately I've got about a year and a half of history I'd love to have access to, how difficult would it be to populate the the db with current json history?

**Comment by mitnk** [comment]
@JohnLunzer I think it would be a trivial thing to do it :) You could have a try. I don't think xonsh would add such a tool, but an xontrib is possible.

**Comment by mitnk** [comment]
@JohnLunzer this gist should do the trick: https://gist.github.com/mitnk/d9385c60e113eef14e41d42509846a5c

**Comment by scopatz** [comment]
Also I believe that you can use the `on_pre_cmdloop` event to modify history in the input file: http://xon.sh/events.html#on-pre-cmdloop

Given the number of different ways to address this, I am going to close this, but please feel free to reopen this issue if needed!
