### ISSUE TITLE
pylint etc, test coverage, related issues raised regarding 

### ISSUE THREAD

**Issue by zaxebo1** [xonsh/xonsh#2096]
i found this blog article having a contructive criticism of xonsh code:
http://www.skepticism.us/2015/11/xonsh-is-no-longer-a-possible-replacement-for-zsh/

- esp. the 'test coverage on being developed code' - issue on worry me. 
- what is the status of cleanliness of pylint run (on xonsh) report now?

Taking the issues raised there in a positive spirit, then is there any update/rebuttal/action taken status regarding issues raised in this article?

**Comment by melund** [comment]
Well. Some of the issues raised by @krader1961 have since been fixed. (e.g. history). Other issues are probably still valid points. That everything isn't perfect is expected for a relatively new project which is still under development. Contributions and PRs are very welcome. 

It is true that there are still some lint issues in the codebase. Not everyone has the same code preferences, and the automatic CI lint check was only added recently.  Other, points raised in the blog are just not valid. `map` and `filter` are not deprecated. And xonsh don't pretend to follow the google style guide. Also keep in mind that there may be more thought behind many of the inconsistencies that new users tend to spot. Speed is also crucial in xonsh. In many cases more important than style guides. 

Where I think @krader1961's argument completely breaks is when he complains about @scopatz not wanting lint-clean code and rejecting his cleanups. That is not true, and the code shown on the blog would be perfectly acceptable for new contributions. 

But rewriting existing code only for the purpose of style is bad for so many reasons. It will only make the code harder to read for the original authors when he later returns to it. It also disrupts tools like 'git blame'. But worst it risks introducing new bugs. 

Ramond Hettinger pulls out a famous quote "A foolish consistency is the hobgoblin of little minds"  in his talk: ["Beyond Pep8"](https://www.youtube.com/watch?v=wf-BqAjZb8M). He has many good takes on this topic. The worst practice he could think of was people Pep8'ing his code or making non-functional changes to existing code.

**Comment by laerus** [comment]
it's kind of funny the criticism against xonsh v0.2.3 (!) and the comparison with a 10 years old project.
btw if anything i believe @scopatz is more tolerant than i would like :laughing: 

also Raymond Hettinger on [Being a Core Developer in Python](https://www.youtube.com/watch?v=voXVTjwnn-U) 
rants about "going around changing other people's code"

:clap: on the joke about map/fitler

**Comment by scopatz** [comment]
Haha, I should be more bullish, perhaps. But to the point of this, I think we (tried) to address @krader1961's issues objectively in issues as he raised them. Then he wrote that blog post.  If there are specific things that folks feel are actionable, we can work on those.
