### ISSUE TITLE
git and/or vim breaking stdout

### ISSUE THREAD

**Issue by rtpg** [xonsh/xonsh#2186]
I've been having a bit of an issue with my shell output for a while (at least since a release ago), but I only just isolated some of the cause:

When I do `git commit` and use my default editor to edit the commit message (`vim`), after I commit, my output suddenly has tabs being "added" to it.

![image](https://cloud.githubusercontent.com/assets/1408472/22868976/f003cfe2-f1de-11e6-9965-63ad33541d85.png)

This problem persists for the rest of the shell session, and requires me to open a new terminal:

![image](https://cloud.githubusercontent.com/assets/1408472/22868989/038e4b96-f1df-11e6-8359-f0b014cf3673.png)

I have this problem when `git` is the one invoking `vim` (a similar issue when Github's `hub` tool invokes `vim`) but not when I just invoke `vim` by itself.

My theory would be that the issue comes from a process invoking another process, and then some state modifications because of that are missing (maybe `xonsh` doesn't properly reset the state in recursive execution?)

I hope this helps anyone working on the subprocess bug-squashing!

**Comment by scopatz** [comment]
Hi @rtpg - thanks for reporting!  Can you try adding the following to your xonshrc:

```python
__xonsh_commands_cache__.threadable_predictors['git'] = lambda args: False
```

I think that this is because of PopenThread getting in the way somehow.  Though a couple things should be noted:

1. I don't see this issue with the text editors I regularly use (less, nano, xo), so this makes me think it is a vim-specific issue.

>>> xonsh doesn't properly reset the state in recursive execution

2. The way shells work, xonsh actually doesn't have anything to do with nested subprocess calls. So when git opens your editor, all xonsh know is that git is sending bytes to stdout & stderr. 

This seems like it might be sanity thing, though. So another thing to try would be after the git command, try running:

```python
>>> __xonsh_shell__.shell.restore_tty_sanity()
```

Let us know if either of those work.  Also, it would be great to know if other vim users are having this problem.

**Comment by mitnk** [comment]
I've been encountering this issue for a few years (since started using vim?). And I think it may not related to xonsh. It also happens in Bash, IIRC. So it may not be a bug in shell level but in terminal level (not sure). But we still can dig it.

**Comment by rtpg** [comment]
`__xonsh_commands_cache__.threadable_predictors['git'] = lambda args: False` did the trick on this issue. TTY sanity didn't help, though.

 Though this doesn't work on my aliases (`gc` for example), I suppose I need to add this for each of those as well. Is the threadable-ness mainly just a performance thing?

**Comment by rtpg** [comment]
This was definitely something recent for me (last couple of months, but before that no issue), so _something_ changed in `xonsh` I think. I haven't touched my `vim` setup in a long time, and wasn't having any issues in zsh running this sort of stuff.

**Comment by mitnk** [comment]
Ah, okay, good to know this. Thanks :)

**Comment by scopatz** [comment]
@rtpg are your aliases function/callables or are they simple string substitutions?

**Comment by sejktmcsdlmfhsc** [comment]
I actually have the same effect as well (just was not aware that vim [may] triggered it) 
since recently-ish (0.5.1 if I had to guess):
After I open a regular vim session without edits (no problem with pyvim though), 
I will get scattered output for following commands be it "pip list" or pwgen for the rest of the xonsh session (as in screenshot).
```python
__xonsh_commands_cache__.threadable_predictors['git'] = lambda args: False
__xonsh_shell__.shell.restore_tty_sanity()
```
 did both unfortunately not help.

@scopatz but it only happens if I call vim with my alias ",v" instead of vim:
```python
aliases[',v'] = "vim"
```
![screenshot from 2017-02-13 20 08 36](https://cloud.githubusercontent.com/assets/21972784/22901045/5850e37a-f228-11e6-8140-59e028a4430f.png)

**Comment by rtpg** [comment]
@scopatz my aliases here are just strings. I just did a quick `for` loop to deal with this issue. 

I also was always using my aliases for this (`git` was also aliased to `hub` in my case).

**Comment by scopatz** [comment]
Hmm that is weird. The cache should pick up the base name of the underlying command after aliases have been resolved.  hub is a different command, so yeah, you'll also have to register that with the cache.

**Comment by scopatz** [comment]
See #2191 for a fix.

**Comment by rtpg** [comment]
Excellent, I'll give that a whirl. Thanks for the help on this

**Comment by mitnk** [comment]
@rtpg It seems you're using Mac. So FYI, the latest master breaks bare `git commit` command, see #2196. We will fix it soon. Sorry about this.

For now you can use `git commit -m 'xxx'` or run bare `git commit` in Bash :)

**Comment by gforsyth** [comment]
Hey @rtpg -- is this still an issue on your end or can we close it out?
