### ISSUE TITLE
trailing newline characters from __iter__ method of !() captured output

### ISSUE THREAD

**Issue by JohnLunzer** [xonsh/xonsh#2304]
When reading about #2302 I thought I'd do some searching to see if xonsh had implemented any inline looping mechanism. I didn't really find anything but I came across #311. I think there is still an oversight with from #311 .  

The return from the __iter__ method contains trailing newline characters in the resulting list of the `find` example in #311. Granted I think the original issue was technically resolved but the syntax savings hasn't been achieved. We're just trading `.split('\n')` for `.strip('\n')`. 

I'm not sure if there are large implications to adding `.strip('\n')`, maybe you't want to be more specific and just check the last character for a newline and do a `if line[-1] is '\n': line = line[:-1]`.

Anyway, this is obviously not high priority but is perhaps a blemish. I'd like to hear some thoughts, maybe I'm not seeing something important.

**Comment by astronouth7303** [comment]
I would point out that all other `.readline()` and IO iteration in Python has this same behavior. (Not that it's right or wrong, just consistent.)

**Comment by JohnLunzer** [comment]
You're right, I can't say I've experienced anything different in my Python life. My understanding of #311 was that it would offer some syntactic shortcut to using `.split('\n')` but I think it failed to do that since instead of dealing with the newlines at the start of the loop you have to deal with the newlines in the body of the loop.

I don't feel like adding an inconsistency here is an issue. By hijacking the `__iter__` builtin of the `!()` subprocess capture we've already created a specialized behavior. The `__iter__` builtin already has logic to strip trailing carriage returns. 

What I'm proposing is altering the specialized behavior to be even more useful by actually creating a syntactical shortcut, my concern is that I don't know if there is some negative side-effect I'm not considering.

**Comment by scopatz** [comment]
Hi @JohnLunzer, In my opinion, iterating through `!()` should have the same behaviour as iterating through a file object, since this is exactly what is happening. Is the current behaviour inconsistent with that?

**Comment by adqm** [comment]
I think the thing it's inconsistent with is other shells' behavior (primarily, Bash), where trailing newlines are removed when "capturing".

For example, if we (for some reason) have a command that makes more than one newline at the end of the file, the current iterator will yield a bunch of empty strings in addition to the "actual" content, whereas Bash would strip those out,

In my fork, I made it so that trailing newlines are always removed when we're capturing (whether it's with `$()` or `!()`).  If it's desirable, I can introduce a PR for that here (though it's not a big change in terms of code, just calling `rstrip` on the `output` before either returning it or creating the object from it).

**Comment by JohnLunzer** [comment]
@scopatz well maybe that is my point, Python isn't consistent in that there is more than one way to _read_ in lines of a file:
```python
with open("userinterface.py", "r")  as f:
     text = f.readlines()

with open("userinterface.py", "r")  as f:
     text = f.read().split("\n")

with open("userinterface.py", "r")  as f:
     text = f.read().splitlines()
```
Each assume knowing about how the data was read in. The latter two give the same output.

I would have to agree with @adqm, `xonsh` is first and foremost a shell, and should exhibit shell-like behavior when there is an _expectation_ of shell-like behavior.

Furthermore, in #311 the OP and subsequent posters are all using `.split()` or `.split('\n')`. At the point which we have access the to captured data (one big string) we've already passed the point at which we can use something like `.readlines()` and we're _forced_ to `.split()` the data. 

Looking at the code changes (#1183) that were made to "fix" #311 I'm confused as to how those newlines are getting into the output because @adqm used `.partition('\n')` which should have gotten rid of the newline characters and behaved similarly to if we had used `.split('\n')`. If there is an inconsistency I feel like it's here.

So again, @scopatz I think there is an inconsistency with both expectaction given how other shells work and with the expected behavior within Python.

**Comment by astronouth7303** [comment]
One thought is to add a `.lines()` generator with this behavior (or `lines()` builtin?)

**Comment by JohnLunzer** [comment]
@astronouth7303 adding such a generator or builtin would be a unnecessary as the standard Python machinery can accomplish the same thing with almost as much brevity. I'm trying to promote creating syntax light loops. All I can do is point to the evidence I've already given as motivation.

**Comment by rca** [comment]
I'm running into a similar issue; take the following use-case:

```
$ finger $(whoami) | grep -i shell
finger: berto
: no such user
```
This doesn't work because $(whoami) doesn't strip off the trailing newline:

```
$ echo $(whoami)
berto

berto@g6 ~
```

I did noticed that `which` _does work as expected_, I presume it's because xonsh does `.rstrip()` on this one:

```
berto@g6 ~
$ echo $(which xonsh)
/usr/local/bin/xonsh
berto@g6 ~
```

**Comment by scopatz** [comment]
@rca - yeah, it is unfortunate that whoami produces a newline, which then bash etc strips for you.  

In xonsh, as you can see [in the bash translation guide](http://xon.sh/bash_to_xsh.html) and [in the tutorial](http://xon.sh/tutorial.html#command-substitution-with), we use the `@$(cmd)` operator to strip the trailing newlines. 

`which` is an interesting case because it is actually implemented as a callable alias. This allows it to detect it is was called in a caputured of uncaptured subproces, and either forego or include the newline as approriate.

**Comment by scopatz** [comment]
On the to-do list is to improve the `@$(cmd)` syntax to allow for arbitrary output transformations.

**Comment by daniel-shimon** [comment]
Hi, this is an issue I stumble upon all the time, and I resort to doing things like `@($(cat SOME_FILE).strip())`

The thing is that unix and windows cli commands always append newlines to their output, and when `$(...)` is used in all shells adding a newline isn't appropriate or needed.

`@$(...)` isn't the solution either, since users don't always want to split the output to different arguments. 
For example, `ls @$(some_command)` will fail if there's a space in the output.

Here's another example.
On windows, currently there's no easy robust way to do the following:
`diff $(where xonsh) some_xonsh` won't work because of the newline.
`diff @$(where xonsh) some_xonsh` isn't robust since xonsh's path might contain a space.

I'm suggesting that `$(...)` will run `.rstrip('\n')` on it's output.
If a user wants to access the entire output without stripping, they can use the more complete `!(...)` feature.

**Comment by anki-code** [comment]
I'm going to close this because we have fresh big discussion in 3924.
