### ISSUE TITLE
Allow backslash-escaping globbing characters

### ISSUE THREAD

**Issue by tdsmith** [xonsh/xonsh#232]
To run e.g. `find . -name *.pdf` with an escaped asterisk (so that it doesn't match `foo.pdf` in the current working directory), I tried `find . -name \*.pdf`, which matches no files, presumably (I didn't investigate) because xonsh is handing find a literal backslash. `find . -name '*.pdf'` works.

I don't know what the set of bashisms xonsh wants to support is. Stop me if these aren't useful; I'm just reporting everything that caught me off-guard :)

**Comment by scopatz** [comment]
Thanks for reporting these! For what it is worth, I do think it is very helpful.  Personally, I don't mind the string method.  But if escape characters are going to be added then we may as well add this one.  Note that Bash requires `find . -name \*.pdf` form.

**Comment by laerus** [comment]
Closing this since you can escape anything you need with quotes or even the new subprocess macros,
for example `find . -iname! *.pdf` (notice the exclamation mark). Also it seems that xonsh is drifting away from implementing a backslask escape mechanism which would be painful at this point and not worth it imho. Feel free to reopen though.
