### ISSUE TITLE
xonsh equivelant of `if [[ -z "$VAR" ]]`

### ISSUE THREAD

**Issue by aidanharris** [xonsh/xonsh#2352]
Is there a xonsh specific way of checking if a variable is undefined?

Right now I'm using the following, but this seems ugly to me:

```python
try:
  $THING=$THING
except:
  $THING="Some Default Value"
```

**Comment by gforsyth** [comment]
You can do
`if 'VAR' in ${...}:'

On Apr 5, 2017 6:51 AM, "Aidan Harris" <notifications@github.com> wrote:

Is there a xonsh specific way of checking if a variable is undefined?

Right now I'm using the following, but this seems ugly to me:

try:
  $THING=$THINGexcept:
  $THING="Some Default Value"

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/xonsh/xonsh/issues/2352>, or mute the thread

**Comment by aidanharris** [comment]
That, worked. Thanks.

**Comment by gforsyth** [comment]
Happy to help. Also, for the use case you posted, since `${...}` is a dictionary, you could do:

```python
 $THING = ${...}.get('THING', 'DEFAULT_VALUE')
```
