### ISSUE TITLE
OSError: [Errno 7] Argument list too long

### ISSUE THREAD

**Issue by shipup** [xonsh/xonsh#2372]
I wrote a script witch take json from different URLS and parse them and at last writes the result in a file but at the middle of script I get this error:
```
Traceback (most recent call last):
  File "/home/shipup/.local/bin/xonsh", line 3, in <module>
    main()
  File "/home/shipup/.local/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 20479, in main
    _failback_to_other_shells(args, err)
  File "/home/shipup/.local/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 20443, in _failback_to_other_shells
    raise err
  File "/home/shipup/.local/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 20477, in main
    return main_xonsh(args)
  File "/home/shipup/.local/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 20519, in main_xonsh
    loc=None, mode='exec')
  File "/home/shipup/.local/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 3728, in run_script_with_cache
    run_compiled_code(ccode, glb, loc, mode)
  File "/home/shipup/.local/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 3634, in run_compiled_code
    func(code, glb, loc)
  File "./script.xsh", line 20, in <module>
    echo @(json.dumps(allPorts)) > allPorts.json
  File "/home/shipup/.local/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 19201, in subproc_captured_hiddenobject
    return run_subproc(cmds, captured='hiddenobject')
  File "/home/shipup/.local/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 19137, in run_subproc
    command = HiddenCommandPipeline(specs)
  File "/home/shipup/.local/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 13476, in __init__
    proc = spec.run(pipeline_group=pipeline_group)
  File "/home/shipup/.local/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 18826, in run
    p = self._run_binary(kwargs)
  File "/home/shipup/.local/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 18836, in _run_binary
    p = self.cls(self.cmd, bufsize=bufsize, **kwargs)
  File "/home/shipup/.local/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 12270, in __init__
    **kwargs)
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
OSError: [Errno 7] Argument list too long
```

I know that I have to use pythonic way to write in file instead of `echo @(arg) > file` but I think it's also a problem with xonsh

**Comment by gforsyth** [comment]
Hey @shipup -- thanks for reporting!  Could you please post the output of `xonfig` and also post your script to a gist or something similar and give us a link so we can look at it?

Also, if you could set `XONSH_DEBUG=1`, then start a new xonsh instance and then trigger this crash, the traceback from that would be very helpful.

**Comment by astronouth7303** [comment]
I suspect this will be one of those errors we'll have to accept and format to the user.

**Comment by shipup** [comment]
this is a simple sample script that cause error:
[https://gist.github.com/shipup/4ff347f797e1cc878b84b1b0cb984cbb#file-oserr-xsh](url)

and this my xonfig output:
`
+------------------+----------------------+
| xonsh            | 0.5.9                |
| Git SHA          | 2ae5218              |
| Commit Date      | Mar 15 12:06:26 2017 |
| Python           | 3.5.2                |
| PLY              | 3.9                  |
| have readline    | True                 |
| prompt toolkit   | None                 |
| shell type       | readline             |
| pygments         | None                 |
| on posix         | True                 |
| on linux         | True                 |
| distro           | Ubuntu               |
| on darwin        | False                |
| on windows       | False                |
| on cygwin        | False                |
| is superuser     | False                |
| default encoding | utf-8                |
| xonsh encoding   | utf-8                |
| encoding errors  | surrogateescape      |
+------------------+----------------------+

`

**Comment by laerus** [comment]
There is a limit in the arguments one can pass to `exec`
and i believe the current implementation passes all `hello`s
as a separate argument.

[reference](https://www.in-ulm.de/~mascheck/various/argmax/)

how do we want to solve this in xonsh?

**Comment by adqm** [comment]
@laerus: This will actually be a single, really long argument (though having something with lots of arguments probably hits the same issue).

Maybe we implement a <code>stream</code> built-in alias that streams a Python object's <code>str</code> representation, rather than just dumping it into the args list?  It doesn't quite solve the problem, but it provides an alternative that lets people get around it.

So:

```
myStr = ''

for i in range(100000):
  myStr += 'hello'
  
stream myStr > myfile
```

It's hard to do this "right" because scoping fights us pretty hard.  But here's a sketch of a hacky version that relies on the thing we want to stream being defined globally as a variable (works with the example above, at least in tako):

```
def _stream(args, stdin, stdout, stderr):
    varname = args[0]
    if varname in __xonsh_ctx__:
        for i in str(__xonsh_ctx__[varname]):
            stdout.write(i)
        return 0
    return 1
```

We could do a better job by actually implementing this as a special form, rather than as an alias.

**Comment by astronouth7303** [comment]
This isn't a problem we can solve. This is an OS limitation on the size of a process's argv. If we spawn an external process, there will always be a limit in the number of arguments that can be passed to it; it is out of our control and can't be worked around without cooperation of the spawnee.

The only limit Python has on list limits is memory, afaik.

What xonsh _can_ do is better format this error. Maybe with a count of how many arguments we tried to hand in? Maybe we can have slug throw a special error for this?

**Comment by riwogo** [comment]
I had the same problem with xonsh and I think this is a bug and I'm not agree with @astronouth7303 that you should format this error and show it to user because imagine user has wrote a script that reads a string from somewhere and writes it by `echo @(myStr) > file` to a file; the size of this string changes by time form very small to very big and one time he runs this script it works and another time it won't. I think it has a tremendously bad effect on user experience with xonsh and if xonsh wants to be an efficient shell it must solve these bugs.

**Comment by adqm** [comment]
@riwogo: What we are dealing with here is an OS limitation on the length of the argument list.  The long-and-short of it is that `echo @(myStr) > file` is not a good way to handle this when the `echo` being accessed is an external program.

We get this same error from Bash as well when launching external programs with long argument lists (for example, the GNU `echo` program with a long argument):

```
[hartz@desky ~]$ /usr/bin/echo $x
bash: /usr/bin/echo: Argument list too long
```
```
[hartz@desky ~]$ echo $x
hellohellohellohellohellohellohellohelloh...
```

Bash gets around this by having its own built-in `echo` command; I think doing that same thing for xonsh might make sense.  In fact, we already have such a thing, but it's just not the default.  I'm not sure if there's an easier way to get at this; it's been a while since I've been involved, but here is something that works (at least in simple cases):

```
hartz@desky ~ $ from xonsh.xoreutils.echo import echo as _echo
hartz@desky ~ $ aliases['echo'] = _echo
```

For example:
```
hartz@desky ~ $ /usr/bin/echo @('hello'*100000)
xonsh: For full traceback set: $XONSH_SHOW_TRACEBACK = True
OSError: [Errno 7] Argument list too long
```
```
hartz@desky ~ $ echo @('hello'*100000)
hellohellohellohellohellohellohellohelloh...
```
