### ISSUE TITLE
How do you set up auto complete for standard linux tools 

### ISSUE THREAD

**Issue by Khalian** [xonsh/xonsh#2379]
e.g. df -h where -h is autocompleted.

**Comment by gforsyth** [comment]
Hi @Khalian -- thanks for posting this. 

So this is a weird situation -- we have a bunch of completers that get tried in order until we get a hit adn then those hits are returned to the user. 

For something like `df`, since it can take a file as an argument, just doing `df <tab>` will give a list of files. This is the same behavior as bash (since we're just calling bash in this case). 

In this case, the `bash` completer picks up `df`, but oddly, the bash completions only offer the double-dash options (at least on my machine). We also offer man-page completions and those _do_ pick up the single dash options (although you first have to do `df -<tab>` to see them. 

For now, a simple-ish workaround is to swap the order of the completers so that man completions come before bash completions (this might impact other completions in less than ideal ways, but  we won't know unless we try)

To do that, you can first remove the `bash` completer, then re-add it to the completer list after the `man` completer -- you can stick this in your `xonshrc`

```console
🐚  completer remove bash
🐚  from xonsh.completers.bash import complete_from_bash as _complete_from_bash # don't pollute namespace
🐚  completer add bash complete_from_bash ">man"
```

**Comment by gforsyth** [comment]
Closing this as answered, if not in a particularly satisfying way.
