### ISSUE TITLE
Completion from man pages

### ISSUE THREAD

**Issue by zajaczajac** [xonsh/xonsh#247]
Hi!

On xonsh.org wishlist I've read about the idea of completion generated from man pages.
I've implemented a very simple version of such a functionality: https://github.com/zajaczajac/xonsh/commit/e25c99a4545ed475e69d5da8bddb1184f3f0462a  
It searches for option names starting with '-' or '--' and returns matching options. Of course it's not perfect and one can come up with better regular expressions to find more options but it's just an early draft.
One can also wonder if it's not gonna be too slow. But for manpages I tested it on it works really nice, and additionally I think that we could bound the length of manpage we process.
I'd love to hear some feedback and ideas :)

**Comment by scopatz** [comment]
Hi @zajaczajac! Thanks for working on this!  Would you mind opening a pull request for this? If you are unsure of how to do this, don't hesitate to ask questions.

**Comment by scopatz** [comment]
I am not sure that this is fully working, so maybe we should keep this open, or would you prefer another issue

**Comment by laerus** [comment]
oh sorry, truth is i didn't test this extensively, just some simple examples, reopening!

**Comment by blahgeek** [comment]
Hi everyone, I am interested in porting fish's manpage completion to xonsh, which is more feature complete and robust. I am not an expert of open source licensing, so I'm not sure if it's ok to do that. The related files are https://github.com/fish-shell/fish-shell/blob/master/share/tools/create_manpage_completions.py and https://github.com/fish-shell/fish-shell/blob/master/share/tools/deroff.py Could someone please take a look? Thanks!

**Comment by gforsyth** [comment]
Hey @blahgeek -- so with the usual disclaimers (I am not a lawyer, others may know better, software licensing is hard, etc....), I think the answer is no, it's not ok.  
BSD 3-clause and GPL v2 (which is what Fish is licensed under) are "compatible" according to GNU in the sense that code released under BSD can be combined with GPL code, but the resulting product must also be released under GPL.  
So this would require changing xonsh's license to GPL which isn't going to happen.
Others may have more details to add.  Sorry for the trouble!

**Comment by scopatz** [comment]
Hi @blahgeek, @gforsyth is totally right about the GPL vs BSD issues.  Interestingly though, the first file you linked, `create_manpage_completions.py`, is actually BSD 3-clause licensed if you look at it.  This means that you could copy this into xonsh and make some minor edits, as long as you retained the original copyright notice at the top, that is already there. 

So that simply leaves the deroff file to reimplement.  Interestingly, the deroff.py says it is ported from C.  If you go hunting, you can find [this version](ftp://ftp.mirrorservice.org/pub/NetBSD/NetBSD-release-7/src/usr.bin/deroff/deroff.c) which is also BSD licensed!  So basically, we'd just need to re-port the deroff file to Python.  If you C, it shouldn't be that hard, since about half the lines are data.  

If you don't know C or are stuggling with the port, please let me know. I am happy to help.  I'd love better man-page completion.  I just haven't ever gotten around to it.

I think this is much more tractable that it might initially appear.

**Comment by blahgeek** [comment]
That's great news! I think I can handle that, I'll let you know if I need some help :P 

And one more thing, now that I thought more throughly about this feature, I have some second thoughts... We already have a good implementation for bash completion, which supports pretty large amount of commands (see [here](https://github.com/scop/bash-completion/tree/master/completions)) which I think covers 90% of my personal use.

A main advantage of completion from manpage is that it has descriptions for argument (though description is not yet part of Completer API of xonsh, it's trivial to add since prompt-toolkit already supports it), but it would not even be used for most commands as long as bash completer has higher priority than manpage completer.

It also seems not right to have manpage completer higher priority than bash completer, since manpage completer is less accurate.

What do you think?

**Comment by blahgeek** [comment]
Well, for fish shell, they don't seems to have support for bash completer, so they have no choice. (Or maybe they do not use that on purpose?)

**Comment by scopatz** [comment]
@blahgeek - yeah I think that you are right about the mapage completion.  It would be great for descriptions, probably should have a lower priority than bash completions, and we should probably add a descriptions API to the completions interface, though not all shells could use it.

As per fish, I don't know a lot about fihs's development cycle. But I think it fair to guess that xonsh is probably one of the few shells to 'borrow' completions from another language :).  As you know, it can be pretty tricky...

**Comment by scopatz** [comment]
Any movement on this?

**Comment by scopatz** [comment]
This is been implemented

**Comment by InfiniteCoder01** [comment]
I'm on NixOS, and this doesn't seem to work. Note: I have set up my man pages as stated [here](https://nixos.wiki/wiki/Man_pages). I think I need to run some sort of index?
