### ISSUE TITLE
Xonsh calls __str__ method on all objects in env at startup

### ISSUE THREAD

**Issue by traverseda** [xonsh/xonsh#2494]
I would like to implement transparent encryption on xonsh enviroment objects. You can see my initial efforts [here](https://traverseda.github.io/lockedObject).

Unfortunately, all objects `__str__` methods get called at runtime, not as use-time. This prevents that functionality, and probably has other downsides, like preventing lazy-loading of complex objects.

I don't understand the implications of changing this to just check if the object is string-able, so I figured I'd create an issue.

**Comment by MrQubo** [comment]
I have a bug that `$CFLAGS`, which is a list, gets converted to a string in scripts. Haven't yet reported it but it might be related.
Also, the link is dead.

**Comment by scopatz** [comment]
Hi @traverseda! That sounds like and awesome idea.  As @MrQubo mentions, that link is broken.  I am curious where `__str__` is getting called.  That seems wrong.

@MrQubo - the `$CFLAGS` thing is a separate issue.  `$CFLAGS` probably hasn't been registered with the `Env` as needing to be converted to / from a Python list.  Can you open a separate issue or perhaps a PR? :) Thanks!

**Comment by anki-code** [comment]
I'm going to close this because:
* Too old issue
* The link to effort is not working (404)
* I believe this could be implemented as xontrib like [xontrib-history-encrypt](https://github.com/anki-code/xontrib-history-encrypt/)
* The code in [environ.py](https://github.com/xonsh/xonsh/blob/main/xonsh/environ.py) is pretty clean to understand the logic around environment first
