### ISSUE TITLE
Disambiguate identically named executables by path in tab completion

### ISSUE THREAD

**Issue by masaeedu** [xonsh/xonsh#2497]
Suppose I have two `find` executables in my PATH:

```
asaeeduddin@OV-5040-G65JHB2 D:\depot\git\autotest master $ which -a find
C:\WINDOWS\system32\find.exe (from PATH element 7)
D:\tools\chocolatey\cygwin\bin\find.exe (from PATH element 35)
```

I want to run the second one. If I type `find` and hit TAB, I see:

![image](https://user-images.githubusercontent.com/3674056/30715368-0e336510-9ee4-11e7-8736-199d3c7e4ff0.png)

There are two entries for `find.exe`, but both populate the line editor with an identical string ("find"), and will dispatch to the same executable (the first one in the PATH). It would be more useful if selecting the other tab-completion option resulted in the full path to executable being filled into the line editor.

**Comment by astronouth7303** [comment]
You can't actually disambiguate... if you type `find`, you'll always get the one that appears first in `$PATH`.

But we can deduplicate the list.

**Comment by masaeedu** [comment]
You can disambiguate by placing `D:\tools\chocolatey\cygwin\bin\find.exe` in the line editor when I tab to the second entry. This is how shells like Powershell work.

**Comment by gforsyth** [comment]
Hey @masaeedu -- there are two separate things here. The duplicate presence of `find.exe` in your completions is not because it shows up twice in your PATH but because, by default, "auto suggestions" based on your history are merged into the completions list.  You can disable this behavior by setting `$AUTO_SUGGEST_IN_COMPLETIONS=False` in your `xonshrc` 

As for allowing multiple versions of executables, I think that would be a substantial piece of work. It also violates the way that most POSIX systems work, I believe.

**Comment by masaeedu** [comment]
> It also violates the way that most POSIX systems work, I believe.

On my Linux system I can have identically named executables in /bin and /usr/local/bin, and depending on how the segments in my PATH are ordered I can use one or the other. I'm simply asking for the way tab completion works in my interactive shell (which is not a POSIX concern) to facilitate switching between the two without manually reordering my PATH.

**Comment by gforsyth** [comment]
> I'm simply asking for the way tab completion works in my interactive shell (which is not a POSIX concern) to facilitate switching between the two without manually reordering my PATH.

It's an interesting idea, but that's going to take some work. You need to first prepend the location in `PATH` to each executable (otherwise they'll be removed from the list when we de-dupe it using `set`) -- then redo the display of the completions a bit.  I imagine having the full path to each executable would be unusable in the completion dropdown, so you could insert the full path to each element in a meta-info field that lives below the dropdown box (the way IPython does in recent versions, calling out attributes vs functions, etc).
Also, we alphabetize the results, but that might not be the ideal behavior in this situation, so that would require some rewriting of the de-dupe and completion generation in general.

I can guide you through these changes if you want to take a crack at it. 

For my personal workflows, if I have a bunch of duped executables that I like to switch between, I do reorder my PATH.  If it's just one or two things, then you can always symlink and add a version number or reminder to the link name.

**Comment by masaeedu** [comment]
I was looking at [this file](https://github.com/xonsh/xonsh/blob/c787f9ab3ae563004c4a5cf4b5f9f47324f12ee8/xonsh/completers/path.py). I'm assuming the `complete_paths` bit in there and whatever consumes that needs to be changed? 

As a start I'm hoping I can just add any duplicate executables as additional elements in the tab completion list (you'd just see `find` twice), and invisibly associate the full path derived from which path segment the binary was found in. When tabbing through you can fill in the right path. It's not super-polished from the UI perspective, but it would work for what I need and would avoid the need to touch lots of stuff.
