### ISSUE TITLE
autocompletion flashes while typing

### ISSUE THREAD

**Issue by mikob** [xonsh/xonsh#2499]
Every time you type a letter the autocompletion suggestion clears and re-draws. A smoother experience would be preferable where the autosuggestion "clearing" wouldn't happen until the new suggestion is ready. FWIW On zsh I don't have this flashing happening while I type.

**Comment by melund** [comment]
What version are you using and what system are you on? Can you please post the output of the `xonfig` command?

**Comment by mikob** [comment]
Here's what it looks like: https://imgur.com/a/yTQma
```
$ xonfig
+------------------+---------------------+
| xonsh            | 0.5.12              |
| Git SHA          | 8941dfdd            |
| Commit Date      | Jun 7 16:04:39 2017 |
| Python           | 3.5.2               |
| PLY              | 3.9                 |
| have readline    | True                |
| prompt toolkit   | 1.0.8               |
| shell type       | prompt_toolkit      |
| pygments         | 2.1.3               |
| on posix         | True                |
| on linux         | True                |
| distro           | LinuxMint           |
| on darwin        | False               |
| on windows       | False               |
| on cygwin        | False               |
| is superuser     | False               |
| default encoding | utf-8               |
| xonsh encoding   | utf-8               |
| encoding errors  | surrogateescape     |
+------------------+---------------------+
```

**Comment by mikob** [comment]
I enabled `UPDATE_COMPLETIONS_ON_KEYPRESS` and now I'm seeing the prompt toolkit autocompletion suggestions. It's still flashy, however. Here's another example I recorded: 

https://asciinema.org/a/139845

**Comment by melund** [comment]
> I enabled UPDATE_COMPLETIONS_ON_KEYPRESS and now I'm seeing the prompt toolkit autocompletion suggestions.

Didn't you see completions in the first place? 

I don't see the same behavior on Windows. The autocompletion popup only appears when I press tab. Actually; UPDATE_COMPLETIONS_ON_KEYPRESS doesn't seem to make a difference for me.  Maybe prompt toolkit behaves differently here between Win and Linux 

Let see if others observe the same behavior as you on Linux.

**Comment by gforsyth** [comment]
Hey @mikob -- thanks for reporting this. 

First, the default behavior with the prompt_toolkit shell is to only show the dropdown list of completions when you press TAB and there is more than one possible completion (otherwise it will just complete).
There is an additional feature which is "autocomplete from history" that displays the ghost text that is shown in the videos you posted. That completion is drawn from your history and is not necessarily valid (depending on what the command is) -- you can select that command using either the right arrow key or Ctrl+e

The flashing looks like the result of a separate option -- what is the value of `$UPDATE_PROMPT_ON_KEYPRESS`? Some people use that to show the status of (say) command mode vs insert mode, but it can lead to that flashing, so you might try setting that to False and seeing if you like that better. 

Let me know if any of that helps.

**Comment by mikob** [comment]
`$UPDATE_COMPLETIONS_ON_KEYPRESS` and `$AUTO_SUGGEST` are `True` `$UPDATE_PROMPT_ON_KEYPRESS` is False. Alternating values with `$AUTO_SUGGEST` and `$UPDATE_COMPLETIONS_ON_KEYPRESS` doesn't make a difference. Both flash. It seems to be completely redrawing on each keypress, but it would be possible to only redraw if the completion suggestions change for either, would it not? I will happily look into it and make a PR if someone can give me some general pointers at what code to pick at or if there's anything special to keep in mind with this functionality.

**Comment by gforsyth** [comment]
The `AUTO_SUGGEST` implementation is part of `prompt_toolkit`, so you would have to implement it there.

**Comment by anki-code** [comment]
Hello @mikob! I can't reproduce this on 0.9.22. Looks solved.
