### ISSUE TITLE
[Mac] Prompt not showing correctly

### ISSUE THREAD

**Issue by zajaczajac** [xonsh/xonsh#254]
![screen shot 2015-05-25 at 14 29 12](https://cloud.githubusercontent.com/assets/4266489/7797301/a43a94b8-02ea-11e5-8715-2673834167a4.png)
There's a problem on OS X with prompt not showing correctly, it looks like the ending of it goes to the beginning. It happens when width of the terminal is smaller than some value (but as you can see on the screen, it would could fit correctly)

**Comment by zajaczajac** [comment]
Oh, I didn't notice that the problem has been discussed already - https://github.com/scopatz/xonsh/issues/21
I've conducted some investigation today and it seems that the function to be blamed is input(string) built-in python function which is called by Cmd's cmdloop(). It seems that if we pass as an argument string that contains colour codes and is longer that some value (around 1/2 of terminal width) then this problem happens.
What we can do is to set use_rawinput to 0 (Cmd class parameter) and then cmdloop just prints the prompt and reads line each time - so tab completion and up&down arrow don't work.

**Comment by scopatz** [comment]
Hi @zajaczajac - yeah we were never able to determine a root cause of this bug.  However, I think that a good fix would be to use the prompt-toolkit shell instead of the readline shell. There are some docs in the repo that tell you how to set this up. it is basically `pip install prompt-toolkit` and then in the xonshrc `$PROMPT_TOOLKIT_SHELL=True` for the moment (though this may change).

**Comment by santagada** [comment]
This now work on both readline (with gnureadline installed) or prompt-toolkit.
