### ISSUE TITLE
Some piped command never finishes

### ISSUE THREAD

**Issue by dosimple** [xonsh/xonsh#2594]
`yes | dd bs=1 count=1 | wc`

it never finishes in xonsh, where as in other shells it does. My setup: current Debian testing with xonsh 0.6.0+dfsg-1.

**Comment by gforsyth** [comment]
Hi @dosimple -- thanks for reporting! 
I can confirm that this looks like a bug.  Something in the threading is swallowing something and `wc` never returns

**Comment by scopatz** [comment]
Note that almost certainly doesn't do what you think it should because `dd` displays to stderr, not stdout. Therefore wc is not actually reading any input and dd isn't closing the handle to its stdout.  I think `dd` is the bad actor here.

Alternatively it may be the case that xonsh doesn't handle the case where a proc in the middle of a pipeline is the first to exit.

**Comment by scopatz** [comment]
#2600 should fix this. It does seem to be the intermediate hanging issue.

**Comment by scopatz** [comment]
Fixed in #2600 - please feel free to reopen if needed!
