### ISSUE TITLE
Replace cmd on Windows

### ISSUE THREAD

**Issue by skjerns** [xonsh/xonsh#2643]
Is it possible or even advisable to replace the `cmd.exe` on Windows?
I'm so used to type `cmd` and have some external apps that open `cmd` that this would be quite useful.

(I've asked this question on the IRC as well, but I got disconnected before checking for answers, my apologies if it has been answered there.)

**Comment by melund** [comment]
Do you mean redirect all calls to cmd.exe to xonsh?  No. I don't think that is possible. But do try and tell me what blows up :) 

Xonsh resembles shells on linux, so many tools will have problems if you point them to xonsh instead of cmd.exe. 

I use xonsh as the terminal in Visual Studio Code for example. It works to some extent. 

![image](https://user-images.githubusercontent.com/1038978/39838255-2b71ef70-53d9-11e8-8edc-1f0baa3093fc.png)

But when I use the task system to start commands in the shell, it still think it should pass commands as if it were cmd.exe and I get errors like this:
```
> Executing task: make html <

xonsh: /d: No such file or directory.
```

**Comment by skjerns** [comment]
Okay, that's already good to know, thanks!
I guess I can look into writing a wrapper that redirects all calls to `cmd.exe` unless no command line options are given.

**Comment by AngellusMortis** [comment]
If you are on Windows 10, I would recommend enabling WSL and installing a Linux distro. I use Arch on my devices and xonsh works fine.

I would not recommend trying to replace cmd.exe or Powershell. Windows is not designed to use different type of shells. WSL is the closest thing you will get to supporting other shells.

**Comment by scopatz** [comment]
In my (more limited) experience, xonsh does work perfectly fine on windows inside of cmd.exe. I tend to use Anaconda the anaconda shell lets me install and run xonsh without problems.

**Comment by santagada** [comment]
I used daily xonsh as my default shell on windows, but instead of cmd.exe I use it inside ConEmu (and commander http://cmder.net/). Besides the error that was just fixed I only sometimes need to run cmd.exe (or powershell), and it is usually because I want to write a .bat file and need to test a command out.

**Comment by skjerns** [comment]
thanks! I'll look into that.

**Comment by melund** [comment]
@skjerns. Conhost, the underlying terminal in which cmd.exe and PowerShell runs changed a lot in Windows 10. It now supports the all the same features.
