### ISSUE TITLE
is it possible to display a document for alias define with ? or ?? like function

### ISSUE THREAD

**Issue by eggcaker** [xonsh/xonsh#2676]
I've defined a alias mapping to a function like: 

```
def _say_hi():
    "" Say hello. """
    print("hi")

aliases['hi'] = _say_hi
```

with i type _say_hi? or _say_hi?? I can see the documentation or source,  is it possible to get same results when type `hi?` and `hi??` ?

**Comment by dratini0** [comment]
I think the reason behind this is that aliases operate in subprocess mode, while `?` and `??` operate in python mode. The same goes for, for example, `dirs?`. Try something like `aliases['hi']?`.

**Comment by eggcaker** [comment]
with `aliases['hi']` can get the results i want, just wondering I can hack the command not found handler to do it 
```
 ~/src/learn/xonsh/ $ hi??
xonsh: subprocess mode: command not found: hi??
Did you mean the following?
    hi:  Alias
```

**Comment by scopatz** [comment]
This is a cool idea @eggcaker! It would also be cool if `?` and `??` brought up `--help` and `man cmd` respectively for all subprocesses. 

The functions that are being called are helper() and superhelper() respectively, see https://github.com/xonsh/xonsh/blob/75120dfd20c2ffc300cb30071b91bd91018cab89/xonsh/built_ins.py#L71.

Unfortunately, I am not sure this is super easy to hack in because the error is being through before these functions are called. To do this, we'd need to change the function signature to require the name. Then it would take a little more work in the parser to generate an AST that doesn't throw an error if the object doesn't exist, see https://github.com/xonsh/xonsh/blob/9b95d9b6f4b1e7366cda94c64a9f7376e7d7bdf9/xonsh/parsers/base.py#L119

If anyone is interested in taking a stab at this, let me know. I'd be happy to help!
