### ISSUE TITLE
Auto complete cd path list not check if directory exits in current folder

### ISSUE THREAD

**Issue by eggcaker** [xonsh/xonsh#2690]
when I  ran `cd folderA` in ~/Desktop, when change to /etc for example, when I type cd still suggest a `folderA` to cd, when press tab and press enter will get message: 
```
cd: no such file or directory: folderA/
```
should be better do not suggest  the directory if not exits current directory ?

**Comment by gforsyth** [comment]
Hey @eggcaker -- `folderA` is showing up because you have `$AUTO_SUGGEST_IN_COMPLETIONS=True`.  The ghosted auto suggest completions are redrawn at each keypress and just match against history, not context.  If you don't want them to show up in the tab complete list, just set that envvar to `False`.

**Comment by eggcaker** [comment]
OK. I'll try that option later thanks
