### ISSUE TITLE
Are bash lists supported?

### ISSUE THREAD

**Issue by guilhermeleobas** [xonsh/xonsh#2743]
## Current Behavior

I have a few bash scripts that uses bash list notation. When I tried to use those with `source-bash`, the variable is not exported. For instance, in the code below, `d` is not exported at all but `first` is. 

```bash
#!/usr/bin/env bash
export d=($(ls -d */))
export first=${d[0]}
```

## Expected Behavior

Be able to access `d` from xonsh. 

## xonfig

```
+------------------+-----------------+
| xonsh            | 0.7.0           |
| Python           | 3.7.0           |
| PLY              | 3.9             |
| have readline    | True            |
| prompt toolkit   | None            |
| shell type       | readline        |
| pygments         | None            |
| on posix         | True            |
| on linux         | False           |
| on darwin        | True            |
| on windows       | False           |
| on cygwin        | False           |
| on msys2         | False           |
| is superuser     | False           |
| default encoding | utf-8           |
| xonsh encoding   | utf-8           |
| encoding errors  | surrogateescape |
+------------------+-----------------+
```

## Steps to Reproduce
1. Save the script above as a .sh file
2. `source-bash file.sh`
3. `echo $d, echo ${d[@]}, echo ${d} # None of the them works`

**Comment by scopatz** [comment]
Hi @guilhermeleobas - I think the issue here is that bash arrays [cannot be](http://wiki.bash-hackers.org/syntax/arrays#storing_values) [exported](https://stackoverflow.com/questions/5564418/exporting-an-array-in-bash-script).  So the issue here isn't so much that that you are doing something, wrong but rather that Bash has no way of passing an array to the environment.

If you want to pass it to the environment, you'd have to serialize it (ie convert it to a string) somehow first.

**Comment by guilhermeleobas** [comment]
Oops :)

Thanks a lot for the answer @scopatz
