### ISSUE TITLE
Async prompt?

### ISSUE THREAD

**Issue by xeor** [xonsh/xonsh#2803]
## xonfig

```
+------------------+-----------------+
| xonsh            | 0.7.7           |
| Python           | 3.7.0           |
| PLY              | 3.9             |
| have readline    | True            |
| prompt toolkit   | 2.0.4           |
| shell type       | prompt_toolkit2 |
| pygments         | 2.2.0           |
| on posix         | True            |
| on linux         | False           |
| on darwin        | True            |
| on windows       | False           |
| on cygwin        | False           |
| on msys2         | False           |
| is superuser     | False           |
| default encoding | utf-8           |
| xonsh encoding   | utf-8           |
| encoding errors  | surrogateescape |
+------------------+-----------------+
```

## Question

I've looked around xonsh sourcecode, prompt_toolkit source, and the docs. But I am unable to find a way to update the prompt/screen while a command is running.

Example, if a command I run suddenly uses over 80% cpu, I would like a tiny message in the button right corner to give me the cpu percent. Is this possible?

I tried a couple of different things with prompt_toolkit, like using threads, but I could not update any text in the terminal until the process was done executing.

Based on https://github.com/xonsh/xonsh/blob/b69fb9ab4bf0def1b702db74e016bf43a8478606/xonsh/codecache.py#L68, I don't think this is possible? There is no async, it blocks.. Or am I wrong?

**Comment by scopatz** [comment]
Hi there @xeor - that sounds like an awesome feature!  

You are correct that right now we have no way of asynchronously running code.  It might not be so hard to do (hopefully).  The right place to look would be the [`BaseShell`](https://github.com/xonsh/xonsh/blob/master/xonsh/base_shell.py#L294) class.  

There might be some issues with running subprocesses outside of the main thread. So rather than running asynchronously, maybe something that could be done would be to spawn a thread that run a callback function during execution.

We'd be happy to review / merge a PR to this effect!

**Comment by xeor** [comment]
I'm fairly new to this project.. So I might need some more info to get this thing going :)

Might something like this be a way to do this?

* Inside the logic that handles prompt update, add a new event that listens, but on a separate thread.. This would need to wrap a lot of logic inside that thread..
* Inside on_precommand, you could fire events picked up by inside the thread..

I havent worked much with threads in python, so this might be completely wrong.. :/

**Comment by scopatz** [comment]
Hi @xeor - sorry for the slow reply.  Yeah, that is an interesting idea and would be worth a shot. I am not sure if subprocess blocks other threads, though.  I don't think it does...

**Comment by agriffis** [comment]
Disclaimer - I haven't used xonsh much. I just found this issue because I wondered if xonsh solves the async prompt problem, so I googled for "xonsh async prompt" and voila!

I think there are two scenarios for async prompts:

1. You'd like to display some expensive information in the prompt, such as virtual machine status. Since it will take a while to gather the information, it would be ideal to display the prompt and then asynchronously update the details _while still typing at the prompt_.

2. You'd like to monitor something about the system, or perhaps display notifications from an event source, _while processes are running_.

In the first scenario, xonsh/pt is still in control of the terminal, so coordination isn't too tricky. In particular, you don't have to worry about what terminal mode or escape codes are in process, assuming the async prompt updates are handled by the same event handler as keystrokes.

In the second scenario, something else is in control of the terminal. What you need at that point is brokered access to the terminal to coordinate the updates from the running process and the async process—in other words you need a terminal emulator. The best answer for that scenario is likely tmux, for some examples see https://github.com/git-pull/tao-of-tmux/blob/master/manuscript/09-status-bar.md

But I still think the first scenario is interesting, and it's what I think of as "async prompt" :grin:

**Comment by astronouth7303** [comment]
Ok, traditionally when shells execute foreground commands, they hand control of the terminal completely over to the pipeline.

Ignoring the concept of a "button" inside of a terminal, which is a huge can of worms.

Implementing this kind of pipeline injection has pretty huge compatibility problems, which xonsh already has too many of.

Like, if `nano` is running, you can't do this. Note that this can happen if the user runs `nano`, or if they run a command like `git commit` or `crontab -e` or any number of other commands that invoke $EDITOR.

POSIX (as I understand it) does not easily allow us to determine what program(s) are ultimately controlling the terminal. (Given that there is a foreground process group, it could be any number.)

While this would be very cool, there's a _lot_ of foundational and model-breaking problems that are soooo beyond our control. (This is the same kind of foundational problems why we can't keep stdout/stderr synchronized but separated.)

**Comment by jnoortheen** [comment]
currently I am trying to make getting git information on xonsh-ptk prompt in async way. I see that xonsh has way to update the prompt on [keystroke](https://xon.sh/envvars.html#update-prompt-on-keypress). Can we do the same for getting the prompt's components as well? something like we trigger the work in background using threads and update the prompt after the thread is done.

a prompt like shown here - https://asciinema.org/a/0pm9OuFzANazrHKXaBKDdJ5hz
with powerlevel10k theme https://github.com/romkatv/gitstatus/issues/33#issuecomment-498144887

**Comment by jnoortheen** [comment]
also I found this for fish shell - https://github.com/acomagu/fish-async-prompt

**Comment by scopatz** [comment]
Yeah, at this point we should be able to add these async components.  PRs very welcome here!

**Comment by anki-code** [comment]
>  something like we trigger the work in background using threads and update the prompt after the thread is done.

Wow! It will be incredible great to use this in [xontrib-prompt-bar](https://github.com/anki-code/xontrib-prompt-bar) for the sections rendering.

**Comment by jnoortheen** [comment]
I have added a PR. Please take a look @scopatz .

**Comment by anki-code** [comment]
@jnoortheen It looks like cool feature! Thanks! Could you please give an example the simple prompt with async sections loading? 

May be add it to the [xonsh tutorial](https://xon.sh/tutorial.html#customizing-the-prompt)?
