### ISSUE TITLE
How to disable 'skipping application of alias' message and let xonsh aliases take precedence

### ISSUE THREAD

**Issue by comfortablynick** [xonsh/xonsh#2810]
## xonfig

```
+------------------+-----------------+
| xonsh            | 0.7.7           |
| Python           | 3.6.5           |
| PLY              | 3.9             |
| have readline    | True            |
| prompt toolkit   | 2.0.4           |
| shell type       | prompt_toolkit2 |
| pygments         | None            |
| on posix         | True            |
| on linux         | True            |
| distro           | Ubuntu          |
| on darwin        | False           |
| on windows       | False           |
| on cygwin        | False           |
| on msys2         | False           |
| is superuser     | False           |
| default encoding | utf-8           |
| xonsh encoding   | utf-8           |
| encoding errors  | surrogateescape |
+------------------+-----------------+
```

## Expected Behavior

I have just started using xonsh and would like to make it my main shell, but still be able to use bash aliases in both places. Ideally, xonsh should ignore any bash aliases that have the same name. If an alias has been defined in xonsh, I would like it to take precedence over any foreign aliases.

I don't want to see this error message every time I open the shell, and the `--overwrite-alias` option seems to do the opposite of what I want. Perhaps the ideal solution is to only print this message when `XONSH_DEBUG` is set.

## Current Behavior

I get this message every time I open xonsh:
```
Skipping application of 'ls' alias from 'bash' since it shares a name 
with an existing xonsh alias. Use "--overwrite-alias" option to 
apply it anyway.
```

## Steps to Reproduce

Open xonsh with bash sourced as a foreign shell, since bash usually has `alias ls='ls --color=auto'` defined by default.

**Comment by scopatz** [comment]
Thanks for bringing this up @comfortablynick! I have opened up #2811, which adds a `$FOREIGN_ALIASES_SUPPRESS_SKIP_MESSAGE` env var you can set to `True` in your xonshrc, and also a `--suppress-skip-message` you can use in `source-bash` commands.

I elected to go with something more specific, rather than go with a general debug hook, because it doesn't seem to me like anything is wrong per se here (and in need of debuging information). Rather it is just that there is different preferred behavior.
