### ISSUE TITLE
Exporting Environment Variable in One Line

### ISSUE THREAD

**Issue by EmreAtes** [xonsh/xonsh#2819]
I have 2 questions,

1. What is the xonsh equivalent for a one-line bash or zsh command such as 
`$ TERM=xterm-256color ssh`
This would also be useful for things like 
`$ CC=/usr/bin/gcc ./configure`

2. To fix this, I also tried putting this in my `.xonshrc` but I couldn't get it to work:

```
from xonsh.tools import uncapturable

@uncapturable
def _ssh(args, stdin=None):
    $TERM = 'xterm-256color'
    /usr/bin/ssh args

aliases['ssh'] = _ssh
```

I'm getting this error: 
`ssh: Could not resolve hostname args: Name or service not known`

Perhaps the example here (https://xon.sh/tutorial.html#uncapturable-aliases) could be changed to use arguments instead of just calling vim for a single file

**Comment by gforsyth** [comment]
Hey @EmreAtes -- good questions!

For env-var swapping, if you aren't married to one-liners, then one shortcut we have is that `${...}` points to the environment and it has a `swap` method, so you can use a context manager and do something like:

```
 ~ 🐚  with ${...}.swap(CC='/usr/bin/gcc'):
......     echo $CC
......
/usr/bin/gcc
```

If you want a one-liner, you can also use `env` and do e.g.

```
 ~ 🐚  env TERM=xterm-256color echo $TERM
xterm-256color
```

As for the error in your alias, which should work otherwise, since you are using a subprocess command `/usr/bin/ssh` on the second line and `args` is in the Python context you need to wrap the args in `@()`

so

```
from xonsh.tools import uncapturable

@uncapturable
def _ssh(args, stdin=None):
    $TERM = 'xterm-256color'
    /usr/bin/ssh @(args)

aliases['ssh'] = _ssh
```

will work.

And improvements to the docs are always welcome!

**Comment by EmreAtes** [comment]
Thanks for the quick reply. I added a documentation PR.
