### ISSUE TITLE
Change auto_completer's color style

### ISSUE THREAD

**Issue by vaaaaanquish** [xonsh/xonsh#2840]
I want change auto_completer's complete color style using prompt-toolkit 2.x. Because, default white is not good for my eyes.
<img width="232" alt="2018-09-24 1 15 19" src="https://user-images.githubusercontent.com/4796081/45930169-64635b00-bf97-11e8-9a0b-5606aba152f2.png">

According to ptk document, It seems to give `style` and `selected_style` to prompt_toolkit.completion.Completion's args.
https://python-prompt-toolkit.readthedocs.io/en/master/pages/reference.html#prompt_toolkit.completion.Completion

I will make pull requests.

**Comment by laloch** [comment]
This problem is very similar to #2838. Both the completion and the toolbar styles are defined by the PTK's default style and there seems to be no way to redefine the styles in xonsh. I think it would be better to provide a hook for overriding the PTK stylesheet globally.

**Comment by laloch** [comment]
@vaaaaanquish I just did
```
import sys
defstyle = sys.modules['prompt_toolkit.styles.defaults']                   
defstyle.PROMPT_TOOLKIT_STYLE.append(('completion-menu','bg:#333333 #eeeeee'))
```
and it worked. So it's definitely possible.

**Comment by melund** [comment]
We used to have a way to control those things: 
https://github.com/xonsh/xonsh/blob/master/xonsh/pyghooks.py#L515-L528

But it seems that PTK2 new way of styling doesn't respect those when they come through the pygments link. 

The problem is that everything in xonsh still relies on styles being `(Token, style_str)` whereas PTK2 now uses `(class_string, style_str)`.

@jonathanslenders is there anyway to control the PTK2 styles (e.g. `completion-menu`) when they are passed in through the pygments interface (`style_from_pygments_cls`, or `style_from_pygments_dict`).

**Comment by vaaaaanquish** [comment]
Thank you. I also think that using PTK2's style is smart.
I will look at [pyghooks.py](https://github.com/xonsh/xonsh/blob/master/xonsh/pyghooks.py#L515-L528)

**Comment by jonathanslenders** [comment]
@melund,

Unfortunately, it's not possible out of the box, because ``Token.X.Y`` translates into ``class:pygments.x.y`` instead of ``class:x.y``. So you can't use a Pygments Token to style non pygments stuff.

However, the pgcli developers created the following translation table:
```python

**Comment by scopatz** [comment]
I am happy to merge whatever works here @vaaaaanquish @laloch @jonathanslenders.  Pull requests very welcome!
