### ISSUE TITLE
Official extension and shebang

### ISSUE THREAD

**Issue by techtonik** [xonsh/xonsh#2990]
What it the official file extension for `xonsh` scripts? Also what is the recommended shebang to prepend such scripts?

http://xon.sh/bash_to_xsh.html doesn't tell anything.

**Comment by gforsyth** [comment]
File extension is `xsh`, the shebang I use is `#!/usr/bin/env xonsh`

Improvements to the docs are always welcome!

**Comment by astronouth7303** [comment]
It would be noted that there is wide variance in how xonsh is installed, so the shbang varies.

**Comment by ErickTucto** [comment]
> File extension is `xsh`, the shebang I use is `#!/usr/bin/env xonsh`
> 
> Improvements to the docs are always welcome!

I have problems with the shebang

![script](https://user-images.githubusercontent.com/22831024/86308629-6c761300-bbdf-11ea-8fc2-535894d4f2aa.png)

**Comment by laloch** [comment]
@ErickTucto, what makes you think it's a problem with the shebang?

You have, in fact, a syntax error at the `ln -s @(me)/scripts {$HOME}/.scripts` line. The position of the syntax error is, however, improperly reported by the parser. The real problem is your use of curly braces in the last argument to the `ln` command. The correct Xonsh syntax would be
```
ln -s @(me)/scripts $HOME/.scripts
```

**Comment by ErickTucto** [comment]
thanks, the problem was the brackets
