### ISSUE TITLE
Add support for clearing or selectively purging session history

### ISSUE THREAD

**Issue by jaraco** [xonsh/xonsh#3033]
## Current Behavior

Currently, it's not straightforward to clear the session history, such as after accidentally leaking sensitive information onto a command.

In [this discussion](https://gitter.im/xonsh/xonsh?at=5c77e94f5c5c1f016d4f8f5f) Anthony and I discuss the considerations and possible solutions.

## Expected Behavior

There should be a straightforward way to clear the history for a session. Bonus if the technique also allows to clear the last 'n' commands or otherwise purge a slice of commands from the history.

Anthony suggests a `history clear` command as a high-level interface. I'd also like to see a low-level interface for more direct manipulation.

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by scopatz** [comment]
Thanks for opening this! Pull requests welcome

**Comment by anki-code** [comment]
I'm going to close this issue because it has unfocused description:
* We already have `history clear` command now.
* We have [xontrib-history-encrypt](https://github.com/anki-code/xontrib-history-encrypt/) xontrib to encrypt the history to prevent leaking sensitive data (with `dummy` option that disables history)
* In case of using sqlite history there is simple way to dive into history or delete some rows - https://github.com/xonsh/xonsh/issues/3401#issuecomment-835272083

**Comment by jaraco** [comment]
Sounds good. Thanks for the consideration. Would it also work to `del __xonsh__.history[-5:]`? Looks like that doesn't work yet. That would be the next iteration on this feature I'd like to see:

```
$ del __xonsh__.history[-5:]
AttributeError: __delitem__
```
