### ISSUE TITLE
Will xonsh work well as a replacement for cmd.exe on Windows?

### ISSUE THREAD

**Issue by certik** [xonsh/xonsh#3062]
For my projects, many times I have to provide CI scripts (on Linux, Mac and Windows) that build the project, test it, package it, upload it, etc. It turns out large subset of this can be made platform independent. 

Sometimes I use Python if I needed to run the same script on all three platforms, but it's verbose, and does not feel like a script. Some other times I use Bash on Linux/Mac and cmd.exe on Windows, which results in code duplication and the time spent debugging it on Linux does not contribute to the script robustness on Windows, because the script is not shared.

Is Xonsh meant to be used in my scenario? It looks like a script, and yet the same script will work on all platforms, so one can debug the main logic of the script, say, on Linux, and then just test on Mac/Windows and if it fails, the bug is probably minor, it's not a syntax error, or some error in the logic, since the exact same script runs on Linux.

If the answer is yes, I should give Xonsh a serious try, then I suggest the following:
* add `cmd.exe` to this comparison table: https://xon.sh/#comparison
* mention at https://xon.sh/windows.html, that Xonsh is meant to be a much better replacement for `cmd.exe` on Windows
* mention my use case somewhere in the documentation

**Comment by jaraco** [comment]
Personally, I've adopted xonsh as my shell for all the platforms you mentioned.

The first thing I noticed when I started using xonsh as my main shell on Windows, however, was that it's missing the built-in commands support (e.g. there's no `dir` or `ls`).

I've found that to be the main defect preventing the adoption of xonsh as my main shell, so to remedy the situation, I revived pycoreutils as [cmdix](https://pypi.org/project/cmdix). Installed alongside xonsh, this library provides many of the coreutils, which are normally binaries on Unix systems.

I should also give a shout out to [Hyper](https://hyper.is/), which I use as a terminal to get a cross-platform terminal as well. Highly recommend.

**Comment by melund** [comment]
I am also using xonsh as my main shell on Windows. The easiest way to get the Linux coreutils is through 'Git for Windows'. During the installation you can choose to add all the MSys tools to path. It works really well . 

Since we can probably assume all windows xonsh users has git installed we could make a xontrib which would add the tools even if Git was installed the default way. This could even be default xontrib. What do you think?

Only issues issues I gave had is with with Visual Studio Code integration. I use it as an integrated shell there too. But not everything is working out of the box.

Also, if you have a Windows 10 install which more than a year old the terminal colors are likely the old colors. There is a tips to fix that here
https://xon.sh/windows.html#color-style

On newly installed Win 10 machines the colors are good by default and $INTENSIFY_COLORS_ON_WIN can be set to false.

**Comment by gilch** [comment]
> The first thing I noticed when I started using xonsh as my main shell on Windows, however, was that it's missing the built-in commands support (e.g. there's no dir or ls).

@jaraco You actually can use `dir` on Windows in Xonsh. It just happens to collide with the name of a Python builtin, so it's shadowed. You can force shell mode with `$[dir]` or add an explicit argument for the same effect, like `dir .`, etc. The command is there.

What other commands are missing?

**Comment by jaraco** [comment]
If I recall correctly, "make dir" and "make symlink" are also not executables available (as they're cmd.exe builtins), but I may be mistaken. I see now both `md` and `mkdir` are aliased to `cmd /c md` and `cmd /c mkdir` (same for `del`). Probably `mklink` should do the same.

In any case, my preference would be to have a unix-like experience on Windows, so I'm not having to context switch when changing platforms. I want to be able to run `rm -r` instead of `del /s /q` or `ln -s bar/foo` instead of `mklink /d foo bar\foo`.

One of the biggest advantages to xonsh is its broad platform support and potential to harmonize use cases across very different systems.

**Comment by certik** [comment]
This is a good point about just doing `rm -r` on Windows also. Even if the equivalent commands on Windows have less options than on Linux, for most of my use cases, the stripped down versions would work.

**Comment by TSN-ADMIN** [comment]
Dd

**Comment by gilch** [comment]
I personally use Cygwin, so I have the Unix-style utilities even in Xonsh. If your goal is portability, that's probably not good enough though.

There is a [Busybox port for Windows](https://github.com/rmyorston/busybox-w32) you could try. It's got a stripped-down version of all the basics in a single executable. It's under a megabyte, so you could distribute it with your script or even have them download it. It does include a `sh` command, but it should also work fine with Xonsh if you want the Python capabilities.

**Comment by tahir-hassan** [comment]
I personally thing that to provide a *nix style environment straight out of the box, you probably include cmdix or pycoreutils straight of the box for Windows, just so it is less confusing for them. 

Another idea would be to change `xonfig web` so that there is another tab for Windows users which checks for a git-bash installation, and offers to setup the aliases for it, for example, put:

```python
aliases["ls"] = [r"C:\Program Files (x86)\Git\usr\bin\ls.exe"]
```

in the `.xonshrc`.

**Comment by anki-code** [comment]
> aliases["ls"] = [r"C:\Program Files (x86)\Git\usr\bin\ls.exe"]

Nice alias. This is also works:
```python
aliases['ls'] = r"C:\Program Files\Git\bin\bash.exe -c ls"
```

**Comment by melund** [comment]
I can also recommend to add the core-utils to path when installing "Git for Windows". 

![image](https://user-images.githubusercontent.com/1038978/158570339-91806049-3a58-48e9-939b-04ca1aa042d7.png)

Then you get the full posix experience in xonsh on windows. 

Alternaltively, just add the path in xonsh: 

```
$PATH.append(r"C:\Program Files\Git\usr\bin")
```

**Comment by anki-code** [comment]
Thanks @melund ! It's a good point to put to the docs. Anyone PR is welcome!

**Comment by ljw20180420** [comment]
> I can also recommend to add the core-utils to path when installing "Git for Windows".
> 
> ![image](https://user-images.githubusercontent.com/1038978/158570339-91806049-3a58-48e9-939b-04ca1aa042d7.png)
> 
> Then you get the full posix experience in xonsh on windows.
> 
> Alternaltively, just add the path in xonsh:
> 
> ```
> $PATH.append(r"C:\Program Files\Git\usr\bin")
> ```

Hello. Is there a way to permanently add the path only in xonsh?
