### ISSUE TITLE
pipe from a function to the `more` command does hang (Windows)

### ISSUE THREAD

**Issue by andry81** [xonsh/xonsh#3187]
## config
`Windows x64 7`, `Python 3.7.3`, `xonsh/0.9.6`

## example
```
def pp(args):
  print(*args)

@(pp, 123) | more
@(pp, 123) | cmd.exe /c more
```

**Update:**
Seems any piping hangs with 3dparty executables, not just only the `more` command.

**Update 2:**
Another example of the hang with the `cmdix` module:
```
def pcall(args):
  args.pop(0)(*args)

import cmdix
@(pcall, print, 123) | @(cmdix.run, 'cat')
```

## Expected Behavior
print and exit

**Comment by scopatz** [comment]
Thanks for bringing this up @andry81.  I think this is because you are not using the correct form of a [callable alias](https://xon.sh/tutorial.html#callable-aliases). Namely you need one that writes to stdout.

```python
def pp(args, stdin=None, stdout=None):
  print(*args, file=stdout)

@(pp, 123) | more
```

seems to work for me

**Comment by andry81** [comment]
Another issue:
```
Command `MORE.EXE` not found.
```
And another:
```
@(pp, 123) | cmd.exe /c more
```
```
Traceback (most recent call last):
  File "c:\python\x64\37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python\x64\37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\Python\x64\37\Scripts\more.exe\__main__.py", line 9, in <module>
  File "c:\python\x64\37\lib\site-packages\cmdix\__init__.py", line 150, in run
    args.func(args)
  File "c:\python\x64\37\lib\site-packages\cmdix\command\more.py", line 22, in func
    for line, filename in lib.parsefilelist(args.FILE):
ValueError: not enough values to unpack (expected 2, got 1)
```
And this still hangs:
```
@(pp, 123) | @(cmdix.run, 'cat')
```

**Comment by andry81** [comment]
If that even works, then it means xonsh can lose the output because of the already existed code and there would be an issue around prints without `file=stdout` paramater, which is important when replacing shell code by a xonsh script.

**Comment by scopatz** [comment]
It seems like the command not found, `not enough values to unpack`, and cat hanging are all issues outside of xonsh, coming from either what is available on the system of cmdix. 

#3188 and #188 (duplicates?) and this issue all stem from not tying the stdout correctly.  When you use `@(func)` to *call* a function, that function is being called in a background thread with stdin, stdout, & stderr all redirected. This is so that users can easily write command pipelines. xonsh isn't losing output, it is just being redirected. Xonsh also redriects sys.stdout, etc so that tools like `print()` usually just work.  It is safer (and avoids race conditions) by passing in `file=stdout` explicitly.  With the `pcall` example above, you can pass in any arbitrary function, which doesn't necissarily print any output to the screen.  This was the case with `@(pcall, shutil.copyfile, 'd:/aaa', 'd:/bbb')` where `shutil.copyfile` **returns** a string, and does not **print** it. Because of this, that string is never sent to any stdout so there is no way for xonsh to know about it.

**Comment by andry81** [comment]
I understand why it does not work the way a user excpect it work.  I don't understand why the user have to change all the print functions in a 3dparty code to fix that. The python modules and libraries already would suggest the usual print and the usual print should be redirected by default if get a call under the `@(...)` operator or under stdout redirection. This is the way any user expect it to work like in the shell or not far away from it. The proposed method actually forces user to rewrite the code, this is not good.

**Comment by scopatz** [comment]
`shutil.copyfile` does not print.  Perhaps I am not understanding something here, but a user should not need to rewrite anything in a third party module

**Comment by andry81** [comment]
It does in a usual python way. It does not in the redirection example with the xonsh code.

**Comment by dotsdl** [comment]
@andry81, there seems to be a misunderstanding here. When the Python interpreter executes `shutil.copyfile`, this function returns the name of the file copied to. The name of the file is *not* printed. Try, for example, in any Python interpreter:
```
import shutil
result = shutil.copyfile('my_example_file', 'new_example_file')
```
No result is printed, because this function does not print. It does, however, return a value:
```
print(result)  # will print value `new_example_file`
```
Does this help? This is precisely the behavior that `xonsh` is showing if we run the same example there.

**Comment by andry81** [comment]
Yes. I thought the function has used a usual print which does not print anything to pipe by default.
