### ISSUE TITLE
Are we having a stable version soon

### ISSUE THREAD

**Issue by blueray453** [xonsh/xonsh#3232]
I am watching the releases for a long time now. The recent release I see is 0.9.9

Does it mean we are having a stable version soon?

**Comment by andry81** [comment]
I am wondering that too. But after a some research for the Windows i did found a bunch of issues which definitely nothing to do with stable. Actually this is quite a mess with the design and I even not sure would it be fixed (half of issues even not marked by anything and another issues just closed).

https://github.com/xonsh/xonsh/issues/created_by/andry81

**Comment by melund** [comment]
@andry81 It is really appreciated that you filed all the issues. I am sure it will eventually help make xonsh better on Windows. 

Keep in mind that not everything is possible on Windows so it will sometimes be a "best effort". You are also welcome to fix some of the issues your self if you can. It is really a community effort to build xonsh. 
Windows developers would very welcome since I guess most core devs are on Linux :)

**Comment by blueray453** [comment]
Windows people have Powershell (though Linux has it too), so I am not really worried about xonsh's windows support. But some of Linux users really need a real replacement for bash. I will gladly use a distribution that do not have bash and comes with xonsh by default. However, I am not sure whether 100% replacing bash is in xonsh's roadmap or not.

**Comment by scopatz** [comment]
@blueray453 - Yes, 1.0 is on the horizon.  I need to open a tracking issue for what needs to be done for that.  Help is always appreciated!

**Comment by scopatz** [comment]
Tracking issue is at #3234
