### ISSUE TITLE
FAQ(?): Recommended way to disentangle xonsh from venvs/conda envs

### ISSUE THREAD

**Issue by michaelaye** [xonsh/xonsh#3265]
My system:

macOS 10.14.5
homebrew

xonsh installed via homebrew.

Why? Because I want to disentangle xonsh from potentially variability in virtual/conda envs as mentioned in your FAQ 8. Or, more clearly, not all my envs have all packages, and xonsh obviously needs to be available all the time, if it would be the default shell.

However, I'd like to have some of my standard python packages available for xonsh, for example pandas or astropy with some important time converters or other fancy utils.
How should I go about this? Can I somehow install Python packages into the space where-ever  xonsh is running? Is that the best / recommended way to do this?

At the moment, I only have built-in packages available, and if I try to import pandas, I get a ModuleNotFoundError.

Alternatively, is it somehow possible to have `xonsh` pick up the modules available from the currently active environment? How would I configure that?

Thanks for creating xonsh, it's fun!

**Comment by gforsyth** [comment]
> Can I somehow install Python packages into the space where-ever xonsh is running? Is that the best / recommended way to do this?

Hey @michaelaye -- there's an alias called `xpip` that we include that behaves exactly like `pip` but will ensure that anything you install is available to `xonsh`.  There isn't a built-in way to do this with `conda`, except to install `xonsh` in an environment and then `conda install` packages into that environment.

`brew` sandboxes things by design, so if you're starting from there, I think `xpip` is probably your best bet.

> Alternatively, is it somehow possible to have `xonsh` pick up the modules available from the currently active environment? How would I configure that?

We've talked about this, because it would be awesome, but it is _very_ complicated and would probably break in spectacular ways.



> Thanks for creating xonsh, it's fun!

:tada: thanks!

**Comment by scopatz** [comment]
A PR to put this on the FAQ would be awesome!

**Comment by michaelaye** [comment]
before i do that, why is the FAQ so darn hard to find? Not listed here: https://xon.sh/sidebar.html and not findable by search. I even don't know how I got to it and can't find the click-path I used to find it anymore...

**Comment by scopatz** [comment]
haha also accepting fixes to the index
