### ISSUE TITLE
Feature request: Add an alias cs 

### ISSUE THREAD

**Issue by dclong** [xonsh/xonsh#3321]
To change to a directory and list its content. It is basically `cd` and then `ls`. The reason is that I found over 90% of the times that I `cd` into a directory, I run `ls` to see what's there (even if sometimes I'm with contents in the directory). Other users might have beening repeating this pattern too. With the `cs` alias introduced, users can be a little bit more efficient using xonsh shell.

**Comment by astronouth7303** [comment]
Toss this in your `.xonshrc`:

```
def _cs(args): 
     cd @(args) 
     ls 
                                                                            
aliases['cs'] = _cs
```

I am extremely hesitant to add two-letter aliases to primary xonsh, just because of the chance of name collisions. I consider you lucky that `cs` doesn't seem to conflict with anything. (We've had this problem in the past--`xpip` used to be `xip`, but that's a Mac signed zip and the program to manipulate them.)

**Comment by scopatz** [comment]
Thanks for the suggestion @dclong! I think that this is something that can easily go into the xonshrc, though
