### ISSUE TITLE
`echo $('...')` prints a text with the quotes

### ISSUE THREAD

**Issue by andry81** [xonsh/xonsh#3339]
## xonfig

<details>

```
+------------------+-----------------------------------------------+
| xonsh            | 0.9.11                                        |
| Git SHA          | dd16d59d                                      |
| Commit Date      | Aug 25 13:21:16 2019                          |
| Python           | 3.7.4                                         |
| PLY              | 3.11                                          |
| have readline    | False                                         |
| prompt toolkit   | 2.0.10                                        |
| shell type       | prompt_toolkit2                               |
| pygments         | None                                          |
| on posix         | False                                         |
| on linux         | False                                         |
| on darwin        | False                                         |
| on windows       | True                                          |
| on cygwin        | <xonsh.lazyasd.LazyBool object at 0x025E2F30> |
| on msys2         | <xonsh.lazyasd.LazyBool object at 0x025EB070> |
| is superuser     | False                                         |
| default encoding | utf-8                                         |
| xonsh encoding   | utf-8                                         |
| encoding errors  | surrogateescape                               |
+------------------+-----------------------------------------------+
```

</details>

## Expected Behavior
the exact text string

## Current Behavior
text string with the quotes added

## Steps to Reproduce
```
echo @('hello world')
```

**Comment by astronouth7303** [comment]
I cannot reproduce.

What is the result of `which echo`?

**Comment by andry81** [comment]
```
"hellow world"
```

**Comment by melund** [comment]
No. The `which echo` command will tell you what "echo" you are using.

**Comment by andry81** [comment]
So, you are saying what the echo is not relaible? I don't quite understand how to fix that.

**Comment by melund** [comment]
https://en.m.wikipedia.org/wiki/Which_(command)

**Comment by melund** [comment]
Thanks for updating your last answer https://github.com/xonsh/xonsh/issues/3339#issuecomment-538638979 

There may have been some changes in the way "source-cmd" works, which is why calling "cmd"'s echo appear to behave differently. I don't think it always did this. And I can indeed reproduce your result if I change my echo alias.

But that is the reason why xonsh now has its own built in version of echo. Make sure you don't overwrite the "echo" alias in your `.xonshrc` file and the should just pick up the built in echo.

**Comment by melund** [comment]
No, actually it has always been like this. `cmd.exe`'s `echo` doesn't strip strings either: 

![image](https://user-images.githubusercontent.com/1038978/66257945-a4ab0b00-e79f-11e9-963d-e66417dae719.png)

I think this issue can be closed.

**Comment by scopatz** [comment]
Thanks for hunting this down @melund!

**Comment by andry81** [comment]
> I think this issue can be closed.
How to fix that?

**Comment by melund** [comment]
@andry81. As I wrote; look in your .xonshrc file, and see if you have any alias that overwrite the built-in echo. I expect you have a line like this:
```
aliases["echo"] = "cmd.exe /c echo"
```

**Comment by andry81** [comment]
I could not found `.xonshrc` on Windows. And if has, what to place there? Do I need to install the separate `echo.exe` executable? Whould it be compatible with the xonsh?

**Comment by melund** [comment]
@andry81 You really should read the documentation and the tutorial. But you are right to be a bit confused. I forgot that the built in `echo` function, is not enabled by default.

It is a separate add-on (xontrib) which needs to be explicitly enabled. @scopatz Maybe it really should be default on Windows, since the Windows lacks many of the coreutils and the since its 'echo' works so differently.  

> Do I need to install the separate echo.exe executable? Why not to map it to simple print function internally?

Well you can install a seperate 'echo' tool For example the unix-tools from the "git for windows" packages. But xonsh own 'echo' function is basically just mapping to print, so it is faster. 

You can find your [run control file](https://xon.sh/xonshrc.html) here: `~/.xonshrc`. Open that file and add the following line: 

```
xontrib load coreutils
```
That will activate the coreutils extension.

**Comment by andry81** [comment]
> You really should read the documentation and the tutorial.

I didn't found any reference to `xontrib` from the tutorial: https://xon.sh/tutorial.html

Actually even `Windows install` section from the online documentation does not mention a requirement of the `xontrib` to install and relation to the `echo` or other builtin command: https://xon.sh/windows.html

So this is a bit hard to find.

> That will activate the coreutils extension.

thx!

**Comment by scopatz** [comment]
Yeah, sorry, the docs for this are at https://xon.sh/xontribs.html#coreutils  The docs could be better here.  PRs welcome!
