### ISSUE TITLE
[Documentation/Screenshots]

### ISSUE THREAD

**Issue by rubyFeedback** [xonsh/xonsh#3340]
First - great work with the homepage, lots of detailed information + tutorials as well.

Now for this issue request:

Would it be possible to add 1-3 screenshots of the shell in action? Does not matter if it is boring (although ideally it should be great); this is just to get an overview for people (like me) not familiar with xonsh. At any rate please do feel free to close this issue request at any moment in time.

**Comment by scopatz** [comment]
Thanks @rubyFeedback! Yeah this is a great idea!

**Comment by astronouth7303** [comment]
Didn't we use to have an interactive tutorial?

**Comment by melund** [comment]
Yes. An asciinema demo, which I thought was really great. I agree with @rubyFeedback, we really need something on the webpage.

The problem with the asciinema demo, was that it was hard to update when xonsh changed. I have looking for some ghost typing software so it could be scripted but with no luck. 

But maybe xonsh is stable enough to attempt a new asciinema demo manually. But shouldn't be me. I am not fast enough on a keyboard.

**Comment by anki-code** [comment]
I believe that any gif/asciinema/ghosttyping animation on the landing page is frustrating because you can't stop it or if you can you should move backward or forward to understand what it shows.

The screenshots is better but the best is copy-pastable commands with syntax highlighting. You can see this, understand and copy.

I suggest the new langing page concept here - https://github.com/xonsh/xonsh/issues/3706#issuecomment-738913669
