### ISSUE TITLE
How to running script with rc in command line?

### ISSUE THREAD

**Issue by anki-code** [xonsh/xonsh#3374]
Hello! Thank you for great shell!

I think there is a confusing xonsh command line order that do unexpected result. In `xonsh --help` we see:
```
# xonsh --help
usage: xonsh [-h] [-V] [-c COMMAND] [-i] [-l] [--config-path CONFIG_PATH]
             [--rc RC [RC ...]] [--no-rc] [--no-script-cache]
...
             [script-file] ...

positional arguments:
  script-file           If present, execute the script in script-file and exit

  --rc RC [RC ...]      The xonshrc files to load, these may be either xonsh
                        files or JSON-based static configuration files.
```

I want to run script with `--rc` and I write:
```
bash$ xonsh --rc rc1.xsh script.xsh
```
Here we see ambiguity. What will happen? Load rc, script run and we return to bash? Or load xonsh with two rc scripts?

I need to just run script after rc loading but no:
```
bash$ xonsh --rc rc1.xsh script.xsh
rc1 load
script load
xonsh> # we are in xonsh now instead of running rc, then script and return to bash
```

How to just run script with rc and exiting like `xonsh script.xsh` works?

I also tried several combinations around `xonsh --rc rc.xsh -c "xonsh script.xsh"` but it's not working and I can't get env variables from `rc.zsh` in `script.xsh`.

I also tried to hack arguments order and run `xonsh --rc rc.xsh -DFAKE=1 script.xsh` and `xonsh --rc="rc.xsh" script.xsh` but as result there are no code and env variables from `rc.xsh` in `script.zsh`. RC just was not loaded. What the hell! 

Please help workaround and run script with rc exactly as `xonsh script.zsh` works? What I'm doing wrong?

***

I suppose this issue also disable the ability to run the code over ssh. If you try:
```
echo "xonsh --rc rc.xsh script.xsh" | ssh server -T "bash -s"
```
You will get nothing and no files was executed on the server. I don't understand why but `xonsh script.xsh` works as expected in command above but with `--rc` I've got total silence. So I think the cause in the first part of this issue.

***

Current workaround:
1. Rename rc file to valid name for python import and with `xsh` extension and place it along with `script.xsh`. Example `rcfile.xsh` in `/path`.
2. `import rcfile` directly in `script.xsh`
3. Run `cd /path && xonsh script.xsh`

**Comment by anki-code** [comment]
Current workaround:
1. Rename rc file to valid name for python import and with `xsh` extension and place it along with `script.xsh`. Example `rcfile.xsh` in `/path`.
2. Import directly `import rcfile` in `script.xsh`
3. Run `cd /path && xonsh script.xsh`

**Comment by gforsyth** [comment]
Hey @anki-code -- thanks for reporting this!  I agree the multiple RC file option leads to ambiguous behavior.  Here are a few examples and the behavior that comes from them:

```console
$ cat test.xsh 
echo $HI_THERE
$ cat rctest.xsh 
$HI_THERE='hello'
```

(note I'm starting at a `bash` prompt)

if I run

```console
$ xonsh --rc rctest.xsh test.xsh
```

I observe the same problem as you reported, which is that both `rctest.xsh` and `test.xsh` are loaded as `rc` files and `xonsh` starts (and doesn't exit).  This ambiguous behavior is something we can try to change, but it's a _bit_ tricky to do while supporting multiple rc files.

You can use a `--` to explicitly break up a command to `argparse` so you can do

```console
$ xonsh --rc rctest.xsh -- test.xsh
$HI_THERE
```

which drops back to a `bash` shell, but doesn't work.  

That's because rc files are only loaded in interactive mode, so you also need to add an `-i`:

```
$ xonsh -i --rc rctest.xsh -- test.xsh
hello
```

This works and drops back to `bash` after executing.  I hope that helps as a workaround and we can try to think of ways to make the behavior a little more intuitive.

**Comment by anki-code** [comment]
@gforsyth it works! Many thanks!

**Comment by anki-code** [comment]
@gforsyth could you please help me with the similar question:
```
$ echo "qwe=123" > xonshrc
$ xonsh -i --rc xonshrc -c "print(qwe)"
NameError: name 'qwe' is not defined
```
Why it is not working? I expected 123 as result.
