### ISSUE TITLE
Question: How to make environment variables prefix aliases and not break completion

### ISSUE THREAD

**Issue by h0cheung** [xonsh/xonsh#3395]
I tried simple add 
`aliases['primerun'] = "env __NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME=nvidia __VK_LAYER_NV_optimus=NVIDIA_only VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/nvidia_icd.json "`
It works but:
1. The completion is broken, after typing primerun, when I press Tab, it only give me files.
2. If I use primerun without other commands, it will print all variables.
Is there a better way to solve these? Especially the first one.

**Comment by gforsyth** [comment]
Hey @Howard-00 -- sorry for the delay in getting to this.  

Where are the completions for `primerun` coming from in the first place?  Do you have a command called `primerun` that normally has functional completions?

As an example, I alias `cat` to `bat`, but I still get `cat` completions when I do `cat <TAB>` (which is the expected behavior)

**Comment by Howard-00** [comment]
> Hey @Howard-00 -- sorry for the delay in getting to this.
> 
> Where are the completions for `primerun` coming from in the first place? Do you have a command called `primerun` that normally has functional completions?
> 
> As an example, I alias `cat` to `bat`, but I still get `cat` completions when I do `cat <TAB>` (which is the expected behavior)

`env` and some environment variables. It seems that the completion cannot handle `env` command.
Is there a better way to create an alias to run a command with some specific environment variables and not break the completion?
