### ISSUE TITLE
Any way to force saving of history?

### ISSUE THREAD

**Issue by beetleb** [xonsh/xonsh#3442]
At work I run xonsh in an environment where, for reasons I haven't figured out, xonsh crashes often. I can live with this, but my problem is I often lose the history of the crashed session.

Is there a command where I can force the current xonsh shell to write its history? 

(My assumption is that history is mostly preserved if you manually exit the shell).

**Comment by laloch** [comment]
Hi @beetleb, you can forcibly flush the history by running
```
$ __xonsh__.history.flush().join()
```
I would, however, like to investigate the crashes. Do you have any pointers?

**Comment by beetleb** [comment]
I haven't noticed a pattern. It works (mostly) fine on my home machine, but at work it crashes much more often. Do note that a *lot* of libraries at work were hand installed by me (i.e. not from the package manager as I don't have root access). So it's not the most stable environment.

What should I do whenever it crashes. Are there log files somewhere?

**Comment by beetleb** [comment]
As an example, I ran 

`` __xonsh__.history.flush().join()``

on all open shells on my work machine and one of them hung on that command. 

It would be great if we could debug it, but I suspect it's more a problem of the environment than with xonsh.

**Comment by anki-code** [comment]
We have two history backends: json (default) and [sqlite](https://xon.sh/tutorial_hist.html#sqlite-history-backend).

Personally I recommend to use [sqlite backend](https://xon.sh/tutorial_hist.html#sqlite-history-backend) because it saves the commands immediately after execution. Just add to your `~/.xonshrc`:
```python
$XONSH_HISTORY_BACKEND = 'sqlite'
```

In case of using json history backend there is a command:
```python
history flush
```
