### ISSUE TITLE
/etc/profile.d/ scripts are not sourced

### ISSUE THREAD

**Issue by qwenger** [xonsh/xonsh#3579]
I am not sure whether this is a bug or a feature, but it seems that scripts under /etc/profile.d/ (archlinux here) are not sourced by xonsh, in contrast to what bash or zsh do, for example.

This means that e.g. some paths are not set (in my case, perl and cuda among others), and more importantly that locales are not configured (this is not only about $LANG but all the $LC_*, as set in the locale.conf's).

Of course there are workarounds, like directly taking care of such configuration in .xonshrc (but then if the package manager changes profile.d, it won't be updated) or source-bash'ing the files in .xonshrc...

**Comment by astronouth7303** [comment]
I think this is semi-deliberate, because xonsh is not a bourne or posix shell.

Note that on my system (debian testing), `/etc/profile.d` is not a direct feature but is handled by `/etc/profile`.

There is a reasonable argument to be made that xonsh should do something similar, with a sample `/etc/xonshrc`. Of course, actually shipping this gets into the quagmire of distribution (in which xonsh supports all the things), and the exact circumstances when xonshrc is read (bourne shells have two sets of startup scripts for unconditional vs probably-human, whereas xonsh only has one).

**Comment by qwenger** [comment]
You're right about /etc/profile.d/* being sourced through /etc/profile, this is standard.
However here at least source-bash'ing /etc/profile from xonsh gives "Source failed", "File not found or syntax error".

I also see that some *.csh are present in /etc/profile.d/, which indicates that at least some packages recognize that bourne shells are not alone in this world. :-) (see also https://unix.stackexchange.com/a/541585 on that matter)

**Comment by jnoortheen** [comment]
Xonsh now source files from '/etc/xonshrc'
