### ISSUE TITLE
Question: Can I change the keybinding alt+backspace to ctrl+backspace ? if yes how ?

### ISSUE THREAD

**Issue by vksdev** [xonsh/xonsh#3645]
## xonfig

```
+------------------+-----------------+
| xonsh            | 0.9.18          |
| Python           | 3.7.7           |
| PLY              | 3.11            |
| have readline    | True            |
| prompt toolkit   | 3.0.5           |
| shell type       | prompt_toolkit  |
| pygments         | 2.6.1           |
| on posix         | False           |
| on linux         | False           |
| on darwin        | False           |
| on windows       | True            |
| on cygwin        | False           |
| on msys2         | False           |
| is superuser     | False           |
| default encoding | utf-8           |
| xonsh encoding   | utf-8           |
| encoding errors  | surrogateescape |
+------------------+-----------------+
```

**Comment by scopatz** [comment]
Please see https://xon.sh/tutorial_ptk.html

**Comment by vksdev** [comment]
I have read some of that and some of [https://python-prompt-toolkit.readthedocs.io/en/master/pages/advanced_topics/key_bindings.html](url) . It says `c-h` is alias for Backspace but there is no alias for `c-Backspace`. `c-c-h` don't work.
As far as I understand ctrl+backspace can not be used as custom keybinding.
I thing it is really annoying for people coming from cmd or powershell on windows to xonsh and find ctrl+backspace do not work. Should it be default on windows?

**Comment by laloch** [comment]
> It says c-h is alias for Backspace but there is no alias for c-Backspace. c-c-h don't work.
As far as I understand ctrl+backspace can not be used as custom keybinding.

No, it doesn't work and it cannot be used, because VT100 terminal and its emulators don't generate any special keyboard code for <kbd>Ctrl</kbd>+<kbd>Backspace</kbd>. The key combo simply doesn't exist and should be ignored by VT100-compatible terminal emulators. Modern terminal emulators, such as Konsole depicted on the screenshot below, allow for customization of the terminal keymap, so you can most probably set your terminal up to generate some unique key code and handle it in PTK. It will, however, never be a standard keyboard shortcut in any cross-platform CLI application.

Btw, you can't use <kbd>Ctrl</kbd>+<kbd>Shift</kbd> keyboard shortcuts either for the very same reason.
![Screenshot_20200727_132131](https://user-images.githubusercontent.com/1336917/88536773-b00c4300-d00c-11ea-8d76-9d6f590c2422.png)

**Comment by vksdev** [comment]
Ok, I understand. thank you.
