### ISSUE TITLE
Env var dict lookup in f-string not working

### ISSUE THREAD

**Issue by sevens-ef** [xonsh/xonsh#3655]
Looks related to #3572, #3454 and possibly #3611 but different enough that I think it warrants a separate bug report.

It's possible to use env vars in f-strings, dict lookups in f-strings but using dict lookups of an env var doesn't seem to work.

E.g.:

```
$  $foo = 'foo'
$  f"{$foo}"  # Env var, works
'foo'
$  bar = {'bar': 3}
$  f"{bar['bar']}"  # Dict lookup, works
'3'
$  $bar = bar
$  f"{$bar['bar']}"  # Dict lookup of env var, doesn't work
$  # NOTE: it shows nothing, not even an empty string
```

Also using `f"{$bar.get('bar')}"` as a work-around doesn't work (though `f"{$bar.get}"` *does* show some output).

## xonfig

<details>

```
$ xonfig
+------------------+---------------------+
| xonsh            | 0.9.18              |
| Git SHA          | 26475146            |
| Commit Date      | May 5 06:42:28 2020 |
| Python           | 3.6.9               |
| PLY              | 3.11                |
| have readline    | True                |
| prompt toolkit   | 2.0.10              |
| shell type       | prompt_toolkit      |
| pygments         | 2.6.1               |
| on posix         | True                |
| on linux         | True                |
| distro           | ubuntu              |
| on darwin        | False               |
| on windows       | False               |
| on cygwin        | False               |
| on msys2         | False               |
| is superuser     | False               |
| default encoding | utf-8               |
| xonsh encoding   | utf-8               |
| encoding errors  | surrogateescape     |
+------------------+---------------------+
```

</details>

## Expected Behavior

```
$  $bar = {'bar': 3}
$  f"{$bar['bar']}"
'3'
$  f"{$bar.get('bar')}"
'3'
$  baz = f"{$bar['bar']}"
$  type(baz)
str
```

## Current Behavior

```
$  $bar = {'bar': 3}
$  f"{$bar['bar']}"
$  f"{$bar.get('bar')}"
$  baz = f"{$bar['bar']}"
$  type(baz)
...
NameError: name 'baz' is not defined
```

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by scopatz** [comment]
I think the issue is that we are piping the contents of the f-str vars into the Python evaluator, rather than the xonsh one

**Comment by laloch** [comment]
The problem in general is that we don't have f-strings parser. We rely on `string.Formatter` instead which is not optimal, because it can only understand classic `str` format specifiers, but not f-string fields. Those are quite similar, but not the same and we cannot alter the behavior, since `Formatter` is a CType.

**Comment by scopatz** [comment]
Ooof, I am not sure I have the ability to fix it before 1.0. It would be a API stable change anyway.  PRs very welcome!

**Comment by scopatz** [comment]
Also, I am trying to push a lot on 1.0 right now - if folks hadn't noticed :wink:

**Comment by scopatz** [comment]
Just to be clear, I am willing to have 1.0 wait on this (it will take a few weeks anyway), if someone is actively working on it

**Comment by laloch** [comment]
I already tried once. Then I realized that it's non-trivial (it's essentially a mini-language with possibly nested f-strings) and I gave up :(

**Comment by scopatz** [comment]
Yeah.... it is not easy

**Comment by laloch** [comment]
So I tried a different approach tonight: Instead of trying to proactively parse and patch the f-strings, I'm now trying to parse the f-string using `ast.parse` and if that fails with `SyntaxError` only then I patch the f-string with `__xonsh__.execer.eval`. It works much better than the current implementation. I can even successfully evaluate things like `f'foo {$HOME!s:{a}.{b}} {${"P"+"WD"}} bar'`. I did, however, already hit the wall. The f-strings are not allowed to contain backslashes within the expression clause. That alone makes patching of nested f-strings (`f"{f'{$HOME}'}"`) impossible. It's a showstopper. We need to find completely different approach to handling f-strings, probably by temporarily replacing the xonsh-specific syntax by some syntactically acceptable dummy construct and patching the resulting AST.
