### ISSUE TITLE
Recommended configuration for using conda and xonsh

### ISSUE THREAD

**Issue by wshanks** [xonsh/xonsh#3734]
I have been trying to work with `conda` inside of `xonsh` and have some questions about recommended workflow. I don't know that these questions require any changes to `xonsh`, but perhaps they could lead to some more documentation. First I would like to hear if other users of `conda` and `xonsh` encounter similar issues.

1. To get set up, I ran `conda init xonsh` which uses the output of `conda shell.xonsh hook` to dynamically generate a xontrib that sets up an alias and completer for `conda`. The xontrib imports `conda` and crashes the shell if this import fails. I think this means that to use `xonsh` and `conda` together one must install `xonsh` into the base `conda` environment. Is that right? And should that be documented somewhere?

2. When `conda activate` is called, it uses `source-bash` to source the activation scripts for the environment. I do use `bash` as well and have somewhat complex bashrc file. I have tried to isolate `xonsh` as much as I can from `bash`, so the `source-bash` call is not ideal but I see that getting every conda package to include xonsh activation scripts will be tough. What I have done is put `$XONSH_IS_PARENT = 1` into .xonshrc file and `if [ -n "${XONSH_IS_PARENT}" ]; then return fi` at the top of my .bashrc file to keep `xonsh` from pulling in things from my .bashrc. Is there any better way to isolate `xonsh` from the `bash`?

3. Even with my modification to .bashrc above, I still get some unwanted changes to my `xonsh` environment when I run `conda activate`. Namely, I end up with `$SHLVL = 2` instead of `$SHLVL = 0` and I end up with `$SHELL = /bin/bash` instead of `$SHELL = $HOME/conda/bin/xonsh` because `source-bash` is pulling these values out of the `conda` activation script's environment. Is there any way to avoid these changes? I was using `$SHELL` to tell things like `tmux` which shell to launch (`tmux` checks `$SHELL` by default but I think I can use configuration settings to make it use something else).

4. Is it possible for `.xonshrc` to know which `xonsh` binary launched it? I would like to use that to set `$SHELL`. Right now I am doing `$SHELL = $(which xonsh)` but relies on the `conda init` code being run first. It would be nice to be able to set it in a way that worked whether or not I was initializing `conda` in .xonshrc.

**Comment by bobhy** [comment]
Hi @willsALMANJ, this sounds like a meaty issue.  Could you clarify the question a bit, in the style of Stack Overflow?  Please explain  what your desired outcome would be, what you do and do not want  to inherit from bashrc in your xonsh/conda environment. 
 Maybe we can offer alternative tactics for getting there.  

Re item 4, maybe this in your .xonshrc will work better?

```
import sys
$SHELL = sys.executable
```

**Comment by willsALMANJ** [comment]
Thanks for the response, @bobhy. Regarding Stack Overflow, I was attempting to go with something along those lines by grouping these little issues together here instead making them all separate in case I was going down wrong paths for all of them.

My goal is to get an experience with conda in xonsh that mirrors what I have in bash. One specific negative with the default behavior was that I was getting lots of warnings of conflicting aliases from bashrc when I activated a conda environment. Since I think of my bash and xonsh configurations separately, I don't really want anything in bashrc affecting xonsh, though perhaps there are subtleties I haven't thought of and xonsh needs access to some things set by bashrc? Also, I thought the crash when I had installed xonsh outside of the conda base environment was disconcerting -- it always feels bad when your shell crashes.

Having experimented for a few more days, I think I might have a better understanding of how things work now relative to how I would like them to work. Here are some possible code changes and changes in my local configuration to address the discrepancies:

1. Update conda.xsh in the conda repo so that it does not crash if it can not import conda. The import is only used for tab completing environment names now. It could just give no names if the import fails instead of crashing (or possibly fall back to getting the environment names from a conda subprocess which would be slower than the import but work from any Python environment).
2. In my .xonshrc, I have `aliases["source-bash"] = ["source-foreign", "bash", "--sourcer=source", "--extra-args=--norc"]` to prevent xonsh from pulling settings out of my bashrc when activating conda environments. I wonder if `--no-rc` should be the default or at least the default for the `conda activate` wrappers?
3. With 2, I see no change to my environment after activating and deactivating a conda environment except that `$SHLVL` gets bumped from 0 to 2. I don't know how important this is, but I wonder if `source-bash` should special case `$SHLVL` and not pull it back into the parent environment.
4. `sys.executable` gives me the path to `python` rather than the path to `xonsh`. However, I found that `sys.argv[0]` gives me the path to `xonsh`.

I was thinking before about documenting that xonsh needed to be in the base environment but my suggestions in 1 would allow xonsh to be installed outside of the base environment.

**Comment by anki-code** [comment]
I prefer to close this issue because there is many questions without repeatable examples and workarounds. If we will discuss it here this thread will be the unreadable mix around many issues. If you still want to solve some issues please create separate issues with step by step examples to repeat (the best way is to using docker container).

**Comment by wshanks** [comment]
Fair enough. The point of this issue was to try to hear from someone else using xonsh and conda together how they do it. The specific issues mentioned were examples of problems I ran into when trying to use xonsh and conda together. My feeling was that I was missing some assumptions that went into the writing of the xonsh hook for conda. If anything were to come out of this issue, it would be adding a section to the documentation on how to use xonsh and conda together rather than a fix for a particular bug.

**Comment by anki-code** [comment]
I'm using conda with xonsh on Arch for simple use cases and I'm not facing with issues. One thing I've fixed is `conda init` time: I put the `conda init` code to `bashrc` and run xonsh as `/bin/bash -i -c xonsh` then `conda init` working much faster in `bashrc` than in `xonshrc`.

The new page in the documentation is very welcome!
