### ISSUE TITLE
unexpected behavior with subprocess mode and environment variables

### ISSUE THREAD

**Issue by zardus** [xonsh/xonsh#385]
I might be misunderstanding how env variable expansion works, but it seems to me that something is not being parsed correctly:

```
yans@lath ~ master $ $ASDF = '/usr'
yans@lath ~ master $ echo $ASDF
/usr
yans@lath ~ master $ ls $ASDF
aarch64-linux-gnu    bin             include         mips-linux-gnu       powerpc64le-linux-gnu  sparc64-linux-gnu
alpha-linux-gnu      cris-linux-gnu  lib             mips64-linux-gnu     s390-linux-gnu         src
arm-linux-gnu        games           lib32           msp430               sbin                   vax-linux-gnu
arm-linux-gnueabi    hppa-linux-gnu  libx32          msp430-linux-gnu     sh-linux-gnu           x86_64-linux-gnu
arm-linux-gnueabihf  i386-linux-gnu  local           powerpc-linux-gnu    share                  xscale-linux-gnu
avr-linux-gnu        ia64-linux-gnu  m68k-linux-gnu  powerpc64-linux-gnu  sparc-linux-gnu
yans@lath ~ master $ ls $ASDF/bin
.................... 
```

The expected result, as far as I can tell, is for xonsh to execute `ls /usr/bin` in subprocess mode, but it seems to want more input. I thought that this was maybe due to `ls` being an alias, but it doesn't look like it:

```
yans@lath ~ master $ del aliases['ls']
yans@lath ~ master $ ls $ASDF/bin
.................... 
```

BTW, I also tried quoting the string:

```
yans@lath ~ master $ ls "$ASDF"/bin
/bin/ls: cannot access "$ASDF"/bin: No such file or directory
```

It looks like it did run this in subprocess mode, but without expanding the variable...

Am I missing something?

**Comment by scopatz** [comment]
Hi @zardus - first off, sorry for the delay in responding.  (I am in the middle of proposal season at work and have been turning email off to get my writing done.)

Secondly, this seems like a bug or deficiency.  It should be fixed.  For the moment, you can get around this via the rather hackey:

```python
$ ls @($ASDF + "/bin")
```

Not satisfying, I know.  If you want to take a stab at fixing this, I'd really appreciate it.  The basic problem is that `os.expandvars` is not being run on every command argument that it could be / should be.  That would be one way to implement this. Another might be to give the $NAME operation the highest precedence in the parser. 

If you come up with a fix, I'll gladly merge it. Otherwise it might have to wait until I find a free moment.

**Comment by zardus** [comment]
I'll try to find some time to look into this. Thanks for the pointers!

**Comment by scopatz** [comment]
Great, thanks!

**Comment by scopatz** [comment]
Yup this is a duplicate.

**Comment by laerus** [comment]
this is fixed on current master, feel free to reopen!
