### ISSUE TITLE
Windows 10 WSL2: fast from root, slow from user

### ISSUE THREAD

**Issue by anki-code** [xonsh/xonsh#3895]
Hi! xonsh is the best! Thanks!

I've made a try to run xonsh on Windows 10 WSL2 Ubuntu 20 and found that it works fast from root but slow from user.

Asciinema - https://asciinema.org/a/bFZb6nmH7bZSWq57VkQCfB0LQ

Screenshots:

<details>

Run from user:

![image](https://user-images.githubusercontent.com/1708680/96334426-7da53b80-1079-11eb-82b1-92fae97e1a49.png)

![image](https://user-images.githubusercontent.com/1708680/96334447-96adec80-1079-11eb-8af8-b2e42e8af5a3.png)

Run from root:

![image](https://user-images.githubusercontent.com/1708680/96334463-aaf1e980-1079-11eb-9d43-6f62443dd5c6.png)

</details>

In the Linux and WSL1 xonsh works perfect for me.

May be it's WSL2 problem. Any thought how to debug/fix it are very welcome.

Thanks!

**Comment by scopatz** [comment]
Thanks for reporting @anki-code! Can you start xonsh with the `--timings` flag, ie `xonsh --timings` for both WSL1 & WSL2 so that we can start tracking down where the slowdown is coming from? Thanks!

**Comment by anki-code** [comment]
Timing wasn't help. But I dive into the code and found the cause.

In WSL2 user has very rich PATH (by default!) with many directories with huge amount of files i.e. `/mnt/c/Windows/system32` with many subdirectories.

But root user has empty PATH (by default).

As result the call stack looks like:

1. PTK do `prompt_formatter` with `{env_name}{BOLD_GREEN}{user}@{hostname}{BOLD_BLUE} {cwd}{branch_color}{curr_branch: {}}{RESET} {BOLD_BLUE}{prompt_end}{RESET}`
2. call `branch_color`
3. call `__xonsh__.commands_cache`
4. call `locate_binary`
5. call `__xonsh__.commands_cache.all_commands` that get ALL 18,222 (!) files from PATH directories and it takes around 5-10 seconds.

**Comment by scopatz** [comment]
Oh wow! That is bad... Maybe on WSL2 you can set the PATH to be something reasonable in the xonshrc

**Comment by anki-code** [comment]
The solution - https://github.com/microsoft/WSL/issues/1493#issuecomment-580643734

**Comment by scopatz** [comment]
Ahh cool.  It would be nice to detect if this was happening and issue a warning with the fix then.

**Comment by daddycocoaman** [comment]
Sorry to necro this but wanted to add something. In case a user doesn't want to throw away the whole Windows path away in WSL2, they can add this to `~/.xonsh.rc` 

`[$PATH.remove(path) for path in $PATH.paths if path.startswith("/mnt/c/")]`

This won't speed up the start time for xonsh because the Windows paths will still be loaded but xonsh will run as expected after. Hope this helps anyone passing through.

**Comment by KoStard** [comment]
I feel like this should be included by default for WSL clients. It is a quite bumpy first impression otherwise.

**Comment by kodjac** [comment]
> I feel like this should be included by default for WSL clients. It is a quite bumpy first impression otherwise.

This is 100% true, I was 1 minute away from ditching the whole xonsh experiment because it was just soooooo slow.

**Comment by NotTheDr01ds** [comment]
Just trying out Xonsh under WSL and came across this.

> Maybe we should load the commands_cache a-synchronically? Or at least in a different thread @daniel-shimon

Coming at it from the WSL-angle, this may be the only real "solution" rather than "workaround".

Removing Windows paths from WSL is a bit crippling for many WSL use-cases.  For example(s), without the Windows path being appended to the WSL2 path, the following doesn't work by default:

* Running VSCode via `code`
* Access to the `wsl.exe` command itself
* Ability to run PowerShell scripts inside WSL using `pwsh.exe` or `powershell.exe`
* And many others

Each of these could be manually run/configured by using the fully qualified path, but ... ugh.  It would also be possible to alias most commonly used commands, but that would have to be done for every Windows command you want to use in WSL/Xonsh.

Additional observations:

* This isn't the only performance related issue caused by the Windows paths.  Running with `prompt-toolkit`, entry is very slow.  I'm assuming there's some lookup happening in the prompt that is going cross-filesystem.

* Putting blame where blame is due, the core issue here is likely the poor performance of the Plan9 network filesystem that WSL2 uses to interface between WSL and WIndows filesystems.  This is a known issue on the WSL2, and I keep hoping that it's next on the list of things the WSL team is going to address.  But ... we wait.

  I can't say for certain that this will resolve the Xonsh issues, but I have to assume so.

**Comment by jaraco** [comment]
Today I spent a little time looking into this issue. I first struggled to get a WSL instance running due to [WSL 2 being non-viable in a UTM VM](https://github.com/utmapp/UTM/discussions/4652). I only managed to get Ubuntu running using WSL 1, but I can see from the OP that the issue is isolated to WSL 2.

> In Linux and WSL1 xonsh works perfect for me.

Interestingly, even on WSL 1, the commands cache still gets populated with all the "executable" files from system32:

```
jaraco@bulletproof /mnt/c/Users/jaraco @ len(__xonsh__.commands_cache.all_commands)
5867
```

So it's not the case that xonsh itself is not performant, confirming the suspicion:

> the core issue here is likely the poor performance of the Plan9 network filesystem that WSL2 uses

It occurs to me that another place where the blame could be placed is on the "executable" bit as reflected on this mounted filesystem. Linux thinks every file is executable.

```
jaraco@bulletproof ~ @ ls -l /mnt/c/DumpStack.log
-rwxrwxrwx 1 jaraco jaraco 12288 Jan 26 10:07 /mnt/c/DumpStack.log
```

I guess that's necessary to "simulate" executability for any path that could be executable, but it means that bit is no longer a meaningful signal for xonsh to use when determining commands to execute.

Indeed, `bash` happily will "execute" these files:

```
jaraco@bulletproof:~$ win32k.sys || echo done
done
```

So `xonsh` seems to be doing the "right thing" according to posix rules and the way the file system is mounted and the fact that these executable files are all on the PATH.

That said, it wouldn't be unreasonable to have a workaround in xonsh that specifically excludes files that have extensions but whose extensions aren't on PATHEXT. That would allow extensionless files with executable bits to still be run, but would exclude most of those that will never work as expected.

Interestingly, Powershell or cmd.exe don't have this problem because they don't rely on the executable bit and rely solely on the extension:

```
PS C:\Users\jaraco> win32k.sys
Program 'win32k.sys' failed to run: No application is associated with the specified file for this operationAt line:1
char:1
+ win32k.sys
+ ~~~~~~~~~~.
At line:1 char:1
+ win32k.sys
+ ~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [], ApplicationFailedException
    + FullyQualifiedErrorId : NativeCommandFailed
```

**Comment by bestlem** [comment]
As a test to see if the issue is WSL2 how do other non POSIX and non MS shells like fish perform?

**Comment by jaraco** [comment]
> As a test to see if the issue is WSL2 how do other non POSIX and non MS shells like fish perform?

I looked at bash above, but I also installed and experimented with fish, and it also seems to perform fine. My guess is that other shells like bash and fish aren't proactively scanning for executables, but instead merely attempting to locate an indicated name when executed, never having to scan for it.

**Comment by geoffreyvanwyk** [comment]
`[$PATH.remove(path) for path in $PATH.paths if path.startswith("/mnt/c/")]`

This allows me to use VI_MODE, because prompt_toolkit uses the Windows clip.exe program for VI_MODE on WSL. 

But when I start tmux, VI_MODE breaks again. For now, I have just disabled VI_MODE.
