### ISSUE TITLE
Running swaymsg sometimes fail in xonsh

### ISSUE THREAD

**Issue by g33kex** [xonsh/xonsh#4034]
The `swaymsg` command of the sway window manager seems to sometimes break with xonsh. 

## xonfig
<details> 

```
+------------------+-----------------+
| xonsh            | 0.9.24          |
| Python           | 3.9.1           |
| PLY              | 3.11            |
| have readline    | True            |
| prompt toolkit   | 3.0.8           |
| shell type       | prompt_toolkit  |
| pygments         | 2.7.3           |
| on posix         | True            |
| on linux         | True            |
| distro           | arch            |
| on darwin        | False           |
| on windows       | False           |
| on cygwin        | False           |
| on msys2         | False           |
| is superuser     | False           |
| default encoding | utf-8           |
| xonsh encoding   | utf-8           |
| encoding errors  | surrogateescape |
| on jupyter       | False           |
| jupyter kernel   | None            |
+------------------+-----------------+
```

</details>

## Expected Behavior

In `bash` or `zsh`, when I execute : 
```
swaymsg -t get_inputs
```

The command exists without error and communicate with the sway backend (it prints out a list of input devices). 

## Current Behavior

Under `xonsh`, sometimes, the command fails with the following error : 
```
[common/ipc-client.c:88] Unable to receive IPC response
```

This happens about half of the time on my machine, but it seems to be quite random. 

It seems to be related to it waiting for Inter Process Communication to happen but that's failing... I honestly do not know what exactly is happening here, but running : 
```
bash -c "swaymsg -t get_inputs"
```
Works every time. So it must be a weird problem with xonsh... 

## Steps to Reproduce

Run `sway` and to be sure to trigger the bug you can use the following code:
```python
for i in range(100):
    swaymsg -t get_inputs 1>/dev/null
```
The command will sometimes work, and sometimes fail with the error described above. Running a similar loop in bash never fails. I noticed on another machine that the bug is still present but the frequency of the error is different. 

## Things I tried

Since the error doesn't happen all the time, I thought it had to do something with threading : maybe when the command is executed in the wrong thread it can't make the Inter Process Communication? 

I tried to disable treading for that command with 
```python
__xonsh__.commands_cache.threadable_predictors["swaymsg"] = lambda x: False
```

Which did not work. Running the command enclosed in `$[ ]` also still triggers the bug. 

## Workaround

For now I'm using the following alias to force the command through `bash -c` but it's a bit annoying:
```python
def _swaymsg(args, stdin=None):
    bash -c @("/usr/bin/swaymsg "+" ".join(args))
aliases['swaymsg'] = _swaymsg
```
----------

The fact that it doesn't break all the time really puzzles me, please tell me if I'm missing something obvious here... 

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by anki-code** [comment]
Can't repeat on Ubuntu.

```python
for i in range(100):
    swaymsg -t get_inputs 1>/dev/null

# 100 lines of:
# 00:00:00.009 [swaymsg/main.c:417] Unable to retrieve socket path
```

**Comment by g33kex** [comment]
> Can't repeat on Ubuntu.
> 
> ```python
> for i in range(100):
>     swaymsg -t get_inputs 1>/dev/null
> 
> # 100 lines of:
> # 00:00:00.009 [swaymsg/main.c:417] Unable to retrieve socket path
> ```

Are you sure you're running in sway/Wayland? It will fail under X11. You can run sway from a X11 session or directly from a tty with 
```
sway
```

And then run the command in a terminal inside sway (you can use windows key + enter to open a terminal in sway).

**Comment by anki-code** [comment]
> you can use windows key + enter to open a terminal in sway

Not working.

**Comment by g33kex** [comment]
> > you can use windows key + enter to open a terminal in sway
> 
> Not working in sway in Kubuntu,

Sometimes it's ALT + enter depending on your mod key. You have to have a Wayland compatible terminal emulator installed though, such as alacritty.

**Comment by JeanMarieMineau** [comment]
I reproduced it on Archlinux.
I use an nvidia gpu, so I had to use `sway --my-next-gpu-wont-be-nvidia` to launch sway, and I launch Terminator from the configuration file (with `exec_always --no-startup-id terminator &` in `~/.config/sway/config`).
![xonsh_and_sway](https://user-images.githubusercontent.com/28675452/103155136-17394980-479d-11eb-9f2b-ace2718a806e.png)

**Comment by yaxollum** [comment]
A workaround which I found is to delete the `$SWAYSOCK` environment variable:
```
del $SWAYSOCK
```
When `$SWAYSOCK` is deleted,  swaymsg works 100% of the time. (I currently have no idea why this works though)

**Comment by yaxollum** [comment]
This issue is likely caused by some sort of a race condition, because by adding the line
```
sleep(1);
``` 
to the top of `main()` in `swaymsg/main.c`, `swaymsg` works 100% of the time.

**Comment by Qyriad** [comment]
I have this issue too with Xonsh in Sway on Archlinux, though curiously it seems like sometimes the swaymsg command actually works, even though it prints that error?

**Comment by yaxollum** [comment]
After investigating this a bit further, I've discovered that this issue is caused by the use of `pause_call_resume`:
https://github.com/xonsh/xonsh/blob/f2ca59a291a73962f9db4bf9a49d978c531e146c/xonsh/procs/specs.py#L909-L917

The PRs that introduced this usage are #1436 and #3000.

`pause_call_resume` sends `SIGSTOP` to the process, runs a function (`XSH.shell.settitle` in this case), and sends `SIGCONT` to the process:
https://github.com/xonsh/xonsh/blob/f2ca59a291a73962f9db4bf9a49d978c531e146c/xonsh/procs/pipelines.py#L777-L787

In the vast majority of cases, this works fine, but in the case of `swaymsg -t get_inputs`, it's causing an issue. This is what happens:
1. xonsh starts the `swaymsg` process
2. `swaymsg` connects to the `sway` socket, sends a request to the `sway` server that's listening on that socket, and [waits for the response using `recv()`](https://github.com/swaywm/sway/blob/89d73beedbad2d484adc85fe114680e85d391958/common/ipc-client.c#L85-L88).
3. xonsh calls `pause_call_resume`, which sends `SIGSTOP` to `swaymsg`. This stops `swaymsg` and interrupts the `recv` syscall that it is currently executing (see https://unix.stackexchange.com/a/509644 for more information)
4. `pause_call_resume` sends `SIGCONT` to `swaymsg`, causing it to continue
5. `swaymsg` gets a value of `-1` from its call to `recv()` due to the interrupted syscall. It then aborts with the message `Unable to receive IPC response`.

I'll try to create a PR to fix this issue.
