### ISSUE TITLE
FileNotFoundError in WSL when launched as a login shell, but not in subshells

### ISSUE THREAD

**Issue by eugenesvk** [xonsh/xonsh#4151]
## xonfig

<details>

```
$ xonfig
+------------------+-----------------+
| xonsh            | 0.9.27          |
| Python           | 3.9.2           |
| PLY              | 3.11            |
| have readline    | True            |
| prompt toolkit   | 3.0.16          |
| shell type       | prompt_toolkit  |
| pygments         | 2.8.0           |
| on posix         | True            |
| on linux         | True            |
| distro           | unknown         |
| on darwin        | False           |
| on windows       | False           |
| on cygwin        | False           |
| on msys2         | False           |
| is superuser     | False           |
| default encoding | utf-8           |
| xonsh encoding   | utf-8           |
| encoding errors  | surrogateescape |
| on jupyter       | False           |
| jupyter kernel   | None            |
| xontrib          | []              |
+------------------+-----------------+
```

</details>

## Expected Behavior

I'm trying to use [zoxide](https://github.com/ajeetdsouza/zoxide) with xonsh and loading it via the recommended `execx($(zoxide init xonsh), 'exec', __xonsh__.ctx, filename='zoxide')` command. I'd expect it to work regardless of how I launch xonsh, but there seems to be a difference, where a login xonsh shell fails in WSL, but a subshell within the same (or any different) shell succeeds!
(not sure whether this is an issue with zoxide or xonsh)

## Current Behavior

A newly launched xonsh in WSL can load zoxide, but can't execute its functions.
However, if I launch xonsh as a subshell (whether within xonsh or any other shell) — this time it works just fine and can execute zoxide functions

```sh
~ $ $PATH.add('/home/linuxbrew/.linuxbrew/bin/') # xonsh/zoxide are installed via LinuxBrew, so need to add it to $PATH
~ $ execx($(zoxide init xonsh), 'exec', __xonsh__.ctx, filename='zoxide')
~ $ z do
# FAILS, see traceback below

~ $ xonsh # launch xonsh as a subshell, this also works in another shell
~ $ execx($(zoxide init xonsh), 'exec', __xonsh__.ctx, filename='zoxide')
~ $ z do # now it WORKS
~/Documents $
```
### Traceback (if applicable)

<details>

```
traceback
```
xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/Cellar/xonsh/HEAD-c068720/libexec/lib/python3.9/site-packages/xonsh/procs/__amalgam__.py", line 2292, in run
    r = self.f(self.args, sp_stdin, sp_stdout, sp_stderr, spec, spec.stack)
  File "/home/linuxbrew/.linuxbrew/Cellar/xonsh/HEAD-c068720/libexec/lib/python3.9/site-packages/xonsh/procs/__amalgam__.py", line 2079, in proxy_one
    return f(args)
  File "zoxide", line 47, in __zoxide_z
  File "/home/linuxbrew/.linuxbrew/opt/python@3.9/lib/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/home/linuxbrew/.linuxbrew/opt/python@3.9/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/linuxbrew/.linuxbrew/opt/python@3.9/lib/python3.9/subprocess.py", line 1823, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'zoxide'
</details>

## Steps to Reproduce
- Use Linuxbrew to install xonsh and zoxide in WSL
- Launch it in e.g. Windows Terminal via `wsl -e /home/linuxbrew/.linuxbrew/bin/xonsh`
- Repeat the shell commands listed above

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by anki-code** [comment]
Taken a short look. I've installed zoxide on Ubuntu, created a user with xonsh shell as a login shell and put the zoxide to the xonshrc. After login the `z` command works perfect.
I think we should look into how brew+zoxide+xonsh works.

**Comment by anki-code** [comment]
Hey @eugenesvk! I made a second try.

I started from this `~/.xonshrc`:
```python
# Load Brew environment
with ${...}.swap(SHELL='/bin/bash'):  # added to tell brew the shell name in case we have different login shell
    source-bash $(/home/$USER/.linuxbrew/bin/brew shellenv)

# Load zoxide environment
execx($(zoxide init xonsh), 'exec', __xonsh__.ctx, filename='zoxide')
```
After this I got the appropriate environment with Brew and zoxide:
```
env | grep PATH
# PATH=/home/USER/.linuxbrew/bin:/home/USER/.linuxbrew/sbin: .....

zoxide
# zoxide v0.5.0-unknown
# Ajeet D'Souza <98ajeet@gmail.com>
# A faster way to navigate your filesystem

cd /tmp
z
# Going to ~
```
But:
```python
z tmp
# FileNotFoundError: [Errno 2] No such file or directory: 'zoxide'
```
To understand this error we should review the code from `zoxide init xonsh` command:
```python
def __zoxide_z(keywords: [str]):
    # ...
    __zoxide_cmd = subprocess.run(["zoxide", "query", "--"] + keywords, check=True, stdout=subprocess.PIPE)
    # ...
```
We see that z function use `subprocess.run` function with zoxide. 

Let's understand what environment has `subprocess.run`?
```python
import subprocess as sp

sp.run(['zoxide'])
# FileNotFoundError: [Errno 2] No such file or directory: 'zoxide'

sp.run(['env'])
# PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
```
Oh, `subprocess.run` has default environment without Brew paths. This is why z function is not working.

If we pass the environment to the run function it will work:
```
sp.run(['zoxide'], env={'PATH': ':'.join($PATH)})
# zoxide v0.5.0-unknown
# Ajeet D'Souza <98ajeet@gmail.com>
# A faster way to navigate your filesystem
```

I think this is not a xonsh problem. I think the zoxide developer ran xonsh from another shell that have appropriate environment to run `subprocess.run` and miss the another way when xonsh is a login shell. I suppose he should use xonsh API to run commands instead of pure `subprocess` to avoid side effects like in this issue.

Finally this means that we should use `$UPDATE_OS_ENVIRON = True` in our `~/.xonshrc` to give `subprocess.run` appropriate environment. The final `~/.xonshrc` looks like:

```python
$UPDATE_OS_ENVIRON = True

# Load Brew environment
with ${...}.swap(SHELL='/bin/bash'):  # added to tell brew the shell name in case we have different login shell
    source-bash $(/home/$USER/.linuxbrew/bin/brew shellenv)

# Load zoxide environment
execx($(zoxide init xonsh), 'exec', __xonsh__.ctx, filename='zoxide')
```

Enjoy :)

**Comment by anki-code** [comment]
Note! I've checked [how Brew get the shell name](https://github.com/Homebrew/brew/blob/c7656d09bc2ed58fe4b1715ecf48e8b4c0398b93/Library/Homebrew/cmd/shellenv.sh#L9). This could be repeated in xonsh like

```python
ps -p @(os.getpid()) -c -o comm=
# xonsh
```
So we have two news:
* the good news - the solution described above is working because Brew returns Bash export by default for unknown shell
* the bad news - when Brew implement xonsh support `source-bash` will not work and the `source-bash` command should be replaced to `source`. The bad news mostly that Brew have no ways to set the shell explicitly for the output of `brew shellenv`.

**Comment by eugenesvk** [comment]
Thanks for this investigation and a detailed explanation, @anki-code!
I'll raise an issue with the upstream and refer to your comment, meanwhile will use your fix:
```
with ${...}.swap(UPDATE_OS_ENVIRON=True):
  execx($(zoxide init xonsh), 'exec', __xonsh__.ctx, filename='zoxide')
```

**Comment by ajeetdsouza** [comment]
Hey @anki-code, thanks for your work on debugging this! I had assumed xonsh would use the same path as provided by `os.environ`, but it seems that xonsh its own internal data structure to track environment variables.

I have been trying to write zoxide's xonsh plugin in pure Python, so that I can use tooling like [black](https://github.com/psf/black) and [pylint](https://github.com/PyCQA/pylint) with it. What would be the best way of calling zoxide from pure Python? I had a look at the Xonsh code, here's what I found:
- subprocesses are called by Xonsh using a custom [`SubprocSpec`](https://github.com/xonsh/xonsh/blob/095ea292e7132c8f72ddbc23dcc38005eafce02f/xonsh/procs/specs.py#L267). This is much too complicated for what I want it to do.
- The [`locate_binary`](https://github.com/xonsh/xonsh/blob/095ea292e7132c8f72ddbc23dcc38005eafce02f/xonsh/environ.py#L2111) function seems to do what I want, I could get the binary path and then use `subprocess.run` on the result.

Is there a better way to do this than the above methods? @scopatz, I'd love your opinion on this too.

**Comment by anki-code** [comment]
Hi @ajeetdsouza! Thank you for your work on zoxide!
Take a look at [__xonsh__.subproc_*](https://github.com/xonsh/xonsh/blob/4087fc95a830e2e408c9248b83554cce935f710b/xonsh/built_ins.py#L165-L184) functions. It's the same as `$()` and `!()`.
