### ISSUE TITLE
Why xonsh need commands_cache.threadable_predictors in case when we want to just run the command?

### ISSUE THREAD

**Issue by anki-code** [xonsh/xonsh#4249]
_Originally posted by @Techcable in https://github.com/xonsh/xonsh/issues/4243#issuecomment-830621609_

> Is there a more general solution to the issues with "thread able" subprocess.
> I don't really get why xonsh has these "thread able" problems but other shells don't.

I'm also wondering why?

When we want just run the command without any threading/capturing why xonsh does not just run the command?

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by daniel-shimon** [comment]
So other shells only capture output when using `$()`, but xonsh tries to capture the output always - enabling stuff like:
```
$ run_something
$ x = _.out
```
Setting `$THREAD_SUBPROCS = False` will disable this entirely (but will still capture `$()`)

**Comment by Techcable** [comment]
> So other shells only capture output when using `$()`, but xonsh tries to capture the output always - enabling stuff like:
> 
> ```
> $ run_something
> $ x = _.out
> ```
> 
> Setting `$THREAD_SUBPROCS = False` will disable this entirely (but will still capture `$()`)

I think `$THREAD_SUBPROCS=False` should be the default (or maybe even remove the feature entirely). It's what users and subprocesses expect because that's what all other shells do.

Threading subprocesses have caused a host of compatibility and reliability issues with xonsh. I'd say it even causes most of them in my personal day to day is and makes things.

I'm an avid xonsh user but I frequently have to drop back to zsh because my terminal freezes up. Personally, I tried xonsh back in 2016 but I had to stop using it because it was so unreliable.

Thankfully, usability and reliability improved and I was able to start using xonsh again in 2020 (thank you so much). Still I've been pleagued with constant issues almost all of which seem to relate to subprocess messing up my terminal.

Python is the world's most popular programming language ([see here](https://pypl.github.io/PYPL.html)) so I think there's definitely motivation to use it as a shell. However I think most developers expect a shell to "just work" and would be willing to sacrifice a few features for a reliable shell.

Personally, I've been hesitant to contribute because of the complexity of subprocesses threading. Stripping the feature would significantly improve reliability and I think remove one of the biggest barriers to adoption 

Say what you will about `bash`/`zsh` but none of their extensions to the shell ever cause processes to mess up my terminal ☹️

**Comment by anki-code** [comment]
> So other shells only capture output when using $(), but xonsh tries to capture the output always
> x = _.out

I think this is the question around choosing the defaults. What the amazing feature that based on capturing output? AFAIK in the default xonsh there are no this kind of features and the output capturing is not needed. I know and I'm using the amazing [xontrib-output-search](https://github.com/tokenizer/xontrib-output-search) that use output capturing and this xontrib is unique [among xontribs](https://github.com/topics/xontrib).

The xonsh platform has the feature of capturing output but it is not used so wide but has wide well known issues. Probably we should think about disabling it by default. I do not suggest to do it right now I want just talking about that we should analyse the features using the scales of pros and cons.

When I ran Minicoda installer and got the freezed terminal I was feeling sad (#4199) and I understand the feelings of new users who facing with the same. I've tested the bash and it really shows nothing when run `a = $(./Miniconda.sh)`. But one difference: any bash freeze could be easily stopped by Ctrl+C instead of xonsh that could freeze the terminal entirely. I think one great feature that xonsh should has - is Ctrl+C that working forever :)

Maybe we should rethink the default behavior and run the commands in not captured mode by default in interactive prompt.

**Comment by anki-code** [comment]
Oh, god, I realized! When we run commands in interactive mode it's the same as `![]` - captured command. But in other shells interactive mode uses `$[]` - uncaptured command.

So the problem is not entirely about `THREAD_SUBPROCS`. The problem is that `THREAD_SUBPROCS` effects on many parts of system but these parts should be calibrated more in more detailed manner.

May be it should work like this:
* Interactive mode should use `$[]` (uncaptured) logic by default
* If the command run in `$()`/`!()`/`![]` (captured) it should work with `THREAD_SUBPROCS=True`
* If we put interactive tool into captured (i.e. `$()`) it should be easily closable by Ctrl+C or has appropriate support (i.e. fzf)

May be all our problems around `THREAD_SUBPROCS` are related to that this variable is so global that changes everything. Instead of having this variable we should have clean logic i.e. be uncaptured by default.

Check me please @daniel-shimon @jnoortheen.

**Comment by anki-code** [comment]
Also I've found capturing the output in two places:

1. In the run_subproc:

https://github.com/xonsh/xonsh/blob/4dc08232e615a75a524fbf96f17402a7a5b353a5/xonsh/procs/specs.py#L877-L887

2. And then in the base_shell again:

https://github.com/xonsh/xonsh/blob/4dc08232e615a75a524fbf96f17402a7a5b353a5/xonsh/base_shell.py#L388-L393


This looks like double capturing of the output.

**Comment by daniel-shimon** [comment]
I agree we need finer control over capturing. Something like:
`$XONSH_CAPTURE_INTERACTIVE` to control capturing normal commands which won't interfere with `$()` and friends

**Comment by jnoortheen** [comment]
Yes doing this will fix many issues and incompatibilities. We can use the env variable as suggested by @daniel-shimon, so that we can have some time before making this as default.

**Comment by anki-code** [comment]
We also have the tools like `sudo`. This tool mark as `uncaptured`:
```python
 __xonsh__.commands_cache.threadable_predictors['sudo']
# <function xonsh.__amalgam__.predict_help_ver>
__xonsh__.commands_cache.threadable_predictors['sudo']([])
# False
```
But we want to do things like `out = !(sudo ls)` but this is not working:
```python
# Open fresh session without sudo login
!(sudo ls)  # we expect the password prompt here
# CommandPipeline(
#   executed_cmd=['sudo', 'ls'],
#   input='',
#   output='',
#   errors=None
# )
```
And manipulation with predictor or THREAD_SUBPROC will have no effect.

We should have support or more detailed euristic.

**Comment by gforsyth** [comment]
Hey all -- great conversation here.
For a bit of context -- when @scopatz and I added in the dual outputs (to stdout and also captured) we were both in the sciences and saving the outputs of commands was sort of paramount for our work, and our work was driving the features in xonsh.
I agree, at this stage, that it is more trouble than it is worth (or at least that it should be more configurable / tunable).

**Comment by daniel-shimon** [comment]
> But we want to do things like out = !(sudo ls) but this is not working:

@anki-code Note that `$(sudo ls)` does work.
There's some funny business with `!()` going on :)

**Comment by jnoortheen** [comment]
can someone explain why [PopenThread](https://github.com/xonsh/xonsh/blob/985773a5c1278c4a5a643b882a2229a7a36a66a8/xonsh/procs/posix.py#L44) has to be a sub-class of Thread?. 

As I understand we need to watch the input/output streams but starting popen itself inside a thread is not necessary, since Popen() is not blocking. I think some of the problem caused by using Thread to start the process is why it is not able to handle signals.
