### ISSUE TITLE
[Feature Request] Xonsh as a decorator

### ISSUE THREAD

**Issue by traverseda** [xonsh/xonsh#429]
I'd like to be able to decorate a function and have it run via xonsh. Not sure how to even approach such a thing, it's too complicated for me.

I could probably hack *something* together using multiprocessing, but ideally it wouldn't serialize/deserialize the data for every call. Anyone have any idea how to do this?

**Comment by scopatz** [comment]
Hi @traverseda, this is an interesting idea that would probably take a number of ugly hacks to implement.  

However, we already have import hooks so that you can mix xonsh and python files in the same project. See this part of the turtorial: http://xonsh.org/tutorial.html#importing-xonsh-xsh

So the easy thing to do would be to write all your xonsh functions in an .xsh file and then import these into the Python file where you want to call them.  Just note that before you import any xonsh files, you have to load the import hook, which you can do easily by sticking the following *somewhere* in your project:

```python
from xonsh import imphooks
```

I hope this helps.

**Comment by traverseda** [comment]
Cool, thanks. Don't remember that from when I first started, but that's perfect.
