### ISSUE TITLE
Vim mode?

### ISSUE THREAD

**Issue by jerabaul29** [xonsh/xonsh#4292]
Is there / what are options to get a vim mode on the full terminal (ie I would like to use vim mode on both the prompt and the previous commands and outputs)? I looked at xontribs, and there is a prompt-vi package, but it seems outdated and not maintained. Is there any native way to do that? :)

**Comment by anki-code** [comment]
Hi @jerabaul29! Try to set [`$VI_MODE`](https://xon.sh/envvars.html#vi-mode):
```python
pip install 'xonsh[full]'  # to install prompt-toolkit
echo @('$VI_MODE = True') >> ~/.xonshrc
# restart xonsh
```

**Comment by jerabaul29** [comment]
Thanks, that really helped :) A small note, my ```.xonshrc``` looked by default something like:

```
# XONSH WEBCONFIG START
# XONSH WEBCONFIG END
```

So adding with the echo just appended to the last comment; but I added by hand, and that works fine :) .

**Comment by jerabaul29** [comment]
A few comments though:

- some vim commands are not available; for example, if I do ```10 a - ESC```, that only inserts one -, not 10
- it is only possible to navigate the current prompt line, not what is above. For example, in a situation like:
 
```$> some_command
some_interesting_output_1 some_interesting_output_2
$> my_prompt_is_here```

I cannot navigate in vim-mode to copy ```some_interesting_output_2``` as if the whole terminal was a single file that I navigate with vim; any idea if this is attainable? :)

**Comment by anki-code** [comment]
I'm not the user of vi-mode so I just put here the two references:
* The vi-mode is from prompt-toolkit package - https://python-prompt-toolkit.readthedocs.io/en/master/pages/asking_for_input.html#vi-input-mode - you can create issues and PRs in this upstream project.
* We have PRs that do magic with prompt and I think you can implement what you need - https://github.com/xonsh/xonsh/pull/4275

I'm going to close this issue because it's mostly the question. You can create distinct issues that have new feature requests or bugs. Thanks!
