### ISSUE TITLE
ptk: pressing Backspace deletes an entire word instead of a single character

### ISSUE THREAD

**Issue by yaxollum** [xonsh/xonsh#4407]
## xonfig

```
+------------------+----------------------+
| xonsh            | 0.10.1               |
| Git SHA          | f5acbe30             |
| Commit Date      | Jul 31 17:38:31 2021 |
| Python           | 3.9.6                |
| PLY              | 3.11                 |
| have readline    | True                 |
| prompt toolkit   | 3.0.18               |
| shell type       | prompt_toolkit       |
| history backend  | sqlite               |
| pygments         | 2.9.0                |
| on posix         | True                 |
| on linux         | True                 |
| distro           | arch                 |
| on wsl           | False                |
| on darwin        | False                |
| on windows       | False                |
| on cygwin        | False                |
| on msys2         | False                |
| is superuser     | False                |
| default encoding | utf-8                |
| xonsh encoding   | utf-8                |
| encoding errors  | surrogateescape      |
| on jupyter       | False                |
| jupyter kernel   | None                 |
| xontrib          | []                   |
+------------------+----------------------+
```

## Expected Behavior
When Backspace is pressed, a single character to the left of the cursor should be deleted.

## Current Behavior
When Backspace is pressed, the entire word to the left of the cursor gets deleted.

## Steps to Reproduce
1. Open a prompt-toolkit xonsh shell (updated to the latest `main`)
2. Type a word (e.g. `hello`)
3. Press Backspace

I think this issue was introduced by PR https://github.com/xonsh/xonsh/pull/4402, which was intended to make <kbd>Ctrl+Backspace</kbd> delete a word, but it unintentionally also changed <kbd>Backspace</kbd> to delete a word.

I have been able to produce this behavior on multiple terminal emulators: Alacritty, Gnome Terminal, and Konsole.

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by daniel-shimon** [comment]
Hi!
I see something wierd happened with that pr since it doesn't work for me locally at all right now (and it used to work for sure), so something got messed up 🤔
I'll look into it

**Comment by daniel-shimon** [comment]
In those terminal emulators, what do you see when running `cat` and pressing ctrl-backspace?

**Comment by yaxollum** [comment]
I see a `^H` for each ctrl-backspace that I press.

If I try running `cat | hexdump -C`, and then use the following keystrokes:
1. ctrl-backspace
2. ctrl-backspace
3. ctrl-backspace
4. Enter
5. Ctrl-D

This is the output of `hexdump`:
```
00000000  08 08 08 0a                                       |....|
00000004
```

**Comment by paul-ollis** [comment]
The key combinations `<Control-Backspace>` and `<Backspace>` are not guaranteed to
produce different results. Sometimes <Backspace> actually produces `<Del>`, in
which case PR #4402 will have the intended behaviour, but it depends.  Some
terminals may produce `<C-H>` (code 8) when `<Backspace>` is pressed, in which case
there is no difference between `<Control-Backspace>` and `<Backspace>`.

When prompt-toolket is in use, `<Del>` is converted to `<C-H>` in order to make
things behave consistently regardless of terminal behaviour. So again, there is
no difference between `<Control-Backspace>` and `<Backspace>`.

The botton line is that there is no practicable and portable way to distinguish
the two key combinations differently.

So, unfortunately, PR #4402 really needs to be reversed.
