### ISSUE TITLE
"C-x C-e does not honor $EDITOR"

### ISSUE THREAD

**Issue by kamou** [xonsh/xonsh#4619]
executing key binding `C-x C-e` should load the current command line into `$EDITOR`.

## Expected Behavior

executing key binding `C-x C-e` should load the current command line into `$EDITOR`.

## Current Behavior
executing key binding `C-x C-e` loads the current command line into nano.

## Steps to Reproduce

```
$EDITOR="/usr/bin/vim"
echo edit me # hit C-x C-e
```

**Comment by kamou** [comment]
this seems to be related to the fact that `os.environ` and the xonsh environment variables are not in sync.
```
$EDITOR="/usr/bin/nvin"
import os
os.environ.get("EDITOR")
```
this outputs:
```
'/usr/bin/nano'
```
but `prompt_toolkit uses os.environ.get("EDITOR")` to resolve the prefered editor.
see `/usr/lib/python3.9/site-packages/prompt_toolkit/buffer.py`

**Comment by kamou** [comment]
a workaroutn is to add the following in my rc file:

```
$VISUAL="/usr/bin/nvim"
os.environ["EDITOR"] = "/usr/bin/nvim"
```

but I think we can all agree this is not very clean

**Comment by kamou** [comment]
maybe this is a bug with prompt_toolkit and not xonsh. I'm not sure.

**Comment by kamou** [comment]
just found `$UPDATE_OS_ENVIRON`
just for my education, is there a particular reason this is not set to `True` by default ?

**Comment by gforsyth** [comment]
Hey @kamou -- sorry for the delay in responding.  I'm glad you found the `UPDATE_OS_ENVIRON` option.

It's a fuzzy case and I can't remember all the details, but generally if you were to start up a Python repl, you would only update `os.environ` via the `os` module.  Since `xonsh` _is_ a Python repl it's sort of an undefined case.  I'm not opposed to setting it to `True` by default, but I'll need to think for a bit to see if i remember any reason why that would be a bad idea.

**Comment by gforsyth** [comment]
Closing as answered
