### ISSUE TITLE
`_print_exception` got an unexpected keyword argument (latest commit on `main`)

### ISSUE THREAD

**Issue by Techcable** [xonsh/xonsh#4665]
## xonfig

<details>

```
+------------------+--------------------------+
| xonsh            | 0.11.0                   |
| Git SHA          | 4af68065                 |
| Commit Date      | Jan 8 20:16:06 2022      |
| Python           | 3.9.10                   |
| PLY              | 3.11                     |
| have readline    | True                     |
| prompt toolkit   | 3.0.23                   |
| shell type       | prompt_toolkit           |
| history backend  | sqlite                   |
| pygments         | 2.11.2                   |
| on posix         | True                     |
| on linux         | False                    |
| on darwin        | True                     |
| on windows       | False                    |
| on cygwin        | False                    |
| on msys2         | False                    |
| is superuser     | False                    |
| default encoding | utf-8                    |
| xonsh encoding   | utf-8                    |
| encoding errors  | surrogateescape          |
| on jupyter       | False                    |
| jupyter kernel   | None                     |
| xontrib 1        | back2dir                 |
| xontrib 2        | fish_completer           |
| xontrib 3        | jedi                     |
| xontrib 4        | readable-traceback       |
| xontrib 5        | term_integration         |
| RC file 1        | /Users/nicholas/.xonshrc |
+------------------+--------------------------+
### 
```

</details>

## Expected Behavior
Xonsh should not crash when there is a NameError in the "compiled code"

## Current Behavior
It crashes when I get a `NameError` (see below)

### Traceback (if applicable)

<details>

```
Traceback (most recent call last):
  File "/Users/nicholas/git/xonsh/xonsh/base_shell.py", line 390, in default
    raise exc_info[1]
  File "/Users/nicholas/git/xonsh/xonsh/codecache.py", line 63, in run_compiled_code
    func(code, glb, loc)
  File "<stdin>", line 1, in <module>
NameError: name 'doc' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/nicholas/git/xonsh/xonsh/main.py", line 435, in main
    sys.exit(main_xonsh(args))
  File "/Users/nicholas/git/xonsh/xonsh/main.py", line 479, in main_xonsh
    shell.shell.cmdloop()
  File "/Users/nicholas/git/xonsh/xonsh/ptk_shell/shell.py", line 392, in cmdloop
    self.default(line, raw_line)
  File "/Users/nicholas/git/xonsh/xonsh/base_shell.py", line 401, in default
    print_exception(exc_info=exc_info)
TypeError: _print_exception() got an unexpected keyword argument 'exc_info'
```

</details>

## Steps to Reproduce
In a new shell, type `doc(dis)` without either `dis` or `doc` loaded

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by Techcable** [comment]
Could also be because I have the `readable-traceback` contribution enabled....

**Comment by gforsyth** [comment]
Hey @Techcable -- I can reproduce this on `main` -- can you see if this happens to you when you start with `--no-rc`?

**Comment by alvarv** [comment]
I apologize in advance, since I have not really looked into how the completer works before posting this... But the fact that it only fails in this way when completing the specific command "code", made me think the problem was not in xonsh, or at least caused by something external.
I do have this same behaviour in two machines, so I checked and my file `/usr/share/bash-completion/completions/code` starts with
```bash
_code()
{
        local cur prev words cword split
        _init_completion -s || return

       _expand || return    ##  < ==

        case $prev in
...
```
whereas other completion files lack this line marked above with `<==`.  As I said, I have not really looked into what `_expand` does (presumably expansion, replacing `~` and perhaps environment variables), but since this is not present in other completion files, I've tried commenting it out, and it fixes the issue (but `~/something` is no longer "completed" into `/home/username/something`; `code` does not seem to mind that, though).

Hope this helps someone more knowledgeable fix the issue... in fact `bash` works OK without commenting this line, so perhaps there is a small bug in how xonsh reuses these files.

**Comment by Techcable** [comment]
The minimal `.xonshrc` to reproduce this issue is here: https://gist.github.com/228202949e79c0b373cf0a56b7a16848

It would appear that this is a `xontrib-readable-backtrace` bug not a xonsh bug.

**Comment by vaaaaanquish** [comment]
Currently under investigation.
link: https://github.com/vaaaaanquish/xontrib-readable-traceback/issues/7

**Comment by vaaaaanquish** [comment]
@Techcable Hi. This bug has been resolved.
Please install `xontrib-readable-traceback==0.4.0` 
ref: https://pypi.org/project/xontrib-readable-traceback/0.4.0/
