### ISSUE TITLE
XONSH_CTRL_BKSP_DELETION does not work in kitty, also typo in changelog ($XONSH_CTRL_BKSPC_DELETION)

### ISSUE THREAD

**Issue by con-f-use** [xonsh/xonsh#4751]
The [changelog has an extra "C"](https://github.com/xonsh/xonsh/commit/337cf25a40e18e95050e812a1d1b7ac8bf6f3335#diff-2c623f3c6a917be56c59d43279244996836262cb1e12d9d0786c9c49eef6b43cR22) in `$XONSH_CTRL_BKSPC_DELETION`, when mentioning the [new feature](https://github.com/xonsh/xonsh/blob/bff0794b68f0d9266d8d920f10170c982927ccf6/xonsh/ptk_shell/key_bindings.py#L226).

Also, <kbd>Ctrl</kbd> + <kbd>🢨</kbd> does not work in [kitty](https://sw.kovidgoyal.net/kitty/).

**Comment by con-f-use** [comment]
heh, I typoed the typo reporting.

**Comment by yaxollum** [comment]
Hi @con-f-use! `Ctrl+Backspace` works for me in kitty when I use the `prompt-toolkit` shell. It doesn't work on `readline` because, as you can see in the code you've linked to, this feature is specific to `prompt-toolkit` (it's in the [ptk_shell](https://github.com/xonsh/xonsh/tree/main/xonsh/ptk_shell) directory). 

Can you try using `prompt-toolkit`? Just do
```
pip install prompt-toolkit
```
and then open a new xonsh shell afterwards

**Comment by con-f-use** [comment]
Thanks peter, prompt-toolkit is installed for me, and xonsh seems to use it. :eyes: 

![image](https://user-images.githubusercontent.com/11145016/162948031-a0136f30-7c3b-4171-887b-15e50e339e05.png)

Still no action on <kbd>Ctrl</kbd> + <kbd>🢨</kbd>. Works if I use e.g. `st` or `gnome-terminal`.

**Comment by yaxollum** [comment]
Wow, that's weird! In a xonsh shell, could you try doing
```
$XONSH_CTRL_BKSP_DELETION=True
kitty xonsh --no-rc
```
and then seeing if `Ctrl+Backspace` works in the new kitty terminal that you launch?

**Comment by con-f-use** [comment]
That doesn't change the behavior. However, it must be something in my kitty configuration, because when I do

```
kitty --config /dev/null xonsh
```

Ctrl + Backspace works.
