### ISSUE TITLE
bash aliases with variables do not work

### ISSUE THREAD

**Issue by jlec** [xonsh/xonsh#533]
I have defined
```bash
$ (0) type ll
ll is aliased to `ls ${LS_OPTIONS} -lh'
$ (0) echo ${LS_OPTIONS}
--color=auto --group-directories-first -F
```
If I run ```ll``` in ```xonsh```I see
```shell
$ ll
/usr/local/opt/coreutils/libexec/gnubin/ls: cannot access ${LS_OPTIONS}: No such file or directory
/usr/local/opt/coreutils/libexec/gnubin/ls: cannot access ${LS_OPTIONS}: No such file or directory
$ echo $LS_OPTIONS
--color=auto --group-directories-first -F
```

**Comment by scopatz** [comment]
OK, I believe that this is because `xonsh.built_ins.expand_path()` is not being called on each alias element as it is being evaluated.  This should be a relatively quick fix in the Aliases class. If someone wants to take a stab at this, that'd be great!

Also, note that in your example above you should `echo $LS_OPTIONS` in xonsh rather than `echo ${LS_OPTIONS}`.

**Comment by gforsyth** [comment]
Closing this.  Alias expansion is supported within alias definition.  Please reopen if any issues persist.  Thanks!
