### ISSUE TITLE
Variable expansion shouldn't work on single quoted string

### ISSUE THREAD

**Issue by zn** [xonsh/xonsh#539]
Step to reproduce:

1. Install xonsh via `pip`
2. run command `echo 'Hello' | perl -ne 'print "$_"'`

Expected result: display `Hello`

Actual Result: display `/usr/bin/env` (Without newline)

Tested Environment:

- Linux (Fedora 23)
- perl v5.22.0
- Python 3.4.3
- xonsh v0.2.3 (Installed from `pip install https://github.com/scopatz/xonsh/archive/master.tar.gz`)

(got same bug on virtualenv install and root install(`sudo pip install xonsh`)

![image](https://cloud.githubusercontent.com/assets/830515/11456818/96eb70ba-96d9-11e5-955c-890429812e35.png)

**Comment by scopatz** [comment]
Thanks for reporting @zn.  I am not a perl expert, so I am not sure exactly what `$_` is suppossed to signify. Usually this is an environment variable for the command that is currently being run.  (So I guess we are launching something with an env prefix). Perl seems to use this as an alternative to stdin?

**Comment by zn** [comment]
oops. I think I'd reported wrong problem. It seem the real problem is about variable substitution on single-quoted string, not about perl.

**Comment by scopatz** [comment]
There is no difference in singly and doubly quoted strings. But I think I see what you are referring to. There is no way to have $VAR pass through the srting.  Maybe \$VAR will work?  We just use os.path.expandvars()

**Comment by zn** [comment]
`\$VAR` doesn't work.. but I found workaround by assigning `$_` to another variable.
```sh
user $ echo '$_'
/usr/bin/env
user $ echo '\$_'
\/usr/bin/env

# assign $_ to other variable
# work as expected result
user $ $__ = '$_'
user $ echo '$__'
$_
user $ echo 'It work as expected!' | perl -ne 'print "$__"'
It work as expected!
```

**Comment by adqm** [comment]
Another way is to build the strings using Python-mode explicitly (since strings in Python mode don't do the expansion of environment variables):
```
hartz@compy-488 ~ $ echo @("$_")
$_
hartz@compy-488 ~ $ echo "Hello!" | perl -ne @('print "$_"')
Hello!
```

**Comment by scopatz** [comment]
Ahh ok.  I see now. We still should think about implementing \$ as an escape.  This would have to happen in `xonsh.environ.expand_path()`.

**Comment by adqm** [comment]
Alternatively, we could just make strings never do the env variable expansion (which is actually the behavior I expected until I looked at the source).  _But_, that has an issue in that it makes it more complicated to do the expansion:

```
echo "$HOME is where the heart is"
```
versus
```
echo @($HOME + " is where the heart is")
```

That, and I guess it makes sense that strings in subproc mode behave a bit differently from strings in Python mode (though this wasn't what I expected).

Maybe the easiest answer to keep everyone happy(ish) is the \$ escape.  _But_, escaping subproc-mode strings seems like a can of worms I don't want to open, since I'm not sure how many other escapes we'll want to implement beyond \$.  It's likely we'd end up with escaping rules in subproc mode that are just as weird as those in, e.g., Bash.

Anyway, this seems like something that might continue to come up, so my vote goes to one of:
* leave as is, document that `@()` is the way to avoid expansion
* don't do expansion in any strings, document that `${}` is the way to do expansion

with a slight preference for the second, since it "feels right" to me that strings are always Python strings (though I could go either way here).

**Comment by scopatz** [comment]
> It's likely we'd end up with escaping rules in subproc mode that are just as weird as those in, e.g., Bash.

Yeah, I agree now that you point it out.

> a slight preference for the second, since it "feels right" to me that strings are always Python strings (though I could go either way here).

Again, I have the a slight preference for the second as well, and that it how it was until the v0.2.3.  But too many people were complaining that it didn't work the way they expected.  I think that we can do two things then:

1. document that `@()` avoids expansion, like you said
2. perhaps add another environment variable that switches this expansion on and off.  The default should probably be on, as it is now.

**Comment by scopatz** [comment]
The above point have been implemented and single and double quotes will remain as in Python.
