### ISSUE TITLE
Main branch regress: redirect to python substitution

### ISSUE THREAD

**Issue by anki-code** [xonsh/xonsh#5466]
```xsh
xonsh --no-rc
echo 1 > @('/tmp/tmp')
# xonsh: None: unable to open file # it's from specs.py:resolve_redirects because parsing is wrong
```

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by yaxollum** [comment]
Hi @anki-code , thanks for investigating this issue! The reason why the `@()` operator outputs a list is that it can produce multiple arguments. For example:
```python
echo @(['hello','world'])
# Output: hello world

echo @(['a','b'])@(['c','d'])
# Output: ac ad bc bd
```

I don't think it's possible to fix this issue in the parser because in some cases we only know the length of the list at runtime:
```python
mylist = ['a']
echo hello > @(mylist) # should redirect output to file 'a'

mylist = ['a', 'b', 'c']
echo hello > @(mylist) # should produce an error since we cannot output to multiple files
```

Considering this, I think the fix that you provided in #5423 is probably the best solution.
