### ISSUE TITLE
When I run a builtin command (i.e. xonfig -h, xontrib -h, etc.) the shell exits

### ISSUE THREAD

**Issue by anki-code** [xonsh/xonsh#5689]
_Originally posted by @Serrindipity in https://github.com/xonsh/xonsh/discussions/5688_

Whenever I run an invalid xonsh command (i.e. xonfig -h, xontrib -h, etc.), the shell exits. I'm pretty new to all of this, so I'm not sure if I'm doing something wrong. This persists even when running xonsh --no-rc --no-env

Xonsh is installed with brew, version 0.18.3 on MacOS.

I've tried uninstalling and re-installing as well. Not sure what's happening.

**Comment by Spitfire1900** [comment]
https://github.com/xonsh/xontrib-vox/issues/12 may be caused by this issue.

**Comment by Serrindipity** [comment]
I'd be willing to work on this, but I'm not sure where to start. I'm pretty new here, what's the best way to start digging into the issue?

**Comment by Serrindipity** [comment]
It looks like when end() is called in pipelines.py, it never gets to self._return_terminal() at line 479. I think it just errors on self._end(tee_output=tee_output), the line before it.

**Comment by yaxollum** [comment]
@anki-code I think the issue is that xonsh uses `argparse.ArgumentParser` to implement `xonfig`, but the code that prints the help message in `ArgumentParser` calls `sys.exit()`:

https://github.com/python/cpython/blob/a67a39272c61de5202c44690d10a385c9ecaf97c/Lib/argparse.py#L1142-L1144

https://github.com/python/cpython/blob/a67a39272c61de5202c44690d10a385c9ecaf97c/Lib/argparse.py#L2656-L2659

The changes made in #5399 cause xonsh to no longer catch the `SystemExit` exception that is raised by `sys.exit()`:
```xonsh
# Before the change:
import sys
sys.exit() # nothing happens

# Now:
import sys
sys.exit() # shell exits
```

I think this is the correct behaviour in general, but for this specific case, `ArgumentParser` causes the entire shell to exit. We could probably fix this by catching `SystemExit` in the [`ArgParserAlias`](https://github.com/xonsh/xonsh/blob/31170c2dafdec1c3208b566a6359da9f1a1b9842/xonsh/cli_utils.py#L560) class.
