### ISSUE TITLE
Adopt a commit/PR guideline

### ISSUE THREAD

**Issue by BYK** [xonsh/xonsh#752]
I've been contributing to the ESLint project for a while and they have a guideline around how commit messages should be formatted in PRs: http://eslint.org/docs/developer-guide/contributing/pull-requests#step-2-make-your-changesa-namestep2a

This makes the commit history very clear, clean and easy to reason about. It also allows tooling to automatically generate changelogs by using these tags.

The behavior is enforced by repo maintainers, a bot and CI which all checks the formatting of the latest commit and makes sure there is only 1 commit in the PR.

I think adopting this would be great for Xonsh. What do you think?

**Comment by scopatz** [comment]
Thanks for bringing this up @BYK!  

Personally I am a little wary of enforcing these kinds of conventions, because at least the way I work, not every commit corresponds naturally to one of the tags. I also believe that it discourages commits (though I only have anecdotal evidence for this), which I consider somewhat undesirable since it leads to fewer, larger commits that make it harder to bisect.  

That said, the ESLint conventions are pretty lightweight.  I wouldn't mind directing people to something like this, if they wanted to optionally follow a convention.

Anyways, those are my two cents. Happy to hear other people's thoughts.

**Comment by melund** [comment]
I am mostly with @scopatz on this. I really like that PRs consist of many commits so I can see the development process. Also in reviews it is nice to see the changes made, instead of just looking an amended commit with everything.

**Comment by BYK** [comment]
@melund we can still have many commits in a PR and then squash them before getting merged. That's how we do at where I work too but up to you of course :)

**Comment by adqm** [comment]
I don't have a strong feeling one way or the other.  I think there are pros and cons either way.

If we did adopt the "squash everything" approach, I think we would need to be more careful about having only one feature per pull request (rather than the current approach of changing other things along the way).

**Comment by BYK** [comment]
>If we did adopt the "squash everything" approach, I think we would need to be more careful about having only one feature per pull request (rather than the current approach of changing other things along the way).

I think this is a good thing. This is actually one of the reasons I proposed the change :)

**Comment by gforsyth** [comment]
I agree that one feature per PR is a good thing -- I'm of a mixed mind towards rebasing.  I like when there's history in a PR, including feedback and fixes -- makes for a good learning tool for newer contributors.  Also shows them that it's ok if they get something wrong.  

That said, I don't need to pile on commits to fix typos, etc...

In re: the automated changelog, if we don't adopt the commit convention, this does seem like something the new PR templates can help with -- forcing people to label what it is and what it does.

**Comment by scopatz** [comment]
I am not a fan of squashing commits before merge, personally.  If other folks want to do it, I don't mind but I think it adds too much burden and sacrifices the actual history, as per what @gforsyth said.

> In re: the automated changelog, if we don't adopt the commit convention, this does seem like something the new PR templates can help with -- forcing people to label what it is and what it does.

The changelog, which was mostly taken from http://keepachangelog.com/, actually explicitly warns against using history messages as the changelog. Having done this before on other projects, I actually agree.  It ends up being too much or too little information to be helpful.

I don't know. I guess my central point is that I'd like it to be easy to do work on the project and easy to contribute. That is my take at least :).

**Comment by scopatz** [comment]
Also, I recognize that I may be a little more fast and loose on this stuff than most people. I think it is because what I care about in open source is having more eyes.

**Comment by astronouth7303** [comment]
So I think we've collectively agreed on a "history is immutable" approach?

This just makes good commit messages better, because you won't be fixing them later. In that vein, I think https://chris.beams.io/posts/git-commit/ is good reading.

**Comment by scopatz** [comment]
Closed due to age. Please feel free to reopen.
