### ISSUE TITLE
Switch tests to pytests

### ISSUE THREAD

**Issue by scopatz** [xonsh/xonsh#918]
B y popular demand...

**Comment by melund** [comment]
I really vote for this, although I dread the work of porting the tests. Not all our `nose` stuff is really pytest compatible. 

It is much more fun to write tests using pytest. Less code and more flexibility. It is also insanely easy to write extension to pytest. The flexibility and extensibility could allow us to create pytest extension that collected `test_*.xsh` files and run them. That shuold be simple.

Maybe we could even make pytest extension that run top level integration tests. So we can test the actual user interface. I have no clue how we approach this, so any help is appreciated. What can we learn from other projects? 

Here is a good introduction to pytest if you haven't used it before:
http://pythontesting.net/framework/pytest/pytest-introduction/

**Comment by scopatz** [comment]
Thanks for adding the details here @melund!

**Comment by laerus** [comment]
we rly need to make this happen before we reach 99% coverage :laughing:

@gforsyth if you could give any hints on where to start on the pytest_port branch i can help with this, or i can just jump in and start brawling with nose.

**Comment by gforsyth** [comment]
Hey @laerus -- that's great!  I've been meaning to dig into that again but I haven't had much time to get in really deep on it (I'm also relatively new to pytest which isn't helping).  I'll merge in recent changes to the branch since a bunch of new tests were added, which may introduce further incompatibilities but the two main pain points were in `test_main.py` and `test_imphooks.py` if you want to take a look at those.  

I'm pretty sure it's due to differences in mocking and patching but I could be wrong on that.

**Comment by laerus** [comment]
we can also use pytest-mock which is a neat plugin

**Comment by melund** [comment]
Let us see how far we can get with plain pytest. But you are right. There are many really neat plug-ins.

**Comment by laerus** [comment]
Mission Accomplished!
