### ISSUE TITLE
Autocomplete: don't display full path

### ISSUE THREAD

**Issue by sebastien** [xonsh/xonsh#937]
Using  `prompt_kit`, when completing a path such as `/var/log/<TAB>`, the autocompletion menu shows fully prefixed entries. The problem is that when the path is very deep, the autocomplete panel starts to give unreadable results (see attached screenshot).

The proposed solution is to only display the `os.path.basename` of the autocompleted path, suffixed by `/` if it is a directory.

![screenshot from 2016-05-19 10-33-09](https://cloud.githubusercontent.com/assets/14598/15397392/1170b2b8-1dae-11e6-85b4-ea31504f9346.png)

**Comment by GuillaumeLeclerc** [comment]
maybe we could use my work in #899 to solve this problem ?

**Comment by adqm** [comment]
Good call; thanks for bringing this up, @sebastien!

@GuillaumeLeclerc, that's an interesting idea.  Using `os.path.basename` would be consistent with what bash does, and would involve less clutter, so that probably gets my vote, but using the shortened path might be interesting, too.

**Comment by sebastien** [comment]
The only case I see where `os.path.basename` does not work is that when you're completing from `CDPATH` and you might have more than one root for the completions. In that case, it would be good to use a path shortener to disambiguate the source.

The logic might be something like:

- If the expression to complete matches only one source, or is absolute, use `os.path.basename`
- If the expression to complete matches more than one source (ie, has at least one match in one of the CDPATH entries), then prefix these with a shortened path.

**Comment by scopatz** [comment]
Thanks for reporting @sebastien!  While there are things that I think we can do on the xonsh side to make this less likely on to occur, there are probably going to be edge cases we can't anticipate (like tab completing long variable names in Python).

I think that this should probably be reported to prompt-toolkit, in order to get a more complete solution. But maybe we are just doing things wrong on our end too.  Thoughts @jonathanslenders?
