### ISSUE TITLE
Cannot Crlt-C out of wizard in readline shell

### ISSUE THREAD

**Issue by scopatz** [xonsh/xonsh#956]
This is part of deeper issues with Crtl-C and readline that I can't figure out right now. I have tried a bunch of things, but none of them seem to work.

**Comment by GuillaumeLeclerc** [comment]
It may worth nothing and I don't know what you tried but if you send some signal using kill at some point you may want to try sending the signals to the whole process group instead of a specific process.

This is what fixed all my problems regarding signals when I was trying to fix #855 and other issues related to job control

**Comment by scopatz** [comment]
See potential fix in #2212

**Comment by scopatz** [comment]
Closing this due to #2212, please feel free to reopen!
